### ISSUE TITLE
PeerPool / Discovery don't answer event bus requests after some time

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#100]
### What is wrong?

Yesterday I put #1556 to work on a server ant today I noticed that the node has more or less stalled with the log being overwhelmed by these warnings.

```
 WARNING  12-12 08:36:55       EthstatsService  Timeout: PeerPool did not answer PeerCountRequest
 WARNING  12-12 08:36:56           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:36:59           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:00       EthstatsService  Timeout: PeerPool did not answer PeerCountRequest
 WARNING  12-12 08:37:01           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:04           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:06       EthstatsService  Timeout: PeerPool did not answer PeerCountRequest
 WARNING  12-12 08:37:06           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:09           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:11           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
 WARNING  12-12 08:37:11       EthstatsService  Timeout: PeerPool did not answer PeerCountRequest
 WARNING  12-12 08:37:14           ETHPeerPool  Discovery did not answer PeerCandidateRequest in time
```

The interesting thing here is, I noticed this one before:

>EthstatsService  Timeout: PeerPool did not answer PeerCountRequest

And so far, I thought this may just be the `PeerPool` being to busy to answer the request by the `EthstatsService` timely.

But now after seeing this one, I feel like I need to look deeper into this.

>ETHPeerPool  Discovery did not answer PeerCandidateRequest in time

I also ran `trinity attach` to see if `w3.net.peerCount` would be responding and in fact it times out. The same happens with `w3.net.version` which isn't even served from the PeerPool (but it is still running on the same event loop / event bus endpoint)

This leads to the question what if there is some form of memory leak / bug in lahja where after some time, the event bus just stalls and cant process any further messages.

### How can it be fixed

There are two things I plan to do:

1. I will take the existing lahja benchmark and start it with parameters that will effectively cause a very long run over several hours to see if they stall at some point. This can give us an indicator if there's something wrong with lahja.

**Update**: Started this now: `python scripts/perf_benchmark.py --num-processes 10 --num-events 36000 --throttle 0.5 &> benchmark2.log`

This should push broadcast one event every 0.5 seconds, to 10 connected processes, 36000 events in total. If my math is correct, this would run over the next 5 hours.

2. I will write a tiny stupid plugin to just ping pong messages via the EventBus that I will run in the context of Trinity for several hours to see if that stalls as well. This can give us an indicator if there's something wrong with how the event bus is integrated in Trinity or it may also show us that there's no problem with the EventBus but with the PeerPool / Discovery instead.

3. Looking through the logs to find anything suspicious around the time when it stops responding to requests.

**Comment by lithp** [comment]
This just happened to me while running d6b746ca (master), including the  `w3.net.peerCount` and `w3.net.version` timeouts, and #98 during shutdown.

Looking at the processes, one of them was using 100% of CPU, and sampling the stack with py-spy almost always gave me:

```
 [there were sometimes some extra frames here]
_find_oldest_unpruned_task_id (/home/github/trinity/trinity/_utils/datastructures.py:658)
_prune_finished (/home/github/trinity/trinity/_utils/datastructures.py:634)
_mark_one_task_complete (/home/github/trinity/trinity/_utils/datastructures.py:620)
inner (eth_utils/functional.py:46)
<genexpr> (/home/github/trinity/trinity/_utils/datastructures.py:601)
_mark_complete (/home/github/trinity/trinity/_utils/datastructures.py:601)
register_tasks (/home/github/trinity/trinity/_utils/datastructures.py:557)
_fetch_segment (/home/github/trinity/trinity/sync/common/headers.py:677)
launch_node (/home/github/trinity/trinity/main.py:163)
[a few more frames]
```

I don't know what the mapping of services to pids is but is it possible that the Discovery and RPC services are also running in this process and being starved of CPU?

**Comment by pipermerriam** [comment]
My intuition agrees with @cburgdorf 's assesment here that our networking process is simply being overloaded.  Step one would be to validate this assertion.  Assuming it is correct, then I think we should prioritize https://github.com/ethereum/trinity/issues/79 and work on separating our peer/networking and sync into separate processes.

**Comment by lithp** [comment]
I think it's something more than just overload. I can (not reliably but pretty consistently) trigger this by using cgroups and capping cpu usage. On my machine giving trinity 20% of the cpu (`cpu.cfs_quota_us` of `20000`) while it's in the middle of syncing with a peer will often trigger it. That sounds like overload, but once this has been triggered removing the quota doesn't fix things, from then on every single `PeerCandidatesRequest` results in a warning being printed.

I [added some loging](https://github.com/lithp/trinity/commit/b78c32872c7a83010fec849b90e5caf1777b1997) to the handling around those messages, here's some example output:

This pattern happens almost every time:

```
   DEBUG  01-08 16:52:56           ETHPeerPool  [0x361f] Asking discovery for more peer candidates
 WARNING  01-08 16:52:56           ETHPeerPool  [0x361f] Discovery did not answer PeerCandidateRequest in time
   DEBUG  01-08 16:52:56     DiscoveryProtocol  got expected pong from <Node(0x41a8@144.202.116.192)> (token == 0x1d16852c942da38ed80694efc6304ea2cf5e51a16e73e4d2cd8cd1d70096ddd1)
   DEBUG  01-08 16:52:56      DiscoveryService  [0x361f] Servicing request for more peer candidates
   DEBUG  01-08 16:52:56      DiscoveryService  [0x361f] Broadcasting peer candidates (('enode://0x2560fba82ada7981d7c98fdc5257d015b25465dde2a235ed3115e08b36400535ced8013a6b9a0a3aa18d3a30658a7902324796427218b34862686119f7fcdc27@5.1
89.232.162:30306', 'enode://0x8c6ddfa2265d2eb7a817a8b85fefe0e0014dfd72208e37b99a239fc2c5b0bf36498131a27080993d6fa12
```

This also happened once:

```
   DEBUG  01-08 16:52:32           ETHPeerPool  [0x2710] Asking discovery for more peer candidates
   DEBUG  01-08 16:52:33      DiscoveryService  [0x2710] Servicing request for more peer candidates
   DEBUG  01-08 16:52:33      DiscoveryService  [0x2710] Broadcasting peer candidates (('enode://0x9cc4d7a90a94ec974ceaa4cf2a8ca7a709dc8ff9e54fbb777c7b80866c18f9687c7bf73594f8fa485e2bf783a5cd12fb94ce055e03bdf7de86091662969ee606@47.
254.149.205:30303', [snip]
   DEBUG  01-08 16:52:33      DiscoveryService  Node discovery lookup already in progress, not running another
 WARNING  01-08 16:52:33           ETHPeerPool  [0x2710] Discovery did not answer PeerCandidateRequest in time
```

The second example looks exactly like overload, the message just isn't delivered in time. The first example might be overload, but if that were true it's very strange that this would keep happening once I remove the overload.

Some things which could be happening?
- Some kind of race condition happens which gets lahja into a bad state where messages now take slightly longer to be delivered than the timeout.
- Some kind of queue gets very full, which prevents messages from being quickly serviced, and this queue takes a long time to drain even when the overload disappears..
-Something happens which gets lahja / DiscoveryService into a bad state and prevents it from sending messages; it can only receive them.

I have a trinity process in this state right now. It's using about 1% of the CPU, it's just spinning in a loop trying to talk to `DiscoveryService`.

**Comment by pipermerriam** [comment]
> Some kind of queue gets very full

This is the first place I'd look.  We could add some `debug2` level logs for queue sizes in our various services that use them.

Also...

https://github.com/ethereum/trinity/blob/bf05b916526a21fefd9a6dcc7f52b49543d4bb1a/trinity/protocol/common/servers.py#L55-L58

This section of code has the potential to be problematic.  It'd be interesting to track/plot the number of tasks that the event loop is running on a periodic basis to see if it balloons at any point.

https://docs.python.org/3/library/asyncio-task.html#asyncio.all_tasks

**Comment by cburgdorf** [comment]
@lithp really great debugging attempt capping the cpu usage!

>Some kind of race condition happens which gets lahja into a bad state where messages now take slightly longer to be delivered than the timeout.

It's a straw man but just make sure to update the dependencies to test against lahja `0.10.1` which is now on latest master. It fixes a bug that *could* lead to a broken lahja connection (but I guess you would have seen an exception in that case).

Also, one thing to note is that in lahja, all async queues do not have a max length. I'm not sure if that could become a potential problem. However, in my long running tests I have stress tested the event bus with thousands of events per second and couldn't find an issue in isolation.

**Comment by cburgdorf** [comment]
I haven't seen this happening anymore. Several improvements happened to both sync and lahja. Closing for now.
