### ISSUE TITLE
Trinity can't connect to Parity peers?

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#1007]
This came up in discord.

**Comment by pipermerriam** [comment]
Has anyone confirmed this is still a problem since #1006 was merged?

**Comment by lithp** [comment]
Parity took a while to build but I just tested it on master (both Trinity's and Parity's) and Trinity successfully connected to a local parity node (I used `--preferred-peer`). Jason also looked through his logs and found that he recently connected to a Parity node, so discovery also seems to be working.
