### ISSUE TITLE
Improve the release (notes) process

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#101]
Right now, generating the release notes is pretty manual and painful, especially with all the different merge styles we're using (merge commit, squash merge, rebase merge).

Come up with a better system, which may involve some or all of:
- changing our standards for merging PRs
- changing how we writing commits
- changing how we title PRs
- hacking up some scripts to hit github and generate (a draft of) release notes based on the merged PRs since the last release

**Comment by pipermerriam** [comment]
The gitlab approach strikes me as something we could adopt.  I originally had some resistance when @cburgdorf originally proposed something similar, however, it required that git commits to be *structured* with this data.  This approach by gitlab separates the entries into independent YAML documents which makes it much easier for new contributors to create them *correctly* and to include one in their pull request.  Alternatively, it will be pretty easy for us to generate them for any pull request which doesn't have one for some reason.

**Comment by cburgdorf** [comment]
>however, it required that git commits to be `structured` with this data.

The structure is very simple though.

However, there's another thing that I like about the gitlab approach. Decoupling release notes entries from commits yield more flexibility on the implementation side. E.g. sometimes it may make sense to split a feature over 5 commits but from the perspective of the release notes it should really just be one entry with an elaborated description of the feature. So, that's nice.

**Comment by pipermerriam** [comment]
I'm :+1: 

Documenting this clearly in the developer documentation and anywhere else that makes senses will help (`CONTRIBUTING.md` , Pull Request Template)

**Comment by cburgdorf** [comment]
Guess we can close this now that we use towncrier.
