### ISSUE TITLE
Trio service task exception handling

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#1032]
### What is wrong?

When a coroutine run inside a trio service with `run_task` raise an exception, the manager will catch and swallow it. Neither the service itself or anyone else will know that the task has failed. For daemon tasks, the service will be cancelled, but the reason for this is still hidden.

For both normal and daemon tasks, I think this is surprising. As an example, see [this snippet](https://github.com/ethereum/trinity/blob/6963342e2baaaad82c13b6457acbd1f8a3a12a57/p2p/discv5/packer.py#L612-L627) which looks quite natural, but is broken (because it's not the service that raises the `HandshakeFailure`, but one of its subtasks).

### How can it be fixed

I'm not sure. At first I thought we can just reraise the exception in the manager. This might work for the example above, but it still doesn't allow the service to handle the exception.

I haven't thought this through, but maybe we can create something similar to a cancel scope for the service's subtasks that can be used to `await` the exceptions raised in tasks. But this seems quite complicated and confusing.

The easiest and currently my favorite solution is to get rid of `run_task` completely and instead create task nurseries manually. This also removes one layer of abstraction, so the service design would become a bit simpler. The only thing we lose seems to be a bit of logging.

**Comment by pipermerriam** [comment]
I think https://github.com/ethereum/trinity/pull/1040 will fix this for you?

**Comment by jannikluhn** [comment]
Yes, #1040 should fix this.

I'm still not convinced that having a hidden task nursery with a special API instead of just directly using the tools trio gives us is a good idea, though. For the most part, because there's no real benefit and, at least with the current API, it's impossible for the service to handle exceptions in subtasks, which is probably not a good idea. Also, we'll still need additional nurseries inside of services (e.g. for deeper nesting or for simply awaiting the result of two coroutines), so we end up with two ways of doing stuff in parallel which is unnecessary.

**Comment by pipermerriam** [comment]
>  it's impossible for the service to handle exceptions in subtasks

Rather than try and expose some sort of exception handling API for background processes, I think it makes a lot more sense to just write tasks such that they handle exceptions.  Maybe this needs to be written down in a sort of *service tasks guidelines* that makes it clear that tasks must be responsible for their own exception handling.

I think the task API has value.  It provides the following which would require additional boilerplate to do with the raw trio API.

1. run something in the background and fail immediately if it fails (nurseries do not raise task exceptions until they exit)
2. run something forever and fail if it exits, aka daemon tasks (this would require additional boilerplate to do with the nursery API)

thoughts?

Maybe for what you are doing you should try using the nursery API instead and see if it's better?

**Comment by jannikluhn** [comment]
> (nurseries do not raise task exceptions until they exit)

I guess technically this is true, but everything will just be cancelled, so I don't think there's a difference in practice:

```Py
import trio

async def main():
    async with trio.open_nursery() as nursery:
        nursery.start_soon(fail_after, 1)
        nursery.start_soon(trio.sleep, 100)
        await trio.sleep(100)

async def fail_after(s):
    await trio.sleep(s)
    print("raising")
    raise Exception()

trio.run(main)  # runs for 1 second
```

> run something forever and fail if it exits, aka daemon tasks (this would require additional boilerplate to do with the nursery API)

Agree, daemon tasks I like too.

> Maybe for what you are doing you should try using the nursery API instead and see if it's better?

I did that in #1033 to work around the exception bug. What's a bit cumbersome with this approach is that one has to pass a nursery object around all the time. I guess we could make the task nursery public, but for now I'm OK to stick with the `run_task` API wherever it works. I'll probably get used to it :)

**Comment by pipermerriam** [comment]
Nice, I didn't realize that nurseries auto-cancelled when a background task blows up.
