### ISSUE TITLE
Extract logic to new Connection API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1041]
### What is wrong?

https://github.com/ethereum/trinity/blob/ce1f5ae3bfc28a45dc872c8e6f5fa068ee75094d/trinity/protocol/common/handlers.py#L48-L67

This logic from the `BaseExchangeHandler` probably belongs in the `Connection` or `Multiplexer` object.

### How can it be fixed

I'm inclined to put it on the `Connection` as `get_protocol_for_command_type`

This API should be able to be reasonably easily tested against the various code paths.

**Comment by Patil2099** [comment]
@pipermerriam Can I work on this?

**Comment by pipermerriam** [comment]
@Patil2099 :+1: all yours
