### ISSUE TITLE
Trio Child-Services

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#1048]
### What is wrong?

There are cases in which a service delegates work to other services. One example is the [routing table manager](https://github.com/ethereum/trinity/blob/67f99026110e70c2cd7567f7a3881bdc81f1eca1/p2p/discv5/routing_table_manager.py) which launches several services for message handling and other tasks. It would be nice to have an API specifically for this pattern.

### How can it be fixed

There are two obvious ways, there are likely more.

1) Add a method `run_child_service` which is similar to `run_task`, but takes a service instance. This is the more flexible approach.
2) Add a class `ParentService` that takes a bunch of child service in its `__init__` method, stores them somewhere and runs them in its `run` method. This is the more rigid approach.

Some questions to be answered are:

- should parent services be able to do stuff on their own or should they just manage their children?
- if they should just manage their children, should it at least be possible to have some sort of setup and cleanup routines, maybe even one of each for each child service?
- are services required to run for the full lifecycle of a service or are they allowed to be started late and exit/fail early?
- should parent's be able to handle errors in their children and, if so, how?

I guess it all boils down to: Are parents mere containers of children or are do they have a life of their own?

**Comment by pipermerriam** [comment]
I lean towards using `run_child_service` (and probably `run_daemon_child_service`).

I'm not seeing the value of `ParentService` presently because parent services almost definitely want to do logic of their own.  For example, beam sync might run the block previewers as child services.

**Comment by gsalgado** [comment]
Has this been fixed, then?
