### ISSUE TITLE
Refusing to start if `logs/` sub-folder is missing

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#105]
### What is wrong?

I start up trinity in fresh directories a lot. I find it mildly annoying/surprising that I have to `mkdir -p /tmp/trindat/logs` instead of `mkdir /tmp/trindat`, when using `trinity --data-dir /tmp/trindat`. It feels like I need to know too much about the internal structure of the data directory.

_Picked up from https://github.com/ethereum/py-evm/pull/1654#discussion_r_

### How can it be fixed

I think we could do away with this check altogether...

But if other people think this is a preferred safety restriction, maybe we can add at least one special case: we allow you to launch trinity without a `logs/` folder, only if the data directory is completely empty.

**Comment by cburgdorf** [comment]
I'm 100 % on board. If the user tells us some directory to be used for the data, we should be free to create any subdirectories there.

**Comment by pipermerriam** [comment]
I think it's acceptable to lazily create the `logs` directory.
