### ISSUE TITLE
Cache-friendlier Beam Sync Backfill

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1076]
> I'm wondering if we can tweak this in some way to give it the same swarming behavior that exists with the way warm trie nodes are retrieved. It'd be nice if all of the nodes could somehow converge so that two nodes that start syncing a few hours apart end up _mostly_ requesting the same data.

That's a really cool idea.

> Maybe instead of doing a sequential walk of the trie we could track the ranges that have been walked and when we pivot, we randomly choose the next range using something like the block hash at the pivot point. Then clients who at least are syncing against the same block would likely end up requesting the same data.

Yup, I like this approach. The state root is something that the backfill needs access to anyway, so I like potentially using that as a pseudo-random source. Of course, some peers will get lucky and race ahead, but at least at the beginning of the pivot, all peers are requesting roughly the same nodes.

> I think the behavior improves if we can improve the likelihood of clients pivoting to the same block. My first thought is that we choose pivot points probabalistically with some sort of weighted choice which favors blocks which are evenly divisible by some fixed-ish value.

Yeah, definitely. I *think* we can even get simpler and just pivot on block `block.number % 75 == 0`. Since the predictability of data being requested (or not requested) can only be used to attack peers who are mid-sync, and probably requires spending significant assets, I don't think it's a critical attack vector.

_Originally posted by @carver in https://github.com/ethereum/trinity/pull/958_

**Comment by carver** [comment]
Interestingly, my experience with nodes so far is that I end up with one okay node and the rest are all terrible. I can't think of a reason it would naturally tend to be that way, but it's been surprisingly consistent. So backfill will be happening *very* slowly.

It's worth noting that the current backfiller, from #958 is actually (currently) just a surveyor of peer performance, and will require some significant work to upgrade to a proper backfiller. It's possible that the two functions should become totally separate. The problem is that there would be contention for which peers to use when, so they are inherently coupled.

**Comment by pipermerriam** [comment]
> The problem is that there would be contention for which peers to use when, so they are inherently coupled.

I think we can ease into the backfilling+performance thing.  It *might* be totally ok if backfilling initially takes a long time (like more than 7-10 days?).  As long as the UX is on par with a synced client we can tolerate the background process taking a while.

I'm less inclined to *optimize* what is effectively *fast-sync* than I am to look at novel ways we can fill the cold data (firehose, swarm, ???).

**Comment by carver** [comment]
Closed by #1844 and #1769
