### ISSUE TITLE
Beam Sync: Reduce sensitivity to Queen Peer latency

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1101]
### What is wrong?

Occasionally, we get stuck in a situation where 2 or more peers have similar performance, and/or highly fluctuating performance. We switch the "queen peer" (best performing) back and forth, which can sometimes cause delays. This seems to cause more of a slowdown than expected (and I *don't* see a lot of "Want to download urgent data, but..." messages).

In general, it's a problem that Beam Sync is so sensitive to quickly and accurately identifying the best peer.

### How can it be fixed

We can reduce fluttering by forcing the new queen to beat the old queen by at least 5% or something.

Worth looking further into why this causes such a performance hit. (Or it might have been a coincidence, that I got a huge block when this fluttering happened)

**Comment by carver** [comment]
Another approach that is growing on me is to completely drop the current pseudo-backfiller service concept (which is really built to identify how good the peers are).

Instead, you broadcast a request for the hash of the same trie node to multiple peers, and just save the first data that comes back. You can increase the number of peers as you lag behind, so you don't unnecessarily flood the network. For example, you might only ask one peer if you are right near the tip of the chain, but if you are 5 minutes behind, you might ask 10. (not sure what the right parameters are there)

We can also spread out which characteristics we are looking for. Like if you ask 3 peers, you could ask for:
- the peer with the best items per second
- the peer with the best round-trip time
- one random peer

This comes with the benefit of establishing speed statistics using the actual nodes that are used by beam sync. This is especially important when the peer is _itself_ beam syncing, and it might not return any backfill nodes. Then it would have terrible items-per-second speed stats when hit with a bunch of backfill requests, even if it was capable of returning beam data quickly.

---

In the current system, temporary fluctuations in speed estimates can cause you to over-ask a bad peer for data, or stop asking a good peer for data. Asking multiple peers can be a big benefit, by mitigating the cost of having the "best" peer wrong for a little while. Maybe what you think is your 2nd best peer is really your best chance, but your stats are a little off. This can be devastating to lag time.

**Comment by pipermerriam** [comment]
Redundant requests across multiple peers seems reasonably fine since we expect this data to be coming from a warm cache.

**Comment by carver** [comment]
I almost wrote up this same issue again. X) "Panic mode" (sending the request to multiple peers) is probably better than trying to optimize the way we choose the queen (for example by switching from throughput to RTT).
