### ISSUE TITLE
Make sure skeleton syncing works with long-running forks

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1102]
Also, we need to deal with this case: our skeleton peer feeding us a fork that is valid but not present on other peers. It may or may not have higher total difficulty. What do we do?

Some options, probably combined:
1. Make sure we don't fill in all the meat on the bones with the skeleton peer (would have prevented the specific issue below, but not if we connect to two peers that are both on the minority fork)
2. Periodically request the same header number from **all** peers to detect a fork. Note *periodically* here is going to have to mean "more often than our reorg maximum". So the reorg maximum would need to become much larger than 24 (see p2p/constants.py). If a fork is detected, pause sync until at least 2/3ds of connected peers agree on a fork, then choose a new skeleton peer from among the peers on the majority fork. (or, more likely, we would have a separate reorg maximum, during skeleton sync)

Note that 2 is messing with a fork choice rule (maybe the smaller number of peers actually has the chain with the higher total difficulty), which should be done with caution. But there are already a lot of little weird variations on fork choice, like not reorganizing past a certain depth.

For background, [quoting myself from chat](https://gitter.im/ethereum/py-evm?at=5bad16f8fe37781110088ad8):
> that's fun, I ran overnight and ended up on some fork. So far, the fork runs from 2933475...3018630 (and counting), from peer 0x94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09... which is one of our bootstrap peers, actually!
No other peers recognize the blocks, they don't show up on ropsten.etherscan, but 0x94c1 just keeps feeding me all the headers, block bodies, and receipts.
I'll never end up back on the correct chain, because any other peer I try to sync headers with gives `Unable to find common ancestor betwen our chain and ETHPeer`
I suppose this wouldn't happen with the skeleton header sync #1324 -- but a naive implementation of that would just get stuck (although that's better than being misled down a fork)

_Originally posted by @carver in https://github.com/ethereum/trinity/issues/59#issuecomment-425192348_

**Comment by pipermerriam** [comment]
> Note that 2 is messing with a fork choice rule 

Idea: A mechanism to normalize each chain's difficulty based on something like the percentage of your peers that are on the fork.  The mechanism should make it so that a majority on a stale chain will always be abandoned for a minority on a *verified* longer chain.

If we are clever enough, we can design our header sync so that it can be *forked* into two concurrent chains, one of which will be dropped once we have full history to objectively apply the fork choice rule.
