### ISSUE TITLE
BeamDownloader stuck with uncollectable node hash?

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1123]
### What is wrong?

I've got beam sync running and it's is exibiting strange behavior.

I am consistently getting this error message:

```bash
   ERROR  09-12 10:34:27        BeamDownloader  Never collected node data for hashes {b'\xc0N\x15\xe4\xd5\xc3\xf6\xcf\x9bT\xd8P\xdc1\x8c\x1d\x81\xc1\x17E\x16\xa7>{\xb9\x13\xe8\xf6\xeb\xb21\xc8'}
```

However, beam sync is continuing to import blocks successfully...

### How can it be fixed

I don't know but here are the DEBUG logs surrounding the first occurance of the error log message:  https://gist.github.com/pipermerriam/68862c52adb7e31a5ecf1c09ca56999b

My guess is that maybe the node is from an abandoned fork?

**Comment by pipermerriam** [comment]
More DEBUG logs from this happening: https://gist.githubusercontent.com/pipermerriam/e38d1613c00623673b9c5f8314817cce/raw/c57e1449c5c5be64bd5db1043498e5ba405d0861/never-collected-node-data.log

**Comment by cburgdorf** [comment]
I'm seeing the same error over and over

[trinity_dappnode_never_collected.zip](https://github.com/ethereum/trinity/files/3615219/trinity_dappnode_never_collected.zip)
