### ISSUE TITLE
Spammed with "discarding Transactions" after an hour

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1124]
* Trinity version: alpha 28

### What is wrong?

Sooo many of these, after running for about an hour:
```
 WARNING  09-12 17:11:05  ETHPeerPoolEventServer  ETHPeerPoolEventServer msg queue is full; discarding Transactions (cmd_id=18) msg from ETHPeer <Session <Node(0x619a@167.86.74.33)> 4b6a2d68-2bef-4175-a77c-9ebacc2b9283>
```

Launched with:
```sh
trinity --disable-upnp --disable-rpc --beam-from-checkpoint="eth://block/byhash/0xcfb11cc7d75eb1e738fc5bd806123f40dd73e0af6ba69c616ab8d5de7f88215c?score=11,883,412,487,502,744,316,860" --data-dir /tmp/smoke-main/ --enable-experimental-eth1-peer-tracking
```

I haven't noticed this in previous runs, but I couldn't trace it to any crash in stderr.

### How can it be fixed

:man_shrugging: Some leading questions:

- Is there a thing that was supposed to be consuming transactions but crashed?
- Are we putting Transactions on the message queue even though we know nothing is consuming them?
- How close is the transaction pool plugin to being stable enough to turn on by default? (and would that even help)

**Comment by pipermerriam** [comment]
I think that this just happens when we get flooded by a ton of transactions which happens legitimately under normal network circumstances.

I think we can mitigate two ways.

1. larger queue to handle times when a huge burst of transactions arrives.
2. Ensure that we are properly disconnecting from peers that send us the same transactions over the same session.
3. Special case this message to display aggregates rather than individual messages.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/trinity/blob/0b6c5e01c8185795eb631c433bbb468989262ccf/trinity/protocol/common/peer_pool_event_bus.py#L65

I bumped this queue size up to 8000 and it *may* have solved this, providing a bigger buffer to allow the transaction messages time to be consumed when there's a big burst of them.

**Comment by pipermerriam** [comment]
Probably good to try and understand what the memory requirements are going to be for this type of thing.  However, the peer subscriber API is going away (replaced by the connection command and protocol handler APIs) so making that change would mostly just be a convenience fix to cleanup the log output.

**Comment by pipermerriam** [comment]
Alright,~2 hours in and this started happening again.  My intuition is that the main even loop is getting bogged down.
