### ISSUE TITLE
InfluxDB + Grafana

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1137]
### What is wrong?

We need better insights into running clients.  Currently we get this via DEBUG logs but I'm finding this insufficient to provide the aggregate data I want.  Specifically, I want to be able to easily make graphs of certain things like the block import time or the number of trie nodes at each block that we have to fetch from the network...

### How can it be fixed

New "Component" (aka Plugin) that listens for events and pipes the event data into InfluxDB.

Then we update things like the peer pool and the beam syncer that periodically dump information into DEBUG logs to also emit an event over the event bus with the data.  Here's my initial thought on the data I want to record.

- All of the request/response metrics.
- All of the beam sync metrics.
- Each time we serve a peer request.

**Comment by ralexstokes** [comment]
just to start building this bikeshed, there is a weak consensus w/ eth2.0 efforts (here and in other clients) to use prometheus in lieu of influxdb -- i have no real data to contribute either way but wonder if there is a preference on your end

if we can accomplish the same tasks w/ one stack across trinity eth1 and eth2, that would be great :)

**Comment by pipermerriam** [comment]
I have no preference as long as whatever is used is able to interface with something like Graphana for flexible easy to create graphs.

**Comment by pipermerriam** [comment]
Pondering over the case for prioritizing this. Here's a set of graphs that would tell us a lot about a running trinity node that we currently can't divine without very close log inspection.

1. stacked line graph showing the p2p commands we're sending to/from our peers.
2. line graph of EMA values
3. import time for beam blocks
4. preview time for beam blocks
5. stacked line graph showing percentage of trie nodes in a block that were available and percentage that needed to be fetched on demand.
6. stacked line graph of cold storage vs hot storage
7. utilization of block preview workers.

We could also detect failures that might not currently be visible lie having a preview worker silently crash/freeze/something.

**Comment by cburgdorf** [comment]
I'm closing this (we have InfluxDB/Grafana monitoring by now) but created #1745 to move over the useful bits.
