### ISSUE TITLE
Per-module logging doesn't work (or is confusing)

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#114]
* `trinity` Version: `git master`, commit 2e8f681818c6befb3ecef0247f9380fba7122156
* OS: Arch Linux
* Python Version (python --version): 3.7.2
* Environment (output of `pip freeze`): MISSING

### What is wrong?

When running either of:

```
trinity --log-level trinity.protocol.eth.ETHPeerPool=DEBUG
trinity --log-level trinity.protocol.eth=DEBUG
trinity --log-level trinity.protocol=DEBUG
trinity --log-level trinity=DEBUG
```

I'd expect `DEBUG`-level logging from `trinity.protocol.eth.ETHPeerPool` to be printed to `stdout`. This does not happen. All messages are at default level (`INFO`).

### How can it be fixed

Not sure.

This feature was added in ~~non-PR commit 0e760630480a2aa16acf2818f97035c926a34cb2~~ PR https://github.com/ethereum/py-evm/pull/1158; there are rudimentary tests for proper argument parsing - but not whether the output contains proper lines.

If new tests for this are added, it's perhaps better to use something less likely to change than `trinity.protocol.eth.ETHPeerPool`.

**Comment by veox** [comment]
In PR #113. I've noticed that without

https://github.com/ethereum/trinity/pull/113/commits/ef5152151be00f865c28f44bfad7a9129d06c995#diff-f35257159996b4bb2bd8615d12c4335eR420

the `logger.debug2()` message produces an error/traceback in `stdout` (because of the line being mis-formatted). However, with the fix, and running as follows:

```
trinity --log-level trinity.sync=DEBUG2
```

... the `DEBUG2`-level lines are still suppressed.

**Comment by carver** [comment]
So I won't get a chance to look into it right now, but IIRC the log levels change which things are written to the debug log. (Totally agree these command line args could use a lot of love, BTW)

So it's likely been used more for adding `debug2` messages into the log, or quieting noisy `debug` messages in the logs.

**Comment by veox** [comment]
Did PR #400 address this?

**Comment by cburgdorf** [comment]
@veox it does and it also added a test to ensure it keeps working!

**Comment by cburgdorf** [comment]
@veox related https://github.com/ethereum/trinity/pull/659 :)
