### ISSUE TITLE
Handle the error from `dial_peer`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#1151]
### What is wrong?

1. Currently, if the dial_peer throws exceptions, the `Node` would die. 
https://github.com/ethereum/trinity/blob/9e9ed906e7e09545acac97795854dc0b4acdcd4a/trinity/protocol/bcc_libp2p/node.py#L328-L333

2. For `connect_preferred_nodes`, it should retry.

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by hwwhww** [comment]
Just noticed that it has been handled in `interop` branch! (`dial_peer_with_retries`)

**Comment by ralexstokes** [comment]
yeah -- we saw this during `interop` if we e.g. ran two trinity nodes essentially at once -- they would race to open a transport and then die if one or the other wasn't ready in time.

i do want to check how `go-libp2p` handles this to get a sense if this is a library concern or an application concern (the approach taken on the `interop` branch)

**Comment by NIC619** [comment]
*me* working on catching these low level connection errors in py-libp2p and raise `SwarmException` from there

**Comment by ChihChengLiang** [comment]
I think this is resolved. Feel free to reopen if it isn't.
