### ISSUE TITLE
Single-step Trinity Installation

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#1158]
I couldn't find an existing issue on the topic of packaging so I'm opening this one. During the ETH2 interop retreat a couple people had a hard time installing Trinity, though most people were eventually able to. Opening a ticket to start a discussion about what we can do to make installing Trinity a seamless process.

I think there are two sticking points:
- Trinity relies on a modern version of python, version 3.6, which is not the default for I think any distribution. For people unfamiliar with python installing 3.6 and then virtualenv are unfortunate barriers.
- Trinity depends on some packages which depend on the system leveldb and snappy libraries.
  - The Arch snappy package appears to be broken (or at least it was last week) so we were unable to get Trinity running on the machine of someone at the interop retreat who was using arch.
  - The brew packages (or the python packages) for leveldb and snappy are entirely broken on OSX. Installing them requires stackoverflow and cargo-culting some command line flags.

There are a couple things we could do to make installing Trinity easier (which will be useful both for end-users and also for other eth2 teams who are trying to make their clients work well with Trinity)

- We could look into the `python-snappy` and `plyvel` packages and try to upstream changes which make installing them on OSX easier.
- We could push our own versions of `python-snappy` and `plyvel` which build their own snappy and leveldb packages so that we're no longer relying on the system libraries.
- We could make our own trinity homebrew package which includes snappy and leveldb libraries, so we're no longer relying on the system libraries
- We could create a [snap](https://snapcraft.io/) package so that people can install trinity with a single command.
- We could build an executable by [freezing](https://docs.python-guide.org/shipping/freezing/#freezing-your-code-ref) trinity and distribute that built executable.
- Release as a combined AppImage
- Host a repository to be used with debian-like installs via apt

**Comment by ralexstokes** [comment]
i'm hoping `pyoxidizer` solves all of our problems here...

https://github.com/ethereum/trinity/issues/753

**Comment by carver** [comment]
Some more options to consider for *nix-y distros:
- Flatpak
- AppImage

[Comparison of snap to flatpack to appimage](https://askubuntu.com/a/1009061/725986).

**Comment by lithp** [comment]
AppImage actually looks super cool, I don't think it requires users installing anything, it should let us distribute a `./trinity` binary which just runs! #1160 experiments with getting `snap` to work, you can now download and run trinity in about 20 seconds if you already have snap installed. I think I'll play with building an AppImage next.

**Comment by jannikluhn** [comment]
Another option would be a docker image. The main advantage would be full control over the system environment, but it does require people to set up docker first.

**Comment by ralexstokes** [comment]
yeah we will provide a docker image -- there is some preference to not have to pull in the (sizeable) dependency that is docker though, so a "native" solution is nice.

**Comment by mhchia** [comment]
Does it seem that we still need to install the runtimes for `AppImage` and `snap` to run? However, I think they are better solutions than we build `rpm` and `dpkg` packages on our own. Writing the scripts for them are not pretty trivial.

**Comment by cburgdorf** [comment]
>Another option would be a docker image

`docker run -it ethereum/trinity` does work already.

We also provide a DappNode package now (which is also based on Docker)

**Comment by carver** [comment]
> Does it seem that we still need to install the runtimes for `AppImage` and `snap` to run?

I believe `AppImage` doesn't require any special runtime or package manager. It's a single file to download and execute.

**Comment by lithp** [comment]
Dropping a note here for future explorers. Today I tried to get Trinity working inside [pyoxidizer](https://github.com/indygreg/PyOxidizer) but I don't think it's ready to handle an application as complicated as Trinity. The issue I'm currently stuck on is [getting uvloop to work](https://github.com/indygreg/PyOxidizer/issues/133), pyoxidizer isn't correctly linking against libuv.

Before that, I had some trouble with pkg_resources, a pyoxizider application which does nothing but import pkg_resources fails with:

```
Traceback (most recent call last):
  File "linecache", line 95, in updatecache
FileNotFoundError: [Errno 2] No such file or directory: 'pkg_resources._vendor.pyparsing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "example", line 1, in <module>
  File "pkg_resources", line 84, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "pkg_resources.extern", line 43, in load_module
  File "pkg_resources._vendor.packaging.requirements", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "pkg_resources.extern", line 43, in load_module
  File "pkg_resources._vendor.pyparsing", line 4756, in <module>
  File "pkg_resources._vendor.pyparsing", line 1284, in setParseAction
  File "pkg_resources._vendor.pyparsing", line 1066, in _trim_arity
  File "pkg_resources._vendor.pyparsing", line 1050, in extract_stack
  File "traceback", line 211, in extract_stack
  File "traceback", line 363, in extract
  File "traceback", line 285, in line
  File "linecache", line 16, in getline
  File "linecache", line 47, in getlines
  File "linecache", line 103, in updatecache
  File "<frozen importlib._bootstrap_external>", line 566, in decode_source
AttributeError: 'memoryview' object has no attribute 'decode'
error: cargo run failed
```

It fails [inside here](https://github.com/python/cpython/blob/3.7/Lib/linecache.py#L82) and given what I know about pyoxidizer (very little) I think this is a genuine compatibility problem, pyoxidizer makes an incompatible change to the python runtime.

I attempted to work around this by not importing pkg_resources from any of our projects (`trinity`, `py-evm`, `web3`, `eth_keyfile`, `eth_utils`, `py-trie`, and `eth_abi`). I did this by installing trinity into a virtual environment, manually changing the relevant files, and then importing it all into pyoxidizer with a `virtualenv` packaging_rule. This mostly worked, but failed to include any of the native libraries. In order to get those to work I had to explicitly add some `pip-install-simple` `packaging_rule`s for `pyethhash==0.1.27`, `lru_dict==1.1.6`, and `uvloop==0.11.2`.

PyOxidizer does seem cool though. It's trying to solve a wicked hard problem and I'm impressed that it does as well as it does, I'm down to try again in a few months!

**Comment by lithp** [comment]
I've finally for an AppImage building, one for `trinity` and one for `trinity-beacon`. This doesn't help with OSX, but it *should* mean that anyone running a modern linux can just download a binary and run it. No runtime required! https://github.com/ethereum/trinity/pull/1205

**Comment by pipermerriam** [comment]
Just stumbled across this as a potential option as well:

- https://nixos.org/nix/
- https://nixos.org/nixpkgs/manual/#python
