### ISSUE TITLE
Errors and warnings when running full `pytest` (not with `tox`)

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#1190]
* Trinity version: v0.1.0-alpha.28-78-gfb2d2aa8 (current latest `master`, commit fb2d2aa8)
* OS: Arch Linux
* Python version (output of `python --version`): Python 3.7.4
* Environment (output of `pip freeze`): MISSING

### What is wrong?

I'm trying to run the full test suite, with a laconic `pytest tests` invocation, without the extra `tox` stuff. Here are three maybe-issues.

-----

I see the tests listed in `INCORRECT_UPSTREAM_TESTS` failing the `xfail`, and I vaguely remember there were changes in these during summer. It's possible that `trinity` is now on the same page as upstream, or maybe there's some other discrepancy. I'll get back to these later.

EDIT: This is for [`git` submodule `fixtures` commit `6b85703b568f4456582a00665d8a3e5c3b20b484`](https://github.com/ethereum/tests/tree/6b85703b568f4456582a00665d8a3e5c3b20b484), which is _after_ [latest tag `v6.0.0-beta.3`](https://github.com/ethereum/tests/tree/v6.0.0-beta.3). IIRC, that's so because of the whole Constantinople/Petersburg debacle; `ethereum/tests` never seemed to tag a specific commit for Petersburg.

EDIT2: ... but the commit is still from January 21, much earlier than summer, so that should be ruled out.

-----

A more immediate issue, however, is a name collision of two files, `test_sync.py` (fix demo in [this commit](https://github.com/veox/trinity/commit/4b715a4297c40fd1873f77294bde5bceb27088f9): just rename it). `tox` runs don't catch these.

@ChihChengLiang is it OK to rename this?..

Strangely, there are other name clashes, but these don't produce issues:

```
      2 test_genesis.py
      2 test_receive_server.py
      2 test_requests.py
      2 test_utils.py
      2 test_validator.py
      3 test_handshake.py
```

-----

Finally, and most importantly, all RPC tests against fixtures print a warning, of this form:

``` python
tests/json-fixtures-over-rpc/test_rpc_fixtures.py::test_rpc_against_fixtures[/home/veox/src/trinity/fixtures/BlockchainTests/GeneralStateTests/stCreate2/call_outsize_then_create2_successful_then_returndatasize_d0g0v0.json:call_outsize_then_create2_successful_then_returndatasize_d0g0v0_ConstantinopleFix:ConstantinopleFix]
  /home/veox/src/trinity/.virtualenv/trinity/lib/python3.7/site-packages/_pytest/python.py:195: RuntimeWarning: coroutine 'test_rpc_against_fixtures' was never awaited
    testfunction(**testargs)
```

... and this I don't know how to solve. :/

### How can it be fixed

:cactus:

**Comment by pipermerriam** [comment]
The *never awaited* thing sounds like `pytest-asyncio` may be missing and thus the test isn't being run via the event loop.

**Comment by ChihChengLiang** [comment]
@veox Feel free to rename those if they block you.

**Comment by veox** [comment]
I suppose it's OK to close this issue.

The first must be addressed in `py-evm` anyway; second is not a show-stopper, can be worked around trivially, and does not affect CI; third is kind of PEBKAC.
