### ISSUE TITLE
Beam sync explainer infographic

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1194]
Anyone want to make a nice explainer infographic for beam sync?

**Comment by cburgdorf** [comment]
Jasons post has one https://medium.com/@jason.carver/intro-to-beam-sync-a0fd168be14a

**Comment by pipermerriam** [comment]
> Jasons post has one

I'm aware.  I'm looking for someone who can take that and add some designer polish

**Comment by carver** [comment]
Haha, yeah. I am happy that I was able to put something together. But I would love someone to make a graphic that looks professional.
