### ISSUE TITLE
Beam Sync Metadata Propagation

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1225]
### What is wrong?

Beam Sync (v0) can only keep up if you have at least one great connection to a peer. Most of the time is spent in the round-trip waiting for data, and which data to ask for is discovered in serial, after receiving the answer from the last request.

We need a more reliable BeamSync experience.

### How can it be fixed

Propagate metadata about which state is needed in a block, using a new devp2p subprotocol (`firehose0`?) with just one command: `WitnessMetadata`. A couple options for the ways to send metadata are considered in this sampling of mainnet witnesses: https://notes.ethereum.org/oqrAzyhhQ_Oczvw7OUqs4w

#### Format
I'm still undecided on the two possible metadata formats.

One would be:
- block hash
- block number
- the list of all hashes of trie nodes that make up the block witness

The other would be:
- block hash
- block number
- list of addresses that are read during the block (excluding transaction signers or recipients and coinbase, assume all recipients need to load their bytecode)
- an extra byte for whether the bytecode was loaded
- a list of storage slots read, by address
- an extra list of trie node hashes required for trie reorgs

The second one is more flexible for future ways of sending state, but the first one is so simple! The second one is a smaller amount of data, but the first one should still still be small enough to fit in a single request. (see the linked `notes.ethereum.org` above)

#### Directionality
Should this be broadcast (like `NewBlock`) or pulled data (like `GetBlockHeaders`)? I would argue that it depends on the probability that peers are mid-sync. If it's common for peers to be syncing, then broadcast seems ideal. There's a lot more tracking involved in guessing which peers have which witnesses available, so maybe broadcast is the simple solution, potentially at the cost of network bandwidth. We can tinker with the percent broadcast rate, but early on, I think it will be hard enough to find witness broadcasters, that we should just start at 100%. (Except if the peer has sent you the same witness, or a more recent one).

**Comment by carver** [comment]
My default direction is toward simplicity: just node hash witnesses, and broadcast-style p2p.

**Comment by pipermerriam** [comment]
I believe we need a way to signal what network we're on.  I think this would be best done with a handshake message exchanged during protocol handshakes.

Using the key/value format that `LES` uses seems appropriate because it allows for extension without having to update the base protocol  message formate.

**Comment by carver** [comment]
> Should this be broadcast (like `NewBlock`) or pulled data (like `GetBlockHeaders`)?

I think broadcast is a no-brainer for now. When a block import happens, the broadcaster can send out the metadata and then promptly forget it. Otherwise, the metadata would have to be either stored in the db (~200k per block), or re-generated on demand (importing recent mainnet blocks takes ~8s, so not really an option currently).

**Comment by carver** [comment]
> I'm still undecided on the two possible metadata formats.

Since we don't have a clean way to request state data by address and/or storage slot over p2p, let's just do node hashes for now.
