### ISSUE TITLE
Test failed for obvious reason but not reflected in CI

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#1231]
### What is wrong?

The test  `pytest tests/libp2p/test_peer_factories.py` should fail, but the [CI](https://circleci.com/gh/ethereum/trinity/131568) still shows it passing. 

### How can it be fixed

Investigating 🕵️‍♂️🐕

**Comment by ralexstokes** [comment]
@ChihChengLiang why should it fail?

**Comment by ChihChengLiang** [comment]
The test uses ConnectionPairFactory without passing `alice_chaindb`, which should raise ` AttributeError: 'NoneType' object has no attribute 'db'` 
https://github.com/ethereum/trinity/blob/24213d8f22a03c370313d3a990eea6a2fe1e76e4/trinity/tools/bcc_factories.py#L92-L101

**Comment by ralexstokes** [comment]
gotcha -- i do get this error locally... is the test being run correctly in CI? maybe something w/ the `pytest.asyncio` infrastructure?

**Comment by NIC619** [comment]
Looks like we forgot the `test-asyncio` dependency for the libp2p tests.🤣
https://github.com/ethereum/trinity/blob/20bfa8bd7caa3588e74263e5025b71cbb3628136/tox.ini#L139

**Comment by ChihChengLiang** [comment]
Ah nice catch, I can send a PR to fix this one.
