### ISSUE TITLE
Spec v0.9.0 updates - `eth2` part

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#1240]
### What is wrong?
https://github.com/ethereum/eth2.0-specs/releases/tag/v0.9.0
- features
	- alter beacon proposer selection logic (ethereum/eth2.0-specs#1413)
	- add seed domains (ethereum/eth2.0-specs#1415)
	- fix delay-based attestation inclusion reward (ethereum/eth2.0-specs#1434)
	- use eth1_block_hash for initial randao_mix (ethereum/eth2.0-specs#1447)
- simplifications
	- remove active active_index_roots and compact_committees_roots from phase 0 (ethereum/eth2.0-specs#1329)
	- remove shards/crosslinks from phase 0 (ethereum/eth2.0-specs#1428)
	- remove transfers from phase 0 (ethereum/eth2.0-specs#1443)
- Fork choice
	- verify state root in fork choice tests and other minor fixes (ethereum/eth2.0-specs#1454)

### How can it be fixed

Question: should the v0.9 progress on the new branch, so that `interop` tests can still work?
@ralexstokes

**Comment by ralexstokes** [comment]
@hwwhww awesome! sounds like you want to do some further refactoring in #1251 so reviewing this will be top of my list after you get that done :)

in the meantime, i'd suggest we just move ahead w/ merging this to `master` we can always rewind to a particular point if we need to but i'd rather have an incentive for another team to update so we can do `v0.9.0` interop experiments
