### ISSUE TITLE
Document the process of adding a new devp2p sub-protocol

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1249]
### What is wrong?

It's not clear what needs to be done, and where to start, to create a new subprotocol.

It's a *little* early to start in on this, since the peer code is changing rapidly at the moment.

I mostly wanted a place to keep track of the list of things I don't know, as I dive into this code as a novice. (first-contact is the best time to write docs, IMO)  The answers may be changing, but the questions are probably stable-ish.

### How can it be fixed

Answer questions like:
1. How do you start announcing support for a new sub-protocol? _Currently, it looks like the answer is to return new values for `get_handshakers()` in `ETHPeerFactory`_
2. What is the minimum set of files that need to be added, in the `trinity/protocol/<SUBPROTO>/` directory? Say to *just* support a handshake, and some kind of simple broadcast message. (not a request/response)
3. _in progress_

**Comment by cburgdorf** [comment]
I think that would be a great addition to our section of detailed [guides](https://trinity-client.readthedocs.io/en/latest/guides/index.html).

**Comment by pipermerriam** [comment]
Somewhat awkward but might be worth developing against https://github.com/ethereum/trinity/pull/1189 since it does make a few meaningful changes to the API.

**Comment by carver** [comment]
> Somewhat awkward but might be worth developing against #1189 since it does make a few meaningful changes to the API.

Yeah, that's a big part of the reason that I left the questions unanswered, currently. Although IIRC `get_handshakers()` didn't change meaningfully.
