### ISSUE TITLE
Remove direct `cytoolz` imports in favor of `eth_utils.toolz` 

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#126]
Loosely depends on https://github.com/ethereum/trinity/pull/125 to ensure `eth-utils` is new enough.

### What is wrong?

We have `toolz/cytoolz` compat via `eth_utils.toolz` but this library still directly uses `cytoolz`

### How can it be fixed

Update all `toolz` imports to come from `eth_utils.toolz`

```
from cytoolz import assoc
# should become
from eth_utils.toolz import assoc
```

**Comment by stringray55** [comment]
I would like to take this up.
