### ISSUE TITLE
spec v0.9.1 updates

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#1261]
### What is wrong?

https://github.com/ethereum/eth2.0-specs/releases/tag/v0.9.1

### How can it be fixed

Mainly removing custody data from phase 0.

Some fork choice updates.

Also some validator updates but I don't think we have that code yet

**Comment by hwwhww** [comment]
I'm starting `removing custody data from phase 0`.

**Comment by ralexstokes** [comment]
i'll start on the fork choice updates
