### ISSUE TITLE
Doesn't connect to preferred node when discovery is on

### ISSUE THREAD

**Issue by lithp** [ethereum/trinity#127]
* trinity Version: b78c3287

This is actually two issues bundled into one.

When trinity is run with a command like:

    trinity --preferred-node enode://long-key@whatever --disable-discovery

We get a lot of lines like this:

    WARNING  01-09 13:12:59.825           ETHPeerPool  [0x42ba] Discovery did not answer PeerCandidateRequest in time

This is understandable, Discovery is not answering at all :)

The second problem occurs when you drop the `--disable-discovery` flag and just use `--preferred-node`. As far as I can tell from looking at the logs, trinity never attempts to connect to the preferred node!

Some ideas:
- When `--disable-discovery` is passed `DiscoveryService` should not run discovery in the background but should still answer requests, using only the set of bootstrap and preferred peers.
- When `--disable-discovery` is passed `BasePeerPool` should not attempt to talk to it, and should instead use just the set of preferred peers? This feels like a much worse solution.
- I'm not sure why ETHPeerPool never ends up trying to connect to the preferred peer. Maybe when discovery is on it never gets a chance because it's too busy trying to connect to other peers. This feels like it's related to why trinity has a hard time finding peers so it's probably worth looking into.

**Comment by lithp** [comment]
#129 fixes the first problem, I still need to look into the second problem.

**Comment by veox** [comment]
> I'm not sure why ETHPeerPool never ends up trying to connect to the preferred peer. Maybe when discovery is on it never gets a chance because it's too busy trying to connect to other peers.

`trinity` now DEBUG-logs reasons why it doesn't connect to the preferred node, e.g.:

```
   DEBUG  04-14 13:02:34        SQLitePeerInfo  skipping <Node(0x053d@79.98.29.154)>, it failed because "TooManyPeersFailure" and is not usable until 2019-04-14 13:03:52
```

**Comment by carver** [comment]
Solved by https://github.com/ethereum/trinity/pull/436 ?

**Comment by carver** [comment]
AFAIK, this is fixed. I have been regularly running in this mode (discovery on, with a preferred peer).
