### ISSUE TITLE
Move compression handling from Command to Protocol

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1278]
Since the protocol knows about snappy support, instead of the command, maybe the protocol should do the decompression.

Like:
```py
unpacked_message = msg_proto.decompress(msg)  # this is just a no-op if msg_proto.snappy_support=False
cmd = command_type.decode(unpacked_message)
```

_Originally posted by @carver in https://github.com/ethereum/trinity/pull/1189_

---

Also *maybe* there's an opportunity to move the command ID handling outside of the command, too. So the protocol would be the one handling it. I seem to remember Piper saying there was a good reason we can't do this, but someday I'd like to take another crack at it.

I think this could be really helpful when managing many versions of the same subprotocol, where the same command might exist with a different `command_protocol_id`. It would be nice to do something like:

```
ETHProtocol65 = ETHProtocol.with_commands(
  Status,
  NewBlockHashes,
  ...
)

ETHProtocol66 = ETHProtocol.with_commands(
  Status,
  SomeCrazyNewCommand,
  NewBlockHashes,
  ...
)
```

Where the *only* thing different about `NewBlockHashes` between the versions is the command id, so we should be able to re-use the command definition.

**Comment by pipermerriam** [comment]
I think all of this can be done, but the snappy stuff would be the biggest win.  :+1: 

Thanks for making an issue for this.  I decided not to do it in #1189 because it was already so huge but forgot to make the issue as to not lose the task.
