### ISSUE TITLE
Trinity prints noisy error message when being port-scanned

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#13]
* py-evm Version: `trinity-v0.1.0-alpha.20-71-g8841a698` (commit 8841a6980254b93294c80a889ed3901fd6baf9c6, slightly past release)
* OS: Arch Linux
* Python Version (python --version): 3.7.1
* Environment (output of `pip freeze`): MISSING

### What is wrong?

Running `trinity` as

``` sh
% nice ionice -c3 trinity --network-id=1 --sync-mode=light --discv5 $ETHSTATS_OPTIONS
```

and then checking if the port is accessible with

``` sh
% nc -vz localhost 30303
```

results in this error message being printed:

``` python
   ERROR  12-20 17:58:10           LightServer  Unexpected error handling handshake
Traceback (most recent call last):
  File "/home/veox/src/py-evm/trinity/server.py", line 185, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/veox/src/py-evm/trinity/server.py", line 199, in _receive_handshake
    ip, socket, *_ = writer.get_extra_info("peername")
TypeError: cannot unpack non-iterable NoneType object
```

Not sure if fresh or regression.

### How can it be fixed

Not sure.

Checking how "regular" sync mode reacts to this and handles it would be a good start.

**Comment by carver** [comment]
Theoretically fixed by #104
