### ISSUE TITLE
Trinity <-> Trinity connections

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1301]
### What is wrong?

There is at least one problem with trinity peers connecting to trinity peers: DAO check issues. Trinity seems to time-out waiting for another trinity peer to send it the DAO fork headers (maybe they are deadlocked waiting on each other).

There might be other issues. I've seen some weird stuff  (after I locally disabled the dao check) like:
- being double-connected to the same trinity peer
- not being able to reconnect after disconnecting

I know the full testing framework #1302 may not be done until we hit beta, but it seems like we *have* to be able to connect to ourselves to just basically get started.

### How can it be fixed

We might fix the DAO check by:
- upgrading to eth/65 subprotocol and using fork-id instead of header check, see #1304 
- hunting down what's deadlocking in the boot manager

The other things just need some basic hunting.

**Comment by gsalgado** [comment]
I believe this is no longer an issue
