### ISSUE TITLE
Trinity <-> Trinity test infrastructure

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1302]
### What is wrong?

We need a full-featured, reliable test suite to make sure mainnet trinity connects to mainnet trinity smoothly and consistently.

### How can it be fixed

:man_shrugging: 

Maybe very similar to existing integration tests, but instead of launching one trinity, we launch two nodes and link them together. We might consider running a dedicated node to connect to, so that we don't run as much of a risk of flaky tests, when we happen to not find any good nodes quickly.

**Comment by gsalgado** [comment]
I'm having a go at this and the first issue I run into is addressed in #1608
