### ISSUE TITLE
Upgrade to eth/64 subprotocol

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1304]
### What is wrong?

We are behind right now (on eth/63). We especially want eth/64 because of [support for fork-id](https://eips.ethereum.org/EIPS/eip-2364), which would let us drop all this DAO-header-checking nonsense.

### How can it be fixed

Add a new subprotocol definition. We don't really have a great example of supporting multiple versions of a subprotocol, so this will take some architecture/design work.

**Comment by gsalgado** [comment]
Closing now that we have eth/64 support and #1593 has landed
