### ISSUE TITLE
Faster startup

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1306]
### What is wrong?

Wiring together all the components at startup is (unnecessarily) slow right now. They start up in series.

cc @pipermerriam you said you were already working on this

### How can it be fixed

Start components in parallel.

**Comment by gsalgado** [comment]
The new `ComponentManager` [seems to start all components in parallel](https://github.com/ethereum/trinity/blob/master/trinity/extensibility/component_manager.py#L93-L96), so I'm closing this
