### ISSUE TITLE
Megathread: All unclean shutdowns

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1307]
### What is wrong?

Lot's of different unclean shutdown issues

- [ ] #318
- [ ] #373
- [x] #656 
- [ ] #1188 
- [ ] #1381 
- [ ] #1557

and probably some more that are unreported.

When all those are cleared: #1603 

### How can it be fixed

shrug

- [ ] Reactivate clean shutdown test once we have fixed all issues

https://github.com/ethereum/trinity/blob/5159b19f76bf4ac8e1910faaee39b1e51d546422/tests/integration/test_trinity_cli.py#L359

**Comment by pipermerriam** [comment]
I'm going to be fixing this.

**Comment by carver** [comment]
FWIW, https://github.com/ethereum/trinity/issues/1300 is currently tagged as higher priority.

**Comment by gsalgado** [comment]
There's only #1603 left to be addressed, and that's also targeted to the beta milestone, so closing this
