### ISSUE TITLE
HTTP server for json-rpc

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1309]
### What is wrong?

We don't have an HTTP server for json-rpc.

### How can it be fixed

- upstream the dopple newline bugfix
- release dopple alongside trinity
- add an opt-in http flag at the CLI, where you can specify which json-rpc modules to make available over http

**Comment by cburgdorf** [comment]
We **do** have an HTTP server that can be enabled via `--enable-http`. That's the one that @hwwhww wrote for the beacon node but we initially aimed to replace it with a dopple based one.

But after playing a little bit with dopple I became a little skeptical:

1. The code is entirely synchronous. The async one that we currently have might be more efficient after all.

2. While playing with dopple + Trinity, I noticed unclosed socket warnings coming out of it

3. Afaik, the beacon chain uses different URL paths which dopple currently doesn't support.

I think that (at least for now) we might be better off just using the built-in HTTP server that we already have.

That said, one thing we **do** need is to filter the APIs that are exposed via HTTP. E.g. we don not want to expose the `admin` module by default.

**Comment by hwwhww** [comment]
@cburgdorf Thanks for the recap!

The main reason for implementing beacon chain built-in server was (3), we require a more customizable URL parser for the (kinda) RESTful requests.

* `--enable-http` (`handler=RPCHandler`) is the HTTP endpoint that converts the requests to RPC handler.
* #1463 added `--enable-metrics` (`handler=MetricsHandler`) for eth2 metrics endpoint and `--enable-api` (`handler=APIHandler`) for beacon chain validator APIs (different ports).
* Note that eth2 currently doesn't use `RPCHandler`, feel free to modify or move to use `dopple` if eth1 needs. :)

**Comment by cburgdorf** [comment]
I'm going to close this in favor of https://github.com/ethereum/trinity/issues/1626
