### ISSUE TITLE
Discv5 tests fail randomly

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1320]
`tests/p2p/test_token_bucket.py` and `tests/p2p/discv5/test_handshake.py` failed on CI for [py36](https://circleci.com/gh/ethereum/trinity/144559) but not for [py37](https://circleci.com/gh/ethereum/trinity/144567).

Upon re-triggering it passed on both py36 and py37, which suggests there's something causing them to fail randomly and it may not be related to the python version at all.

**Comment by cburgdorf** [comment]
See related discussion in https://github.com/ethereum/trinity/issues/967
