### ISSUE TITLE
Move `--preferred-peer` CLI flag to be controlled by the discovery plugin

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#134]
### What is wrong?

The `DiscoveryService` was recently moved to be plugin based, however, the `--preferred-peer` and `--discv5` CLI flags/arguments are not controlled by the plugin

### How can it be fixed.

Migrate both of those `CLI` flags to be controlled by the `DiscoveryPlugin`

**Comment by veox** [comment]
May be in conflict with (more recent proposal) #440, that suggests decoupling preferred peers from peer discovery.
