### ISSUE TITLE
`SerenityStateTranisition` Missing Eth2 `validate_state_root` equivalent?

### ISSUE THREAD

**Issue by gnattishness** [ethereum/trinity#1340]
# What is wrong?

The Eth2 spec for [`state_transition`](https://github.com/ethereum/eth2.0-specs/blob/v0.9.2/specs/core/0_beacon-chain.md#beacon-chain-state-transition-function) contains the following:

```python
...
if validate_state_root:                                                                                                 
    assert block.state_root == hash_tree_root(state)
```

I'm unable to find an equivalent check in trinity's implementation (though it's possible I missed it).

### How can it be fixed

- Check for a mismatched state_root and raise a ValidationError(?) if the check fails
- Optionally, expose a `validate_state_root` boolean flag as a parameter for `apply_state_transition` (this would be helpful for fuzz testing - e.g. [beacon_fuzz](https://github.com/sigp/beacon-fuzz))

**Comment by ralexstokes** [comment]
we handle this a bit differently from the spec; if you refer here:

https://github.com/ethereum/trinity/blob/master/eth2/beacon/chains/base.py#L413-L415

we first have the state machine import the block and if we want to validate it (by default, we do) then we end up checking that each field of the ssz schema matches, including the `state_root`, in our call to `validate_imported_block_unchanged`.

i think we are all open to extending the API here if it makes fuzz testing radically simpler so let me know if we can do more here or if the above is not clear. thanks!

**Comment by gnattishness** [comment]
Thanks for clearing htis up!

There should be no need to extend or adjust the existing API.

I'm currently instantiating and calling the `SerenityStateTransition` directly.
As I need to pass a `BeaconState` as input and get it as output, the higher-level `import_block()` is less suitable.
To maintain consistency across implementations, I can simply disable `validate_state_root` checking for the other implementations and call your lower-level transition. If performing validation becomes necessary, I can easily use `BeaconStateMachine.import_block` and include the `validate_imported_block_unchanged` in the harness function.
