### ISSUE TITLE
Beacon chain cache implementation

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#135]
Hello! Need some advice about practicing the state transition. :pray:

### Context
For calculating FFG rewards in every cycle transitions, in the old beacon_chain repo, we set a dict `block_vote_cache[block_hash]` *in `ActiveState`* to maintain:
1. `block_vote_cache[block_hash]['voter_indices']`  - the validator indices who voted to the block
2. `block_vote_cache[block_hash]['total_voter_deposits']` - the total deposits of the voters

[This dict will be updated when validating the attestation in per-block transition](https://github.com/ethereum/beacon_chain/blob/eaf14825fd9bd95bafaf5d3457d173a33e84c65e/beacon_chain/state/state_transition.py#L219-L255) for FFG rewarding.

The slot number range for the `block_hash`es needs to be longer than or equal to `max(crystallized_state.last_state_recalc - config.CYCLE_LENGTH, 0)` to  `crystallized_state.last_state_recalc`.

But, there’s a chance that the chain forks, then we need to recalculate the `block_vote_cache` thing.
Unlike `ActiveState` that can be reproduced easily, the voter data need to be calculated by iterating every attestation between the blocks.

### Questions
1. It seems the easy way to create a cache is the `lru-dict` cache?
    - Here is a draft commit:
https://github.com/hwwhww/py-evm/commit/136f4b4c237a68b70fe72a5e4e5448918c135069
    Please just search for `block_vote_cache` and see how it is used.
    - Is it the good practice for our use case?
2. In `Chain`, it generates a new `VM` instance by calling `get_vm` in every action! So if we follow this paradigm, we will do:
    ```python
        def get_sm(self, at_block: BaseBeaconBlock=None) -> 'BaseBeaconStateMachine':
           """
            Returns the StateMachine instance for the given slot number.
            """
            block = self.ensure_block(at_block)
            sm_class = self.get_sm_class_for_slot_number(block.slot_number)
            return sm_class(block=block, chaindb=self.chaindb)
    ``` 
    - So the current `BeaconStateMachine.active_state` object, it will be persisted in every cycle transition (64 slots), but won’t be passed per `import_block` action automatically. Should it be cached in a global `lru-dict` as well?

Thanks!

**Comment by ralexstokes** [comment]
shall we close this issue? seems to have gotten stale wrt the spec
