### ISSUE TITLE
Connecting to same peer twice, causes connection issues

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1352]
* Trinity version: 06e4e734e590e3
* OS: linux

### What is wrong?

I occasionally see in the logs that the same peer connects twice (eg~ the peer pool calls `register_peer()` twice on the same peer). I suspect this causes other problems.

I have been noticing it when running two peers that have each other set as preferred-peers. I also have this patch:

```diff
diff --git a/p2p/discovery.py b/p2p/discovery.py
index d812f7de..f3db9489 100644
--- a/p2p/discovery.py
+++ b/p2p/discovery.py
@@ -590,7 +590,7 @@ class PreferredNodeDiscoveryProtocol(DiscoveryProtocol):
     preferred_node_recycle_time seconds.
     """
     preferred_nodes: Sequence[NodeAPI] = None
-    preferred_node_recycle_time: int = 300
+    preferred_node_recycle_time: int = 60
     _preferred_node_tracker: Dict[NodeAPI, float] = None
 
     def __init__(self,
```

Other than a bit of log spam, it seems to cause other problems with connectivity, and messages being conveyed correctly.

Most easily reproducible before #1301 is fixed, but I suspect it's a problem for connections with any peer.

### How can it be fixed

My first guess is:
- peer A starts a handshake
- it hangs waiting on dao fork headers (I have patch that ignores a timeout error on the dao fork check)
- peer B starts a handshake with A
- peer A times out waiting for B and launches the connection to B
- peer B times out waiting for A and launches the connection to A

Obviously, it would be awesome to remove the DAO check (by switching to eth/65 and using fork-id). It would also make this scenario a lot less likely, but wouldn't remove it completely. I think we need some kind of suppression on both sides of a handshake:
- if we are processing an incoming handshake, don't make an outgoing handshake
- if we are making an outgoing handshake, ignore an incoming one

**Comment by pipermerriam** [comment]
This *might* be a simple fix.

We use a lock to try and ensure that we aren't handshaking with the same peer at the same time:

https://github.com/ethereum/trinity/blob/fcea7124effca010db62bd41a24dd7975825ba90/p2p/peer_pool.py#L335

This line looks like it should be moved to cover this block of code:

https://github.com/ethereum/trinity/blob/fcea7124effca010db62bd41a24dd7975825ba90/p2p/peer_pool.py#L433-L457

This would ensure that we held the lock until the peer was in the peer pool.

Similarly, we probably want to use the lock around this block of code too:

https://github.com/ethereum/trinity/blob/fcea7124effca010db62bd41a24dd7975825ba90/trinity/server.py#L180-L201

And inside of each of these locks we would probably need to do a check for whether the peer has appeared in the peer pool and do an early exit if that is found to be the case.
