### ISSUE TITLE
The scope of beacon chain MVP

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#136]
# Beacon chain MVP testnet

## Motivation
To have a basic runnable beacon chain client as the base for farther iterations.

## Scope
1. Serialization: RLP
	1. Hashing will be inefficient because no tree but the number of validators will be small in testnet so probably okay.
	2. SSZ is nice to have but RLP is okay stub as long as SSZ will eventually use same `Serializable`  interface.
2. Network layer: devp2p
3. Validator Client -> ~~new repo~~
	1. Minimal RPC interface to trinity
	2. Block proposal and Attestations [stub `shard_block_root`]
	3. Simple key management
4. Local attestation aggregation
	* The beacon block proposer will aggregate the attestations.
5. Fork Choice [slot number or longest chain]
6. State transition (ordered by importance)
	1. Shuffling (required)
	2. FFG Finality (required)
	3. Crosslinks (required)
	4. RANDAO [could use stub: `hash(slot_number)`]
	5. Reward/Penalty
	6. Slashing
	7. Registration/Logout

**Comment by ralexstokes** [comment]
shall we close this issue? it seems like we have incorporated the decisions to make here so we can move on
