### ISSUE TITLE
Remove Light Client support (LES)

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1366]
### What is wrong?

Recently, the discussion came up whether we should remove LES support in Trinity. Here are some arguments in favor for removing LES support:

1. The current LES support is very incomplete
2. Removing it reduces code complexity and might make the implementation of certain more important features easier (p2p APIs, RPC APIs etc)
3. LES in itself isn't very well adopted and it might further fall behind if stateless clients (beam sync and friends of all colors) prove a more viable path forward.

### How can it be fixed

1. This is a call for discussion. We should gather opinions on this. @pipermerriam seems to be in favor of doing this, I'm personally somewhere between neutral and in favor (+0), what do others think?

2. If decided in favor, first step would be to just remove all different code paths that are concerned with LES things.

**Comment by cburgdorf** [comment]
@carver @pipermerriam @gsalgado I think we should decide if we want to do this before going into beta. It would be less nice to remove it afterwards. I'm beginning to like/accept the idea of removing LES support.

**Comment by pipermerriam** [comment]
I'm in favor. 

Upside is less code to maintain and hopefully less friction to get the client fully operational in the next 4 months.

Downside is that it allows our APIs to get skewed a bit away from supporting multiple protocols but I don't think this will be a big problem short term, and within a few months we will very probably be running multiple protocols for witnesses.

Case for nuking current for of LES is that it is a very incomplete implementations that is multiple versions behind the current main version of the protocol and it doesn't currently support any of the flow control behavior.

**Comment by carver** [comment]
People seem to be leaning toward removing. I guess I'm -0, but not enough to veto, and I can live with that.

**Comment by gsalgado** [comment]
I'll defer to you guys on this one as I haven't been involved in the developments of the past year, but in theory, if we ever need to bring it back we should be able to, without too much effort, provided our abstractions are good.

**Comment by cburgdorf** [comment]
I think the only thing worth preserving is a pure header sync. E.g. something like `--sync-mode headers`. In fact, while I was working on Görli I temporary created such sync mode because it helped testing the consensus rules. It wasn't possible to use `--sync-mode light` for that as that would have restricted me to find `LES` peers.

**Comment by gsalgado** [comment]
One thing I've just noticed is that `tests/integration/test_lightchain_integration.py` is likely to be the only integration test we have that exercise sync components that are shared between the light and beam syncers, so whenever we do drop LES support we should convert that test to use beam sync

**Comment by pipermerriam** [comment]
I'm still supportive of dropping LES
