### ISSUE TITLE
Consider splitting ChainDB sync and async methods into separate types

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#14]
### What is wrong?

`ChainDBProxy` provides both sync and async versions of the `ChainDB` methods, so it's up to callsites to decide which ones to use and whether or not to mix them. That feels icky and may lead to us accidentally making blocking calls in asyncio code, thus blocking the event loop and preventing other coroutines from running.

### How can it be fixed

We could have separate `ChainDB` types for the sync and async versions, and ensure asyncio code only has access to the async ones

**Comment by carver** [comment]
If I understand correctly, this was resolved by https://github.com/ethereum/trinity/pull/439
cc @cburgdorf
