### ISSUE TITLE
Implement per-slot transition logic

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#140]
### What is wrong?
Implement [per-slot-processing logic from the spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#per-slot-processing).

### How can it be fixed
1. Add the logic to: https://github.com/ethereum/py-evm/blob/9c93531eade79101a6c4f12ed4330d0cbe14dfd9/eth/beacon/state_machines/forks/serenity/state_transitions.py#L32-L39
2. Write tests.

**Comment by Bhargavasomu** [comment]
Since `merkle_root` helper function is merged, I am continuing with this.
