### ISSUE TITLE
Request peer status often and trigger sync after status

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#1401]
### What is wrong?

Per https://github.com/ethereum/trinity/pull/1399#discussion_r358602856

First, Trinity only requests a peer's `STATUS` once happened at the handshake, so the peer pool never updates the information of the peer's head slot, finalized root, finalized epoch, etc.

Second, the spec says we should start the sync once we learn the `STATUS`, while it's not the case in the current implementation.

### How can it be fixed

- We should request the peer's status once for a while to have the updated knowledge of the peer's finalized root and epoch.
- We should have a way to trigger sync immediately after the handshake.

**Comment by ralexstokes** [comment]
Closing due to staleness (and this has also been re-filed here: https://github.com/ethereum/trinity-eth2/issues/17)
