### ISSUE TITLE
test_multiplexer_only_p2p_protocol sometimes fails with a TimeoutError

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1440]
https://circleci.com/gh/ethereum/trinity/168906?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I'm tempted to just increase the timeout there (currently we're using 0.1), unless anyone objects

**Comment by pipermerriam** [comment]
Timeout increase seems appropriate.
