### ISSUE TITLE
Need persistent storage for ENRs

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1444]
In order to fix #1299 we're probably going to need a persistent storage for ENRs retrieved as part of peer discovery. We need to figure out the requirements of said storage and then decide what backend we're going to use for it

**Comment by pipermerriam** [comment]
I'd suggest something similar to the approach used in the `network-db` component, though there is some frustrating fragility in managing the database file itself.

**Comment by jannikluhn** [comment]
I was thinking it would be nice to simply dump ENRs in a directory. This would make it very easy to manually share or compare them with other nodes.

Filename could be `f"enr_{encode_hex(node_id)}_{sequence_number}"`, content the standardized base64 representation.

**Comment by cburgdorf** [comment]
>I was thinking it would be nice to simply dump ENRs in a directory.

I like the simplicity and flexibility of that approach.
