### ISSUE TITLE
Update `Deposit` and `DepositData` data structure

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#149]
### What is wrong?

Per https://github.com/ethereum/eth2.0-specs/pull/388, some renamings and adjustment.

### How can it be fixed

- Update `eth2.beacon.types.deposits.Deposit` fields
- Update `eth2.beacon.types.deposit_data.DepositData` fields

**Comment by ralexstokes** [comment]
i can tackle this one @hwwhww

**Comment by hwwhww** [comment]
@ralexstokes thank you! 👍
