### ISSUE TITLE
Drop Python3.6 support

### ISSUE THREAD

**Issue by AndreMiras** [ethereum/trinity#1490]
* Trinity version: master
* OS: osx/linux/win
* Python version (output of `python --version`): NA
* Environment (output of `pip freeze`): NA

### What is wrong?

Trinity is a client rather than being a library, so it feels weird to me that we're using `tox` and also testing against Python 3.6 and 3.7. I feel more like keeping one or the other.
It slows down the CI and local testing, hence slows down development speed.
I discussed it with @cburgdorf Gitter and [he explained that the concern was to support Ubuntu LTS 18.04](https://gitter.im/ethereum/trinity?at=5e2700e642ae383fa9603364). This is a valid concern, but Ubuntu 18.04 does come with Python3.7 support without playing with backport which. It simply needs to be installed via `apt install python3.7`, refs https://packages.ubuntu.com/bionic/python3.7
I always use Ubuntu LTS on my docker containers and I can always install `python3.7` out of the box without any struggle.
[Christoph agreed and suggested me to create a ticket](https://gitter.im/ethereum/trinity?at=5e270364b674071d4ecec75e) to further discuss it with other developers.

### How can it be fixed

I would be happy to make a PR that drops python3.6 support from `tox.ini` and documentation if any.

**Comment by cburgdorf** [comment]
Just chiming in here to notice that Ubuntu 20.04 (coming in April) will also be the next LTS release. By my highly subjective standards I'd personally be ok if we drop Python 3.6 support sometime soon. /cc @carver @pipermerriam

**Comment by carver** [comment]
> It simply needs to be installed via `apt install python3.7`, refs https://packages.ubuntu.com/bionic/python3.7

:-1: for requiring another step before a trinity install works on a default system.

> I always use Ubuntu LTS on my docker containers and I can always install `python3.7` out of the box without any struggle.

Sure, assuming you know that py3.7 is required ahead of time. If not, then, you try installing it against python3.6 in a venv, and then it's broken even after you install py3.7 on your system, because your venv is pinned to the python version.

You would be surprised at how often people get stuck on "little" issues like python version.

> It slows down the CI and local testing, hence slows down development speed.

Since this seems like the main concern, let's address this directly. Development speed is a hugely desirable feature! But we can get there in other ways:

First, CI isn't that much slower to also check against py3.6, because:
  - the tests run in parallel
  - the longest tests (the ethereum/tests tests) already only run against one python version

Second, you're almost always better off just testing against a single python version locally, and letting CI catch it if you accidentally introduce some code that doesn't work in py3.6. It's not a big ask to have devs run local tests with a custom invocation (not in tox), because they probably want something custom like `pytest-watch` that will auto-run the tests on every file save, anyway.

**Comment by carver** [comment]
> Just chiming in here to note that Ubuntu 20.04 (coming in April) will also be the next LTS release.

It seems like it would be a good time to revisit python versions when the new LTS is released.

**Comment by AndreMiras** [comment]
Disclaimer: I'm a lot like a YAGNI, pragmatic and Pareto principle kinda person :smile: 
First thank you @carver for taking time sharing your feedback :+1: 

Let me try to share my thoughts regarding your comments.

> :-1:  for requiring another step before a trinity install works on a default system.

Since this is about running an Ethereum client, I guess or I hope we're targeting power users, for now at least. So I reckon these people should at least know how to install python3.7, if not having it already installed. Additionally we could distribute a deb/snap package if we really want to make it install friendly.
Also I remember when 18.04 got initially out, Python3.6 wasn't even installed, but I don't think we should have aimed for Python2.7 nevertheless.

> Sure, assuming you know that py3.7 is required ahead of time. If not, then, you try installing it against python3.6 in a venv, and then it's broken even after you install py3.7 on your system, because your venv is pinned to the python version.

You can't install it against python3.6 if it's filtered in the `setup.py`, pip just won't let you install the Python3.7 version of it thanks to `python_requires=">=3.7,<4"`. So it won't ever be in this state.

> First, CI isn't that much slower to also check against py3.6, because [...] the tests run in parallel

Yes that's right, but we also know CI have limited amont of tasks it can run in parallel (at least in the free plan :smile:). So it should actually have an impact to divide the amont of tasks by 2 on most CI (including the one from people's fork).

There're also the things I didn't mention. Like being stuck with some Python3.6 only features or [other things](https://github.com/ethereum/trinity/blob/v0.1.0-alpha.34/trinity/db/orm.py#L44), even though the impact is probably minimal. Or having to "maintain" at huge `tox.ini` and `.circleci/config.yml` file.
Also I initially made this proposal because I felt like contributing and first thing I do usually is to check if there's a CI and try to run tests locally. Tests ran for ages (on high end i7 laptop) and just like broken CI it can discourage new contributors. I know you can run a subset of tox env in local, but still you should at least run the entire set once to be sure the project runs as expected in local before playing I think.
But I'm sure I can survive next LTS release in 3 months from now.
My two WEI :wink:

**Comment by carver** [comment]
> Since this is about running an Ethereum client, I guess or I hope we're targeting power users, for now at least. So I reckon these people should at least know how to install python3.7, if not having it already installed.

Not everyone is the same kind of power user. Being an academic cryptography expert doesn't necessarily mean being really comfortable with python runtime nuances.

> You can't install it against python3.6 if it's filtered in the `setup.py`, pip just won't let you install the Python3.7 version of it thanks to `python_requires=">=3.7,<4"`. So it won't ever be in this state.

Right :+1: 

I think what would actually happen is that pip will install the most recent version that *does* allow python3.6. So people would get stuck on an old version. Unless/until we delete all the historical versions. Ick.

> Also I initially made this proposal because I felt like contributing and first thing I do usually is to check if there's a CI and try to run tests locally.

And I love that you did! I hope I don't come off as dismissive, which is not my intent. The end user experience is very important to me, but so is the developer one. It's all a game of tradeoffs.

> But I'm sure I can survive next LTS release in 3 months from now.

Ok, cool. It's nice that this is a problem that will resolve itself, pretty much. Thanks for bearing with us. Welcome to the repo! :)

**Comment by cburgdorf** [comment]
This landed
