### ISSUE TITLE
Implement p2p discovery v5

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#15]
The discovery v4 protocol is really bad at finding LES peers, so we had to resort to hard-coding known LES peers in the `PeerPool` we use with our `LightChain`. The latest release of geth (1.8.x) implements the [discovery v5 protocol](https://github.com/fjl/p2p-drafts), though, which is much better at finding peers that support a specific sub-protocol (e.g. LES), so we should implement that (probably even dropping v4) and change our `PeerPool` to use `p2p.DiscoveryProtocol` instead of hard-coded nodes.

**Comment by carver** [comment]
> Hi guys, I've created a tracking issue for the v5 spec over in the devp2p repo. We can discuss the protocol there :).

Not sure what the original tracking issue was, but here is the milestone tracking all the v5 things:
https://github.com/ethereum/devp2p/milestone/2

**Comment by gsalgado** [comment]
So, this unfinished v5 implementation was based on an old draft of the spec and now we have a new [implementation](https://github.com/ethereum/trinity/issues/873) based on the current spec draft, therefore I'm closing this
