### ISSUE TITLE
Exceptions leaked by test but no failure

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1505]
When trying to reproduce #1504 I ran `pytest tests/core/p2p-proto/` and [got this massive traceback](https://gist.github.com/gsalgado/d867a03645b9800ee2499e4247534aa9), but no tests were reported as having failed. By the looks of it, one or more tests are not waiting for coroutines to finish and are being flagged as succeeding, but then the coroutines eventually run and crash.

**Comment by gsalgado** [comment]
@carver these seem to be coming from `tests/core/p2p-proto/test_sync.py::test_beam_syncer` and it's reproducible 100% of the time. Thought I'd ping you as you might have some idea what's causing that?

**Comment by carver** [comment]
Note that the test starts the beam syncer and succeeds as long as the syncer gets far enough, then tries to cancel it out. So I can sort of imagine a scenario where a background thread raises an exception during shutdown and it's ignored, and then the test passes.
