### ISSUE TITLE
`cached_property` results in `Any` types

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1520]
### What is wrong?

The `cached_property` decorator results in return values having `Any` 

### How can it be fixed

Fix is present in https://github.com/ethereum/trinity/pull/1519 and needs to be extracted into a stand-alone PR

**Comment by Elnaril** [comment]
Hello @pipermerriam 
I am happy to give a try to this issue if it's fine for you ?

As per my current understanding, this would mean:

1. Apply commit a177bef89b7c89853d3cb1f86175c6865523a9ef (so your modified mypy.ini file from the PR #1519)
2. For each of the  "Returning Any from function declared to return _Some_Type_" error ( I found 57 of them), apply one of the 3 fixes you mentioned:
    - wrap return values in an extra level of type casting
    - use cast to force the types...
    - do a type: ignore

Is it correct ?

**Comment by pipermerriam** [comment]
@Elnaril yes, that seems like the correct approach.  Feel free to open up a PR and we'll take a look.

**Comment by Elnaril** [comment]
@pipermerriam Thank you for your feedback. I'll create a PR asap with the new mypy.ini and start from there.
