### ISSUE TITLE
Node crashes hard with: Cannot overwrite existing ENR (1) with old one (0)

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1570]
* Trinity version: master -- 4e817b74e9aa6e
* OS: linux

### What is wrong?

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 56, in run_process
    trio.run(cls._do_run, boot_info)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/jcarver/code/trinity/trinity/extensibility/trio.py", line 70, in _do_run
    nursery.cancel_scope.cancel()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/jcarver/code/trinity/trinity/components/builtin/peer_discovery/component.py", line 106, in do_run
    await async_service.run_trio_service(discovery_service)
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 156, in run_service
    await manager.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 208, in run
    for _, exc_value, exc_tb in self._errors
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/base.py", line 301, in _run_and_manage_task
    await task.run()
  File "/home/jcarver/code/trinity/venv/lib/python3.6/site-packages/async_service/trio.py", line 76, in run
    await self._async_fn(*self._async_fn_args)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 665, in receive
    await handler(node, payload, message_hash)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 688, in recv_pong_v4
    await self.process_pong_v4(node, token, enr_seq)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 917, in process_pong_v4
    await self.update_routing_table(remote)
  File "/home/jcarver/code/trinity/p2p/discovery.py", line 318, in update_routing_table
    self.node_db.set_enr(node.enr)
  File "/home/jcarver/code/trinity/p2p/discv5/enr_db.py", line 55, in set_enr
    enr.sequence_number
ValueError: ('Cannot overwrite existing ENR (%d) with old one (%d)', 1, 0)
```

(Also the error message looks like the formatting didn't get applied as intended)

### How can it be fixed

:man_shrugging: cc @gsalgado

**Comment by carver** [comment]
I applied this patch locally:

```diff
diff --git a/p2p/discovery.py b/p2p/discovery.py
index 03cde962..399dd3c0 100644
--- a/p2p/discovery.py
+++ b/p2p/discovery.py
@@ -315,7 +315,10 @@ class DiscoveryService(Service):
                 "Checking if %s is still responding, will evict if not", node, eviction_candidate)
             self.manager.run_task(self.bond, eviction_candidate)
 
-        self.node_db.set_enr(node.enr)
+        try:
+            self.node_db.set_enr(node.enr)
+        except ValueError as exc:
+            self.logger.warning("Ignoring received ENR, because: %r", exc)
 
     async def bond(self, node: NodeAPI) -> bool:
         """Bond with the given node.
```

and I get it fairly regularly on boot. Here are a few more:

```
 WARNING  2020-02-21 12:17:23,663      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 3730, 0)
 WARNING  2020-02-21 12:17:44,382      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 246869, 0)
 WARNING  2020-02-21 12:17:49,804      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 2323, 0)
```

**Comment by carver** [comment]
Note that I'm running with `--enable-experimental-eth1-peer-tracking`

**Comment by gsalgado** [comment]
One situation where this would happen is if you have an ENR without endpoint info in the node DB (which should no longer happen). Can you try deleting yours and restarting? I'll see if I can find any other ways to trigger this

**Comment by carver** [comment]
> Can you try deleting yours and restarting? I'll see if I can find any other ways to trigger this

But do we really want to ask everyone using trinity to do this manually at the next release? Maybe we can detect these records in the DB and drop them at runtime with a warning log. Hard-crashing nodes until you manually delete the node database seems like a bug.

**Comment by carver** [comment]
Ah, just seeing that you made the point in the PR that this bug is only possible for people who were running on master. Yeah, fine by me, I'll drop my node DB and try again.

**Comment by carver** [comment]
Hm, I started getting the errors a lot again:

```
 WARNING  2020-02-25 16:43:25,887      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 69, 0)
 WARNING  2020-02-25 16:43:26,375      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 1042, 0)
 WARNING  2020-02-25 16:43:43,214      DiscoveryService  Ignoring received ENR, because: ValueError('Cannot overwrite existing ENR (%d) with old one (%d)', 5, 0)
```

Do you think this be caused by not having #1575 ?

**Comment by gsalgado** [comment]
Nope, if we're trying to overwrite an existing ENR with another one with sequence number 0, #1575 wouldn't help. This probably means we have a race condition somewhere in our code. I'm on it

**Comment by gsalgado** [comment]
Can you change your logging there to include the exc/tb info, like:

`self.logger.warning("Failed to update ENR in db", exc_info=True, stack_info=True)`

**Comment by gsalgado** [comment]
Actually, I just found one situation before #1575 was merged in which we could end up triggering the ValueError from set_enr() -- when a node's address change. I've merged #1575, so you may stop seeing those after you pull that. It'd still be a good idea to merge #1578 as it will prevent trinity from crashing and log the full stack trace so that if you get this again we'll have a better idea of what triggered it

**Comment by carver** [comment]
Okay, yeah, after pulling master (with #1575) I'm not getting any more of the "Ignoring received ENR..." warnings, they are replaced by a bunch of:

```
 WARNING  2020-02-26 12:05:15,018      DiscoveryService  Received msg from <Node(0xae0e13@18.197.213.44)>, using an address (Address(18.197.213.44:udp:20190|tcp:20190)) different than what we have stored in our DB (Address(18.197.213.44:udp:18796|tcp:18796)), deleting our DB record to force a refresh.
```

I guess a lot of people are behind a NAT and broadcast the wrong port?

**Comment by gsalgado** [comment]
I think it's more likely their client uses a random port when creating the NAT portmap. Maybe this shouldn't be a warning

**Comment by carver** [comment]
> I think it's more likely their client uses a random port when creating the NAT portmap.

Aren't we saying the same thing? They created the ENR based on a local port, and the NAT is translating some different external port to their local port.

But then why would the IP address be correct instead of something like `192...`? IDK, not my expertise.

**Comment by gsalgado** [comment]
The NAT port mapping (created via UPnP) expires after a certain time, so if the client uses a random port when creating that, they could get a different one every time. Their ENRs should have the correct ip/port used in the mapping. So they send us an ENR with the port for the current mapping, but then next time they contact us they're under a different mapping and we don't have the ENR for that yet, so we'd trigger that warning

**Comment by carver** [comment]
> So they send us an ENR with the port for the current mapping, but then next time they contact us they're under a different mapping and we don't have the ENR for that yet, so we'd trigger that warning

Makes sense

> Maybe this shouldn't be a warning

:+1: 

---

Re-closing as this particular error has gone away.
