### ISSUE TITLE
Must detect external IP address and use that in our ENR

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1571]
When we generate our local ENR we use the IP address in which DiscoveryService listens to (i.e. `0.0.0.0`). We need to somehow figure out the actual IP address that other nodes can use to connect to us, which can be either the external address of our NAT port-mapping (if one exists) or the address of any(?) externally-facing local interface.

Also, sice the NAT port-mapping is re-created periodically, we will probably need to change UPnPService to send events when that happens so that DiscoveryService can update our local ENR. 

Another complication is that DiscoveryService currently updates our local ENR upon startup, so it might make sense to change it to wait a bit for an event about a NAT port-forwarding being setup, and if one doesn't arrive, use the address of any externally-facing interface.

**Comment by gsalgado** [comment]
@jannikluhn I see that in discv5 this problem has been avoided by not including any endpoint info in the local ENR. Have you thought about how to address it there?

**Comment by jannikluhn** [comment]
> @jannikluhn I see that in discv5 this problem has been avoided by not including any endpoint info in the local ENR. Have you thought about how to address it there?

Yes, this is in fact specified by the v5 spec, see https://github.com/ethereum/devp2p/blob/master/discv5/discv5-theory.md#maintaining-the-local-node-record

We follow the `PONG` aproach: Whenever we receive a PONG, we emit an `EndpointVote` and send it to the [EndpointTracker](https://github.com/ethereum/trinity/blob/master/p2p/discv5/endpoint_tracker.py#L48). Once we have votes from enough peers for a particular endpoint, the tracker updates the ENR.

It looks like ip and port are included in [v4 pings](https://github.com/ethereum/devp2p/blob/master/discv4.md#ping-packet-0x01), so something similar might be possible for v4 as well.

**Comment by gsalgado** [comment]
One problem with using the PING msg for that is the fact that in discv4, the only situation in which a remote will ping us is when the last pong they got from us is more than 12h old, so we may end up in a situation where we get no pings for a long time. I'll see what geth does on discv4 wrt maintaining the local ENR
