### ISSUE TITLE
Manual testing to approve Alpha MVP (for ETH1)

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1601]
### What is wrong?

We're very close to telling people: this is no longer just a prototype, it's a "basically working" alpha (with some intentionally missing features, like log filters).

Before we do that, we should make sure we really believe it ourselves.

### How can it be fixed

Everyone run a trinity node for a while, and try it out.

Things to try on mainnet:
- [ ] check an account balance
- [ ] call a contract
- [ ] broadcast a transaction
- [ ] make something else up that isn't listed here

People who signed off that it looks good enough for MVP:
- [ ] ralexstokes 
- [ ] lithp 
- [ ] cburgdorf 
- [ ] gsalgado 
- [ ] carver
- [ ] kclowes 
- [ ] njgheorghita 
- [ ] pipermerriam 

(I'll change all those ^ to mentions when all the other MVP tasks are resolved)

@kclowes -- Would you be up for adding a guide in web3.py docs to launch trinity and connect to it, then do all the web3.py things you might want to do? If there's anything keeping us from preferring trinity over Infura in the docs, please mention it!

**Comment by ralexstokes** [comment]
@carver running a node in this context means starting from scratch and using beam sync to reach the tip of the chain?

**Comment by kclowes** [comment]
> Would you be up for adding a guide in web3.py docs to launch trinity and connect to it, then do all the web3.py things you might want to do? 

How exciting!! I'd be happy to! I can write something up in the next week or so as I play around with it, or if you want to/already have something ready let me know @carver!

> If there's anything keeping us from preferring trinity over Infura in the docs, please mention it!

Will do!

**Comment by cburgdorf** [comment]
@ralexstokes alternatively, you can use `--beam-from-checkpoint <checkpoint-uri>` to skip downloading the header chain and start from a trusted checkpoint instead.

**Comment by cburgdorf** [comment]
Just to throw in something motivating, I've been running beam sync on Görli for a week with just one minor hiccup which is already fixed in master.

![image](https://user-images.githubusercontent.com/521109/86264054-4ee68080-bbc2-11ea-834b-598cddb83e20.png)

**Comment by cburgdorf** [comment]
@carver this issue mentions `broadcast a transaction` but I just realized we don't have `eth_sendRawTransaction` (#29) implemented yet. I guess this is a *must*  for the beta milestone, no?

**Comment by cburgdorf** [comment]
Confirmed that transactions can be submitted locally via metamask https://goerli.etherscan.io/tx/0x19afa0f2c8a1ac19bf40789ba18adee22937c901740d639cae4fa0a502ee0844
