### ISSUE TITLE
Re-enable tests/integration/test_trinity_cli.py::test_shutdown_does_not_throw_errors

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1603]
### What is wrong?

Test `tests/integration/test_trinity_cli.py::test_shutdown_does_not_throw_errors` was disabled because of flakiness, as described in #1573 

Ultimately we would like to re-enable this test, when shutdown does not throw errors.

### How can it be fixed

Wait until trinity no longer errors on shutdown, then remove the `skip` mark, so that future CI runs will fail if shutdown starts erroring again.

**Comment by cburgdorf** [comment]
Just noting that I had also added it as a todo here https://github.com/ethereum/trinity/issues/1307
