### ISSUE TITLE
Shutdown issues, a braindump

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1613]
I've been trying to fix our shutdown so that all tasks started by our asyncio services are terminated and the components exit cleanly without the need for us to kill them with a SIGTERM, but I've been at this for too long now and have identified several issues that I may not be able to fix in one go, so I thought I'd write them down here

~First issue, affecting all our components: https://github.com/ethereum/async-service/issues/62~ (not really an issue)

Another issue is that some of our services use the `run_asyncio_service()` API, which [doesn't wait for the service to finish after `manager.run()` returns](https://github.com/ethereum/async-service/issues/62#issuecomment-600465685). For those services, the `KeyboardInterrupt` comes from the [`Manager.run()` method](https://github.com/ethereum/async-service/blob/master/async_service/asyncio.py#L213)

Also, for all services using the `background_asyncio_service()` API, I get the KeyboardInterrupt in https://github.com/ethereum/async-service/blob/master/async_service/asyncio.py#L414 (instead of [`_run_and_manage_task()`](https://github.com/ethereum/async-service/blob/master/async_service/base.py#L299) as I'd have expected). When that happens, `background_asyncio_service()` moves on to wait for `manager.stop()`, which seemed to hang forever because the only place where we flag a service as finished is in `Manager.run()`, which at this point is no longer running. I thought this one could be easily fixed by changing `_handle_cancelled()` to flag the service as finished once all tasks are finished, but after making that change I realized the `manager.stop()` still didn't seem to return, and after digging further I noticed it was actually raising yet another `KeyboardInterrupt`, and that seems to happen for any async calls inside the `finally` clause of `background_asyncio_service()`. Need to investigate this further unless somebody can shed a light on what's going on here.

~Finally, ISTM that the [AsyncExitStack we use in the ComponentManager](https://github.com/ethereum/trinity/blob/master/trinity/extensibility/component_manager.py#L87-L101) causes us to wait for the components to finish in sequence, and I don't see why we'd want to do that.~ (fixed in #1650)

**Comment by cburgdorf** [comment]
Just pinging @pipermerriam here as he's been the last one who worked on that and I think he formed an opinion about how things *should be* but then got dragged into other things.

**Comment by pipermerriam** [comment]
The sequential unwinding of components by `AsyncExitStack` isn't intentional and seems like it should be reasonably easy to fix.

The issues with `KeyboardInterrupt` + `run_asyncio_service` seem like they can be addressed in the `async-service` library (looks like @gsalgado has started on a PR to fix that).  Basically, that just seems like a bug.

**Comment by gsalgado** [comment]
I was hoping maybe someone would be able to shed some light on that `KeyboardInterrupt` being raised by `manager.stop()`, while we're handling the first KeyboardInterrupt, but as that didn't happen I'll have to dig into it again as even if I fix all the other issues, that one would still prevent our services from cleaning up during shutdown

**Comment by gsalgado** [comment]
It turns out the double `KeyboardInterrupt` happens because all our processes are receiving 2 SIGINTS. The first one is [sent by the terminal itself, when we hit `Ctrl-C`](https://github.com/ethereum/py-evm/issues/827#issuecomment-394317506), and the 2nd one is sent by `AsyncioIsolatedComponent` when the component gets cancelled. I guess we need to somehow detect when a SIGINT has been sent by the terminal and refrain from doing it again. We can't rely solely on the one sent by the terminal as that won't happen if the main trinity process is sent a SIGINT from something other than a `Ctrl-C` in the terminal

**Comment by pipermerriam** [comment]
This might have to do with os settings and process groups, a topic I don't know much about.

**Comment by ralexstokes** [comment]
yeah it *seems* like we want every child process to ignore (at least
SIGINT) if we can be confident that the parent will manage them properly...

**Comment by carver** [comment]
> yeah it *seems* like we want every child process to ignore (at least SIGINT) if we can be confident that the parent will manage them properly...

Yup, makes sense to me. But then leaves us with the problem of having some kind of bug where the main process is failing to gracefully shut things down.

I think the idiomatic way to deal with that would be to handle `SIGTERM` and have all the child processes shut down more aggressively when it's detected.

**Comment by gsalgado** [comment]
So, IIUC, what you guys are suggesting is for the main process (i.e. the one running `ComponentManager`) to handle a SIGINT by sending a signal other than a SIGINT to all of its children? And then all children would ignore SIGINTs altogether? One annoying thing with that approach is that it means `asyncio-run-in-process` would have to ignore SIGINTs; although that could be made configurable via a function argument.

**Comment by gsalgado** [comment]
Actually, I think #1666 is what we really want as process-groups are only supported by Unix and we can't rely on that as a `kill <pid>` will not send a SIGINT to the whole process group like a Ctrl-C in the terminal (although there are ways to achieve that with the kill command). Also, the fact that we have both AsyncioIsolatedComponent and asyncio-run-in-process sending SIGINTs to child processes shows we probably had forgotten all our processes were under the same group and would get SIGINTs from the terminal upon a Ctrl-C

**Comment by gsalgado** [comment]
All issues here have either been fixed or I've reported separate ones, so closing
