### ISSUE TITLE
Look into moving snappy compression/decompression into the transport

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1618]
### What is wrong?

Currently, the compression of messages using snappy is awkwardly tied up into the `CommandAPI`.  This is purely to support the `Hello` command's lack of compression.

### How can it be fixed

The radical change would be to check around with whether we can deprecate uncompressed messages and make the `Hello` message also use compression which would unify the interface across all commands.

Short of that, moving the compression down into the `Transport` might make sense.  We may be able to do something as simple as putting a check for `if message.command_id == Hello.cmd_id: ...` inside of `TransportAPI.send` and performing the compression/decompression .

**Comment by thisisraghavkumar** [comment]
Hey is this issue taken up by anyone?
