### ISSUE TITLE
Help please. 

### ISSUE THREAD

**Issue by aristodemos** [ethereum/trinity#1632]
Dear trinity community
this is more of a question rather than an issue.
If this should be addressed somewhere else, sorry in advance. 
Please point me into the right direction.

* Trinity version: 0.1a.35
* OS: osx
* Python version (output of `python --version`): Python 3.7.3
* Environment (output of `pip freeze`):
aiohttp==3.6.0
anyio==1.2.3
appnope==0.1.0
argcomplete==1.10.0
asks==2.3.6
asn1crypto==0.24.0
async-exit-stack==1.0.1
async-generator==1.10
async-lru==0.1.0
async-service==0.1.0a7
async-timeout==3.0.1
asyncio-cancel-token==0.2.0
asyncio-run-in-process==0.1.0a4
attrdict==2.0.1
attrs==19.2.0
backcall==0.1.0
base58==1.0.3
bitcoin==1.1.42
blake2b-py==0.1.3
bloom-filter==1.3
cached-property==1.5.1
cachetools==3.1.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
cloudpickle==1.3.0
coincurve==10.0.0
coverage==4.5.3
cryptography==2.6.1
cytoolz==0.10.0
decorator==4.4.0
devp2p==0.9.3
dicttoxml==1.7.4
eth-abi==2.1.1
eth-account==0.4.0
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.8.4
fastecdsa==1.7.4
filelock==3.0.12
geoip2==2.9.0
gevent==1.4.0
greenlet==0.4.15
h11==0.9.0
hexbytes==0.2.0
idna==2.7
ifaddr==0.1.6
importlib-metadata==0.18
ipaddress==1.0.22
ipfshttpclient==0.4.12
ipython==7.8.0
ipython-genutils==0.2.0
jedi==0.15.1
jsonschema==3.0.1
lahja==0.15.2
libp2p==0.1.4
lru-dict==1.1.6
lxml==4.4.1
maxminddb==1.4.1
milagro-bls-binding==0.1.3
miniupnpc==2.0.2
multiaddr==0.0.8
multidict==4.5.2
mypy==0.761
mypy-extensions==0.4.3
netaddr==0.7.19
netdisco==2.6.0
netifaces==0.10.9
outcome==1.0.0
packaging==19.0
parsimonious==0.8.1
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==7.0.0
plotly==4.0.0
pluggy==0.12.0
plyvel==1.1.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.11.3
psycopg2-binary==2.8.3
ptyprocess==0.6.0
py==1.8.0
py-ecc==1.7.1
py-evm==0.3.0a14
pycparser==2.19
pycryptodome==3.8.2
pyelliptic==1.5.7
pyethash==0.1.27
Pygments==2.4.2
pymultihash==0.8.2
PyNaCl==1.3.0
pyparsing==2.4.0
pyrsistent==0.15.7
pysha3==1.0.2
python-dateutil==2.8.0
python-snappy==0.5.4
repoze.lru==0.7
requests==2.22.0
retrying==1.3.3
rlp==1.1.0
rpcudp==3.0.0
ruamel.yaml==0.15.98
six==1.12.0
sniffio==1.1.0
sortedcontainers==2.1.0
SQLAlchemy==1.3.9
ssz==0.2.3
termcolor==1.1.0
toml==0.10.0
toolz==0.10.0
tox==3.13.2
traitlets==4.3.3
trie==1.4.0
trinity==0.1.0a35
trio==0.13.0
trio-typing==0.3.0
typed-ast==1.4.0
typing-extensions==3.7.4
u-msgpack-python==2.5.2
uPnPClient==0.0.8
urllib3==1.25.3
uvloop==0.14.0
varint==1.0.2
virtualenv==16.6.1
wcwidth==0.1.7
web3==5.4.0
websockets==8.1
yarl==1.3.0
zeroconf==0.23.0
zipp==0.5.2

### What is wrong?
This is more of a question rather than an issue.
I am building an ethereal crawler based on trinity codebase.
I am trying to connect to remote ethereum nodes to record their ip, network_id, head.hash, and genesis_hash.
I do this using the following program:
```
import asyncio
from trinity.protocol.eth.peer import ETHPeer, ETHPeerFactory
from p2p.connection import Connection
from p2p.handshake import (
    dial_out,
    DevP2PHandshakeParams,
)
from p2p.kademlia import Node
from p2p import ecies
from cancel_token import CancelToken
from trinity._utils import version
from eth_utils import hexadecimal
from trinity.protocol.eth.payloads import StatusV63Payload, StatusPayload
from trinity.protocol.eth.proto import  ETHProtocolV63, ETHProtocol
from trinity.protocol.eth.handshaker import ETHV63Handshaker, ETHV63HandshakeReceipt, ETHHandshaker, ETHHandshakeReceipt


from eth_keys import keys

from p2p.exceptions import (
    HandshakeFailure,
    DecryptionError,
    MalformedMessage,
    PeerConnectionLost,
    CorruptTransport,
    UnreachablePeer,
)

#Node to connect to
#remote = Node.from_uri("enode://0a779b7536904cbc46c2d1d5c643c11b813580991cec1df14f6679632543e176f757be06f902b2e8201f3c4b58f9cf7a9aec2eaaa0899e34683cd2440e288618@13.73.21.91:30304")
#remote = Node.from_uri("enode://0a740d6b28ff2d1003f30af047f21888a9202cef7b630980c5ad77df707d17178d87acf486d24c847c96deb75e3c367df1c3463d1d872efebf0b893174ee5b6d@138.68.92.248:30303")
#remote = Node.from_uri("enode://093c55f3c61dc0682fa4729759939adc6453ab0dd18a00b3bfccbcbd55ed194e585778353b6f21e73b00ee646dfcd913bbd3bbd835369a92d5b0608fa7584ba1@78.94.240.180:30303")
#remote = Node.from_uri("enode://0959f8fff2068bf829b8bc49a1ee9203eecede5cb45cbfdbe7650cedf4dbcaaf2c61bd4d37e414a1e9efe2b4d05e3e505f3fe62820a9a860e6d9ece774dc3ffa@52.178.119.116:30304")
#enode = "enode://09652bd6afccffd056ccfd12823c6b65a985192c059fe5a894b923f4a0e0cd94d3fc63650f233d39a048a33bbdbc368fa4806c8c7625b1551d6daa7f695f9806@206.81.30.213:30303"
#enode="enode://34c97b8a3d9a4d6181c8e732874428071263aaf2a541ec385383189c07e206217f146006603e8c628b5e37adb1e022421367e23aadf955d994b5ad4ca0ccde95@3.114.90.49:30303"

nodes = []
connections = []

async def interrogate(remote : Node, my_pk: keys.PrivateKey) -> None:



    #CancelToken
    cancel_token = CancelToken(f'token-{remote}')

    #DevP2P_handshake Parameters
    client_version_string = version.construct_trinity_client_identifier()
    p2p_handshake_params = DevP2PHandshakeParams(client_version_string, 30303,4,)



    total_difficulty = 14495542418975058000000
    head_hash = hexadecimal.decode_hex('000000000000000000012e5aad5967a3af779dec93e9a06777713e7378253474')
    genesis_hash = hexadecimal.decode_hex('0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3')

    handshake_v63_params = StatusV63Payload(
            head_hash=head_hash,
            total_difficulty=total_difficulty,
            genesis_hash=genesis_hash,
            network_id=1,
            version=ETHProtocolV63.version,)

    #Connection c
    c: Connection = None
    try:
        c = await dial_out(remote=remote,
             private_key=my_pk,
             p2p_handshake_params= p2p_handshake_params,
             protocol_handshakers= (ETHV63Handshaker(handshake_v63_params),) ,
             token=cancel_token)

        #return c
        connections.append(c)
    except UnreachablePeer:
        print(f"Can't reach {remote!r}")
        cancel_token.trigger()
        cancel_token.trigger()
    except ConnectionResetError:
        print("Could not wait for transport to close")
        cancel_token.trigger()
        cancel_token.trigger()
    except HandshakeFailure as e:
        print(f"HandshakeFailure {remote} -> {repr(e)}")
        cancel_token.trigger()
        cancel_token.trigger()
    except DecryptionError:
        print(f"DecryptionError {remote}")
        cancel_token.trigger()
        cancel_token.trigger()
    except MalformedMessage:
        print(f"MalformedMessage {remote}")
        cancel_token.trigger()
        cancel_token.trigger()
    except PeerConnectionLost:
        print(f"PeerConnectionLost {remote}")
        cancel_token.trigger()
        cancel_token.trigger()
    except CorruptTransport:
        print(f"CorruptTranspor {remote}")
        cancel_token.trigger()
        cancel_token.trigger()
    except Exception as e:
        print(f"problem with node {remote}. Exception {repr(e)}")
        cancel_token.trigger()
        cancel_token.trigger()

    #print(f"Connections: {connections}")
    if c is None:
        pass
    else:
        for c in connections:
            print(f"Peer - ip: {c.remote}")


'''


        fork_blocks = forkid.extract_fork_blocks(self.context.vm_configuration)
        our_forkid = forkid.make_forkid(genesis_hash, head.block_number, fork_blocks)

        handshake_params = StatusPayload(
            head_hash=head.hash,
            total_difficulty=total_difficulty,
            genesis_hash=genesis_hash,
            network_id=self.context.network_id,
            version=ETHProtocol.version,
            fork_id=our_forkid
        )

        return (
            ETHV63Handshaker(handshake_v63_params),
            ETHHandshaker(handshake_params, head.block_number, fork_blocks),
        )

'''


async def main():
    '''
    global nodes
    for remote in nodes:
        pass
    '''
    # My Private Key
    #my_pk = ecies.generate_privkey()
    my_pk = keys.PrivateKey(private_key_bytes=b'\xe3&p\x9f\xd4\xd2\xdaW\xdci\x1d\xf1\xd9r\xcf\xd5\xe3\xcf\xc5Vc%/\xcc:\x8c\xe5\xe1m\t\xe8\x05')
    await asyncio.wait([interrogate(remote, my_pk) for remote in nodes])


if __name__ == "__main__":
    # global nodes
    print("Start reading file...")
    file = 'data/eth_nodes.txt'
    of = open(file)
    i = 0
    for line in of:
        '''
        if i > 15:
            break
        '''
        #print(f"line-{i}:{line}")
        nodes.append(Node.from_uri(line))
        i += 1

    # asyncio.run(main())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
    print(f"Connections: {connections}")
    for c in connections:
        print(f"Peer - ip: {c.protocol_receipts}")
        for r in c.protocol_receipts:
            print(f"receipt - {r}")
```
Please include information like:

* full output of the error you received
* what command you ran
* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by aristodemos** [comment]
My problem is that I receive a lot of timeout exceptions and I am wondering if there is an issue with the above piece of code or I am just unlucky and try to connect to non existing peers.
I occasionally receive a "HandshakeFailureTooManyPeers" exception but most of them are Timeout Excpetion generated by this piece of code in auth.py
```
    async def connect(self) -> Tuple[asyncio.StreamReader, asyncio.StreamWriter]:
        return await self.cancel_token.cancellable_wait(
            asyncio.open_connection(host=self.remote.address.ip, port=self.remote.address.tcp_port),
            timeout=REPLY_TIMEOUT)
``` 
Any thoughts ?

**Comment by pipermerriam** [comment]
My guess is that they are legitimate timeouts.  You could do an experiment to try and confirm this by running the main client and using the `admin_addPeer` API to try and connect to them using the main trinity client.  If you get a timeout there as well it's probable that the nodes are indeed timing out.

**Comment by cburgdorf** [comment]
I'm going to close this, feel free to hop into our [chatroom](https://gitter.im/ethereum/trinity) for any questions.
