### ISSUE TITLE
Backfilling Headers, after using a checkpoint

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1664]
### What is wrong?

When using the header checkpoint feature, Trinity skips over downloading old headers. So Trinity can't serve requests for old headers (from local users or peers).

To be a proper client, we need to download the previous headers from genesis.

### How can it be fixed

One approach:
1. Add a list into the database of missing header ranges. So if you checkpoint to header 5, then sync through header 8, then checkpoint to header 12 and sync for a while, then shut down, then the database would have a key like `MISSING_HEADER_NUMBERS` with a (rlp-encoded?) value: `[[0, 5], [9, 12]]`.
2. Add a background service that reads the values periodically and requests missing headers from peers. (Maybe this service should wait until lag to the tip of the chain is low?) Also, of course, update the ranges of missing headers after they are imported.

**Comment by cburgdorf** [comment]
@pipermerriam I'm moving your comment from #1665 here to clarify something in the context of this issue.

>I believe that we don't track this and that it should not be part of py-evm so I believe it's something that trinity would need to keep track of. It could still store it in the main key/value database.

I want to be sure we are on the same page where these markers belong. Currently, the only way we end up with holes in the chain is by using the Py-EVM API `header_db.persist_checkpoint_header(header, trusted_score)`.

To me, it would feel most natural if Py-EVM where the one to also provide a companion API `header_db.get_chain_integrity()` which might give you answers such as:

```
# consecutive chain from genesis to 1000, missing everything above 1000
header_db.get_chain_integrity()
[[1001, -1]] 

# consecutive chain from genesis to 500
#   missing headers 501 to 599
#   consecutive chain from 600 to 800
#   missing headers from 801 to 899
#   consecutive chain from 900 to 1000
#   missing everything above 1000
header_db.get_chain_integrity()
[[501, 599], [801, 899], [1001, -1]] 
```

I think this kind of thing would be easy for the `HeaderDB` to track and I believe it would be unfortunate if Py-EVM can make it easy for one to end up with a chain with holes while at the same time don't give you APIs to deal with them properly. Also, I don't see much downside in having the functionality directly in Py-EVM.

What are your thoughts about that?

**Comment by pipermerriam** [comment]
I have some doubts about how easy it will be to implement cleanly in Py-EVM but if you want to take a stab I'm not opposed.

**Comment by pipermerriam** [comment]
Alternate path is to implement it in trinity and port it into Py-EVM once the API feels clean assuming that we can implement it cleanly above the PyEVM level which isn't guaranteed.

**Comment by cburgdorf** [comment]
This landed with https://github.com/ethereum/trinity/pull/1714
