### ISSUE TITLE
No DEBUG logs from asyncio_run_in_process shows up in our log files

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1668]
None of the DEBUG logs emitted by asyncio_run_in_process shows up in our log files. I suspect it's because the logger instance used there is created at import time, so it gets the default level (INFO) and not what trinity sets up during startup.

**Comment by gsalgado** [comment]
Same goes for any DEBUG logs from `trinity/extensibility/component.py`, which also creates the logger instance at import time

**Comment by pipermerriam** [comment]
Some important context.

`asyncio-run-in-process` will be using `loggng.getLogger` to setup it's loggers.

The `eth_utils` logging utility functions do some fancy stuff under the hood.  Specifically this:

https://github.com/ethereum/eth-utils/blob/b3146fc7c283208dee29a549372eac1631c5ea3b/eth_utils/logging.py#L79-L81

**Comment by gsalgado** [comment]
It doesn't look like this is caused by the loggers being created at the module level. Any ideas?
