### ISSUE TITLE
FullSyncStrategy/BeamSyncStrategy seem to prevent trinity from shutting down cleanly

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1669]
Running trinity on light mode with #1666 and #1663 merged, I'm able to get it to shutdown cleanly (i.e. no asyncio warnings) with no need to SIGTERM any processes, but that is not the case when running in full/beam sync mode. Any idea what could be causing that, @carver?

**Comment by carver** [comment]
Hm, I'll take a look tomorrow. The Beam syncer spawns extra processes for the importing and previewing, so that's one place I'd start. But no explanation for the full syncer of the top of my head.

**Comment by pipermerriam** [comment]
Maybe something to do with the thread-based stuff?

**Comment by carver** [comment]
Wait, by unclean shutdown, did you mean "hang indefinitely"? Because that seems to be what's happening on master right now...

That's a pretty serious regression.

**Comment by gsalgado** [comment]
I was able to get it to hang once, but having a hard time reproducing it since. Also, #1668 will make debugging a lot harder. I'm digging into that but no luck so far, so if you guys can spare a few cycles and have a look as well, that'd be nice

**Comment by gsalgado** [comment]
@carver meanwhile, can you manually apply https://github.com/ethereum/asyncio-run-in-process/pull/16 into your dev environment so that when you get another hang we have at least a chance of finding out what's causing it?

**Comment by gsalgado** [comment]
Closing in favor of #1687
