### ISSUE TITLE
Add a new test to run Trinity for a minute or 2

### ISSUE THREAD

**Issue by Bhargavasomu** [ethereum/trinity#170]
### What is wrong?
Currently we run `Trinity` a bunch of times with different flags. But the main problem is we run them only for 20 seconds each. This window is too tight and may lead to false positives, i.e. we can't be sure that `Trinity` is in a stable state just because errors didn't show up on this `Circle CI Job`.

I think that not having this measure was the reason for what @veox is observing in #169.

### How can it be fixed
Running all the current `Trinity run` checks for a minute would take a lot of time for the tests to complete. Probably have a single run like `trinity --ropsten` run for a minute or 2 in a separate `Circle CI Job`.

**Comment by Bhargavasomu** [comment]
cc @pipermerriam @carver

**Comment by Bhargavasomu** [comment]
Also it is peculiar that a `Ping` being sent after a `Handshake` is the property of `Parity`, I guess. Since we don't have a test which tries to make sure that everything is smooth with `Parity`, might also be the cause of this issue @veox is seeing in #169

**Comment by pipermerriam** [comment]
I believe we have an integration test which runs `geth` locally with a pre-populated database.  We could do the same for parity.

Also, those geth tests and database directories should probably be updated (I'm making a separate issue for that).

**Comment by pipermerriam** [comment]
I'm a little concerned about a 2-minute CI run but I also think this would be a good test to have in place.  We could

- Do this and just have longer CI runs
- Do this but only run them *nightly* (how will we know if things are failing?)
- Figure out a way to only have this run *if* the other runs succeed?  (this pattern would probably be beneficial for **all** of our integration tests)

**Comment by Bhargavasomu** [comment]
@pipermerriam we won't run all the `Trinity flagged commands` for 2 minutes. I was just hoping we would run the basic commands like `trinity` or `trinity --ropsten` for a minute or 2. This shouldn't take long time, I guess.

**Comment by carver** [comment]
As a percentage of total time in the CI run, another 1-2 minutes sounds reasonable. I don't think it would meaningfully worsen the experience right now, and could pick up useful things. It would be great to get the instant feedback rather than waiting for nightly or pushing it to our pre-deployment testing.

:+1: for doing a 90-second run on a single command, like: `trinity --ropsten`

**Comment by Bhargavasomu** [comment]
Please note that I'm making this `Long Run` version of `Trinity` as a new job, rather than adding it as a new testcase to the already existing jobs. The reason is because, `Circle CI` will parallellize among jobs more efficiently than parallellizing among the `tests in a job`. Hence I am adding a new `Circle CI` Job.
