### ISSUE TITLE
Beam sync test fails intermittently

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1704]
`tests/core/p2p-proto/test_sync.py::test_beam_syncer()` fails intermittently after conversion to new-style Service: https://circleci.com/gh/ethereum/trinity/219875

I had never seen that one failing intermittently before, and since the exception is coming from `async_service`, it looks like something introduced with the recent conversion from BaseService to Service. @carver any idea what could be causing it?

**Comment by carver** [comment]
Looks like it's a `run_task()` being called while a service is shutting down. This used to be permitted in `BaseService`. I just added an `is_running` check, I think that should cover it...
