### ISSUE TITLE
Figure out if we can use trio-run-in-process on our TrioIsolatedComponents

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1719]
I believe the plan was to use trio-run-in-process in our trio-based components in the same way we use asyncio-run-in-process in our asyncio-based ones. That would allow us to get rid of the last place where we use the `multiprocessing` module, and likely get rid of the annoying EOFError we see on CI regularly.

However, the `ComponentManager` runs in the main process (in an asyncio loop), and so, AIUI, it can't call `trio-run-in-process` unless we resort to something like [`trio-asyncio`](https://trio-asyncio.readthedocs.io), which doesn't sound like a good idea as they don't recommend using it on any non-trivial piece of code.

So, I'm wondering if maybe I'm missing something? Or was the plan to use `trio-run-in-process` differently?

**Comment by pipermerriam** [comment]
Plan was to use `trio-run-in-process` the same way we're using `asyncio-run-in-process`.  I originally wanted to converge the two libraries into a single library (like `async-service`) but for now I think we should just use `trio-run-in-process` as-is (maybe with a single pass for whether the behavior and handling is roughly equivalent to that of `asyncio-run-in-process`.

**Comment by gsalgado** [comment]
As discussed on discord, we can't use it as intended for the reason I pointed out in the description, so trying a different approach: https://github.com/ethereum/asyncio-run-in-process/pull/20
