### ISSUE TITLE
Update go-ethereum integration tests.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#172]
### What is wrong?

We have a set of integration tests that run a go-ethereum node with a pre-populated database and test syncing against it.

https://github.com/ethereum/trinity/blob/07cabc7fa9d85db66a6f0065599c79fb7e0a0b0a/tests/integration/test_lightchain_integration.py

These tests run against `v1.7.4` of geth which is reasonably outdated.

https://github.com/ethereum/trinity/blob/master/.circleci/config.yml#L60-L76

#### 1) update to a go-ethereum version `>=1.8.20`

This should be converted to a shell script that can be called from the circle-ci config, similar to the [`merge_pr.sh`](https://github.com/ethereum/trinity/blob/master/.circleci/config.yml#L18) script

#### 2) re-generate the geth database.

This should be done with a local development POW chain with ~100 blocks.  The resulting database directory should then be zipped up.  The integration test should then be updated to properly unzip the database directory into a temporary directory and then run the test.

**Comment by carver** [comment]
One way to build the chain on the new geth version would be to start the v1.7.4 geth version with the test data directory, and then start a newer geth version (say 1.8.21) with discovery turned off and connect it to the 1.7.4 node to sync.

This is one way to make sure you don't sync too many blocks, which can really bloat the test data directory.
