### ISSUE TITLE
Define guidelines for using `raise OtherExc from exc`

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1746]
### What is wrong?

We use the `raise OtherExc from exc` form in many places in our codebase, but in most cases the `OtherExc` will be caught/handled and logged (as in, we log `str(OtherExc)`), and that doesn't include any info from the original exception (`exc`).

### How can it be fixed

We need guidelines (and possibly helpers?) to use that form of raising exceptions, to ensure we include the original exception's msg in the new one so that when we do things like `str(OtherExc)` we get the original exception's msg as well

**Comment by pipermerriam** [comment]
I had been operating under the blind assumption that the message was preserved somewhere in the reporting so this might be an appropriate addition to the [style-guide](https://github.com/ethereum/snake-charmers-tactical-manual/blob/2ce3fa4a9c05f3c4d37bc926e9702a6ebe790ea0/style-guide.md)

**Comment by gsalgado** [comment]
I can't think of a helper function that would make sense in this case, so I'm tempted to just add something to the style-guide recommending that we should always use `raise OtherExc(*exc.args) from exc`, unless somebody can think of a better alternative?

**Comment by pipermerriam** [comment]
Style guide seems appropriate.

**Comment by gsalgado** [comment]
https://github.com/ethereum/snake-charmers-tactical-manual/pull/69
