### ISSUE TITLE
Cute Animal Pictures in Pull Request Template

### ISSUE THREAD

**Issue by Lilith1410** [ethereum/trinity#1759]
Hellos :) 

I just submitted my second Pull Request and I want to contribute in a good manner, following the contributing guidelines. But there is an issue that I ran against twice already and that gives me slight headaches. 

The cute animal pictures that are required under each Pull Request. 

- Where do I get them? 

If I google 'cute animal pictures' I get tons of pictures, but they have watermarks, are licensed or bad quality. The pictures in your guys Pull Requests are free of watermarks, not licensed (I hope), and pristine quality. (And really cute and diverse!) 

- Where do you save them? 

When I click on the images in the Pull Requests, I get sent to a link that seems to be connected to GitHub? That means you don't just copy-paste a link from a picture website but there must be some functionality in GitHub for this? 

It would be great to get some input on this - there seems to be a common shortcut that I am unaware of. I cannot imagine all those hardcore developers submitting a Pull Request and then browsing the web for an hour to get a good picture of a cute baby cat :) 

[Sorry for the noob question, but I am a baby developer in the making and this is a thing that I stumbled over. ]

**Comment by cburgdorf** [comment]
Hahaha, great question! Well, I some people have really sophisticated sources for their images but I generally just google, often for specific animals or let my 7yo pick the animal of the day :)

If you are concerned about the license issues (Personally, I stopped being concerned about it for this trivial use case) please note that google lets you set filters for the images.

![image](https://user-images.githubusercontent.com/521109/83236459-d724d080-a193-11ea-8ce2-f842a4786e89.png)

>When I click on the images in the Pull Requests, I get sent to a link that seems to be connected to GitHub?

Yeah, you can simple drag and drop images into issues and GitHub will upload and store them on their servers for you. That said, I often link them directly to the image src that Google brings up.

>I cannot imagine all those hardcore developers submitting a Pull Request and then browsing the web for an hour to get a good picture of a cute baby cat :)

[Here's a ton of cute little Chameleons](https://www.google.com/search?q=cute%20little%20chameleon&tbm=isch&safe=off&safe=off&tbs=sur%3Af&hl=en&ved=0CAQQpwVqFwoTCOCWsabO2OkCFQAAAAAdAAAAABAC&biw=1905&bih=985) for your next PR all free of licensing issues :)

**Comment by Lilith1410** [comment]
xD hahaha, okay then, I just have to update my mental image to all the developers actually typing in and searching for cute little animal images. 

Thanks for the chameleon pictures and the great answer! My next pull request will definitely have a picture now :)
