### ISSUE TITLE
Sync not following new blocks

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1788]
### What is wrong?

Whenever beam sync catches up to the tip of the chain it simply doesn't seem to monitor for new incoming blocks anymore.

```
    INFO  2020-06-15 16:02:37,960            BeamSyncer  Downloading 8 block bodies for uncle validation, before <BlockHeader #2878389 eb36b56a>
    INFO  2020-06-15 16:02:38,003            BeamSyncer  Getting recent block data for uncle validation
    INFO  2020-06-15 16:02:38,155            BeamSyncer  Have all data needed for Beam validation, continuing...
    INFO  2020-06-15 16:02:38,156  HeaderLaunchpointSyncer  Choosing (BlockHeader(parent_hash=b'I`\x17qp\xaeY\xa4v\xd9\xfa8eX\x17\xd0&U\x879\x19Pn#\xa1\x85\xc7\xd4\xd6\xc1\to', uncles_hash=b'\x1d\xccM\xe8\xde\xc7]z\xab\x85\xb5g\xb6\xcc\xd4\x1a\xd3\x12E\x1b\x94\x8at\x13\xf0\xa1B\xfd@\xd4\x93G', coinbase=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', state_root=b'\xb5\xe33?\x90\xa4x\n\x83\x02\x95z,\x94\x85\xde\xa5j\xc6 \xf4i+\x06\x90\xf2eN\x8b/u\x06', transaction_root=b'\x88\xcf\xdf%\xe9^\x99\x8b\xb7\x02Oh\x15^\xec\x15\xd5\xdf@\xe5!\x86\x8ci\xc5\xc1\x1aF*)\xd7\xb0', receipt_root=b'\x9fsY\xb1W\xae\x93/\x89\xf5\xc0iN\x01\xdb\xe1A\xae$\x91C\x9anf\x13DH\x8e\xcdP\xd0\xfa', bloom=243379359128029679368193394469676036040981803670726871652199982100224040305508798462466536773837319773720111347029137381707652436477999838821802425805789351709786808712980579466169539996259172439702503195115225308223363880662808062707177688678141450061236656541056244881396737871129048581898883062717780699985800382705544301310022249333773267405084080692661842854729066248990462502258869672275618600482304788855040244514838875801124864, difficulty=2, block_number=2878389, gas_limit=8000000, gas_used=152744, timestamp=1592229732, extra_data=b'\xd8\x83\x01\t\x0e\x84geth\x88go1.14.2\x85linux\x00\x00\x00\x00\x00\x00\x00\x9ak\xc8\xb4\xf9\xf2\xf1\xd4\xfb\x0eLo\xd5x\xdf\xbd_xd\xf0A\xacG(\x97\xb2\x16\xd4\x97\x85\xf6,]\xf8\xb9\xf9S2){9\t\x07\xc2I\xe3\x85qS\x03e\xf5\xcd\x82\xf1\xc5\xae\xb0\x86\xf3l\x8d\x859\x00', mix_hash=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', nonce=b'\x00\x00\x00\x00\x00\x00\x00\x00'),) as launchpoint headers to sync from
    INFO  2020-06-15 16:02:38,157        BeamDownloader  Starting beam state sync
    INFO  2020-06-15 16:02:38,176   BaseBodyChainSyncer  Waited 0.0s for <BlockHeader #2878389 eb36b56a> body
    INFO  2020-06-15 16:02:38,177     BeamBlockImporter  Beam importing <BlockHeader #2878389 eb36b56a> (1 txns) ...
    INFO  2020-06-15 16:02:56,446   BaseBodyChainSyncer  Imported block 2878389 (1 txs) in 18.27 seconds, lagging 1 blocks | 44s
    INFO  2020-06-15 16:02:56,446     BeamBlockImporter  Beam importing <BlockHeader #2878390 6973a6d7> (1 txns) ...
    INFO  2020-06-15 16:02:57,830   BaseBodyChainSyncer  Imported block 2878390 (1 txs) in 1.38 seconds, lagging 0 blocks | 30s
    INFO  2020-06-15 16:03:23,948           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
...
DEBUG  2020-06-15 16:10:05,981       BeamSyncService  Beam Sync is lagging behind the latest known header by 0 blocks
```

It then keeps telling me that it is lagging by `0` know blocks but at that time the network has long advanced forward.

### How can it be fixed

1. To reproduce run:

```
trinity --goerli --sync-from-checkpoint eth://block/byhash/0x0a72e4c2f3280cf8455ce008520a5888ce4779da467fa197caa36b8030f93b57?score=4,199,759 --disable-backfill
```
2. 
:shrug:

**Comment by cburgdorf** [comment]
I just added a few more logging statements to verify that our chain tip monitor does in fact continue to see the tip advancing.

```
    INFO  2020-06-15 17:51:50,800     BeamBlockImporter  Beam importing <BlockHeader #2878800 568d812f> (1 txns) ...
   ERROR  2020-06-15 17:51:59,862   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:04,167   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:13,949   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:18,929   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:19,528   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:29,826   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:29,832   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:33,658   PeerPoolEventServer  NEW BLOCK
    INFO  2020-06-15 17:52:44,063           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
   ERROR  2020-06-15 17:52:45,740   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:47,084   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:52:59,669   PeerPoolEventServer  NEW BLOCK
   ERROR  2020-06-15 17:53:03,044   PeerPoolEventServer  NEW BLOCK
```
It's just the sync not picking it up somehow.

**Comment by cburgdorf** [comment]
@carver Can I draw your attention to this issue? My assumption is that this may be surfacing a case that we haven't faced on mainnet yet simply because mainnet isn't progressing as smoothly compared to Görli which is more lightweight.

It is very consistent to reproduce. It catches up to the tip of the chain and then simply stalls, not progressing any new blocks. I'm trying to find the root cause but I thought you may be interested in it as well, as you have a much better picture of the whole thing.

**Comment by carver** [comment]
> this may be surfacing a case that we haven't faced on mainnet yet simply because mainnet isn't progressing as smoothly compared to Görli which is more lightweight.

I don't understand this. How would the rate that blocks come in change things meaningfully? The last time I was running Beam Sync regularly on mainnet, I wasn't seeing anything like this behavior.

> It is very consistent to reproduce.

To me, that means that the most likely answers are:
1. something broke and it doesn't work on mainnet either, anymore
2. some funny interaction between goerli machinery and beam sync

So I'd be checking if the same problem happens on mainnet. Other than that, I'd have to dig around a lot more to figure out how it might be interacting with goerli. (Maybe for example: the validate_extension calls are failing somehow, which wasn't possible on mainnet, and another bug means that the failure of that one task doesn't trigger all of trinity to shut down). So I'd be looking at the debug logs for that, and probably sprinkling in more like you did with `NEW BLOCK`, but closer to the part where the blocks should be added to the queue of blocks to process in beam sync.

**Comment by cburgdorf** [comment]
>How would the rate that blocks come in change things meaningfully?

Not so much the rate at which blocks come. I remember the last time I ran beam sync on mainnet (and  that's been a while) my machine could barely keep up so I had a constant lag and maybe every once in a while a pivot would be needed.

With Görli, we are in a much different situation where it is super easy to get to the tip of the chain and come to a point where there's a lag of `0` blocks. So, I was wondering if this might result in exercising different code paths simply because on mainnet we aren't in the comfortable position of getting to a state of "all done" that easily.

>something broke and it doesn't work on mainnet either, anymore

Yep, I'll try it on mainnet, too. 

I think the last thing I figured out yesterday was that the base header chain syncer hangs here waiting for another segment to come from the skeleton syncer which simply never comes.

https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/trinity/sync/common/headers.py#L978

**Comment by cburgdorf** [comment]
Ok, the behavior seems to be consistent across mainnet and it also seems to be happening on plain `--sync-mode header`. We catch up to the tip, and then stall, not acting on any new headers that we should be following. 

```
INFO  2020-06-16 09:33:21,386     HeaderChainSyncer  Imported 194 headers in 0.05 seconds, new head: <BlockHeader #10274940 973424e9>
INFO  2020-06-16 09:33:22,013     HeaderChainSyncer  Imported 194 headers in 0.05 seconds, new head: <BlockHeader #10275134 e83d3a45>
INFO  2020-06-16 09:33:22,243           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
ERROR  2020-06-16 09:33:22,933   PeerPoolEventServer  NEW BLOCK
INFO  2020-06-16 09:33:23,065     HeaderChainSyncer  Imported 358 headers in 0.08 seconds, new head: <BlockHeader #10275492 95291e20>
ERROR  2020-06-16 09:33:33,045   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:33:35,686   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:33:43,142   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:33:52,683   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:34:04,239   PeerPoolEventServer  NEW BLOCK
INFO  2020-06-16 09:34:22,245           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
ERROR  2020-06-16 09:34:45,570   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:34:51,371   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:35:13,050   PeerPoolEventServer  NEW BLOCK
INFO  2020-06-16 09:35:22,248           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
ERROR  2020-06-16 09:35:25,870   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:35:33,162   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:35:51,748   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:35:52,715   PeerPoolEventServer  NEW BLOCK
INFO  2020-06-16 09:36:22,252           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
ERROR  2020-06-16 09:36:22,785   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:36:24,159   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:36:32,544   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:36:43,469   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:37:00,420   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:37:02,443   PeerPoolEventServer  NEW BLOCK
ERROR  2020-06-16 09:37:17,187   PeerPoolEventServer  NEW BLOCK
INFO  2020-06-16 09:37:22,255           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
```

That sounds like a major regression to me that needs to be addressed before any new release.

**Comment by cburgdorf** [comment]
I identified the issue and came up with a fix in https://github.com/ethereum/trinity/pull/1790 but unfortunately it causes one of our tests to fail. Still investigating.

**Comment by cburgdorf** [comment]
@carver I want to declare bankruptcy on my ability to fix this properly. I've spend most of the day debugging this and while I do have a fix it breaks a differnt thing (see https://github.com/ethereum/trinity/pull/1790)

So, here's all I know:

1. Every sync method is currently broken
2. That is because our loop that observes the chain tip is stalled

https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/trinity/sync/common/headers.py#L919-L926

3. That is, because when the `SkeletonSyncer` is cancelled, the loop **should** advance forward with the next tip info, but doesn't.

https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/trinity/sync/common/headers.py#L136-L137

4. The reason it is blocked is because after the `SkeletonSyncer` is cancelled, we still hang on this line forever

https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/trinity/sync/common/headers.py#L978

5. The way my fix works is by not blocking on `_full_skeleton_sync` but also on the cancellation of the `SkeletonSyncer` itself

```
        async for peer in self._tip_monitor.wait_tip_info():
            try:
                await self._validate_peer_is_ahead(peer)
            except _PeerBehind:
                self.logger.debug("At or behind peer %s, skipping skeleton sync", peer)
            else:
                async with self._get_skeleton_syncer(peer) as syncer:
                    task = asyncio.create_task(self._full_skeleton_sync(syncer))
                    await asyncio.wait(
                        [task, syncer.manager.wait_finished()],
                        return_when=asyncio.FIRST_COMPLETED)
                    task.cancel()
```

6. But that in turn is bringing up the pesty `DuplicateTask` issue observed here https://circleci.com/gh/ethereum/trinity/240595

I tried several other approaches but failed miserably...

**Comment by carver** [comment]
> 1. That is, because when the `SkeletonSyncer` is cancelled, the loop **should** advance forward with the next tip info, but doesn't.
> 
> https://github.com/ethereum/trinity/blob/615d6bcc871ac8c8ae795a39fb55ac6745650cb2/trinity/sync/common/headers.py#L136-L137
> 

Then at first glance, I'm guessing this broke on the transition from `BaseService` to `async-service`.

> 1. The way my fix works is by not blocking on `_full_skeleton_sync` but also on the cancellation of the `SkeletonSyncer` itself
> 
> ```python
>         async for peer in self._tip_monitor.wait_tip_info():
>             try:
>                 await self._validate_peer_is_ahead(peer)
>             except _PeerBehind:
>                 self.logger.debug("At or behind peer %s, skipping skeleton sync", peer)
>             else:
>                 async with self._get_skeleton_syncer(peer) as syncer:
>                     task = asyncio.create_task(self._full_skeleton_sync(syncer))
>                     await asyncio.wait(
>                         [task, syncer.manager.wait_finished()],
>                         return_when=asyncio.FIRST_COMPLETED)
>                     task.cancel()
> ```
> 

Hm, yeah, I can imagine how this causes other downstream bugs potentially, since they are expecting a clean shutdown of the previous skeleton sync. The avenue I'd like to explore is how to make sure that the syncer doesn't hang on cancel.

**Comment by carver** [comment]
> The avenue I'd like to explore is how to make sure that the syncer doesn't hang on cancel.

Well actually, the first step is to reproduce this in a test so that we can more confidently say we've solved it and so that it doesn't regress again. So I'll start there... after lunch.
