### ISSUE TITLE
Let JSON RPC HTTP listen address be configurable via flag

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1795]
### What is wrong?

Currently, the address that our HTTP server listens on is hardcoded to:

https://github.com/ethereum/trinity/blob/3172e4e92a45aa608fbd761abcf7239eb9b0d1ce/trinity/http/main.py#L26

This is greatly limits the usefulness of Trinity. E.g. when running Trinity on DappNode one can not perform requests against the JSON-RPC API (one  of, if not **the** main use cases for letting Trinity run on a DappNode)

### How can it be fixed

Expose this via a flag. E.g. Geth exposes this as `--rpcaddr 0.0.0.0`. I think that `rpc` is a bit ambigious (after all, one can also use IPC to access the JSON-RPC API). Therfore I think we might want to pick one of these names:

- `http-address`
- `http-listen-address`

**Comment by carver** [comment]
Default should still be 127.0.0.1, but seems reasonable to me :+1:
