### ISSUE TITLE
p2p.exceptions.ConnectionBusy exception taking whole node down

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1797]
### What is wrong?

```
    INFO  2020-06-18 15:27:40,544     BeamStateBackfill  Unexpected err while getting background nodes from ETHPeer (eth, 63) <Session <Node(0xe44bbd@88.99.161.14)> cefd5046-d66e-4a22-97a5-88a0469ab079>: 
    INFO  2020-06-18 15:27:40,548     BeamStateBackfill  Unexpected err while getting background nodes from ETHPeer (eth, 63) <Session <Node(0xb5948a@18.218.250.66)> 1ecca656-ed49-43a8-9656-8f7372921d3e>: 
    INFO  2020-06-18 15:27:44,809           ETHPeerPool  Removing ETHPeer (eth, 63) <Session <Node(0xb5948a@18.218.250.66)> 1ecca656-ed49-43a8-9656-8f7372921d3e> from pool: local_reason=None remote_reason=None
    INFO  2020-06-18 15:27:55,917           ETHPeerPool  Removing ETHPeer (eth, 65) <Session <Node(0x6f621a@91.13.207.112)> daab170d-c0d7-4a9f-a605-768d3f271a51> from pool: local_reason=None remote_reason=None
    INFO  2020-06-18 15:27:58,986           ETHPeerPool  Removing ETHPeer (eth, 63) <Session <Node(0xe44bbd@88.99.161.14)> cefd5046-d66e-4a22-97a5-88a0469ab079> from pool: local_reason=None remote_reason=None
    INFO  2020-06-18 15:27:59,064            FullServer  TCP Listener finished, cancelling Server
    INFO  2020-06-18 15:27:59,090      ComponentManager  Received shutdown request: Node exiting. Triggering shutdown
    INFO  2020-06-18 15:27:59,090      ComponentManager  Shutting down, reason: Node exiting. Triggering shutdown
    INFO  2020-06-18 15:27:59,091      ComponentManager  Stopping components
[1m[31m   ERROR  2020-06-18 15:27:59,090                  Sync  Unexpected error in component <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7ff9fa69c790>, shutting down trinity
Traceback (most recent call last):
  File "/usr/src/app/trinity/p2p/exchange/candidate_stream.py", line 81, in payload_candidates
    timeout=total_timeout * NUM_QUEUED_REQUESTS,
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/trinity/trinity/extensibility/asyncio.py", line 58, in _do_run
    await self.do_run(event_bus)
  File "/usr/src/app/trinity/trinity/components/builtin/syncer/component.py", line 393, in do_run
    await self.launch_sync(node, strategy, boot_info, event_bus)
  File "/usr/src/app/trinity/trinity/components/builtin/syncer/component.py", line 409, in launch_sync
    event_bus,
  File "/usr/src/app/trinity/trinity/components/builtin/syncer/component.py", line 241, in sync
    await manager.wait_finished()
  File "/usr/local/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 444, in background_asyncio_service
    for _, exc_value, exc_tb in manager._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 246, in run
    for _, exc_value, exc_tb in self._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 246, in run
    for _, exc_value, exc_tb in self._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/usr/src/app/trinity/trinity/sync/header/chain.py", line 184, in run
    await manager.wait_finished()
  File "/usr/local/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 444, in background_asyncio_service
    for _, exc_value, exc_tb in manager._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 165, in run
    await self.child_manager.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 246, in run
    for _, exc_value, exc_tb in self._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 913, in run
    await self._build_skeleton()
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 933, in _build_skeleton
    await syncer.manager.wait_finished()
  File "/usr/local/lib/python3.7/contextlib.py", line 177, in __aexit__
    await self.gen.__anext__()
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 953, in _get_skeleton_syncer
    self._skeleton = None
  File "/usr/local/lib/python3.7/site-packages/async_generator/_util.py", line 42, in __aexit__
    await self._agen.asend(None)
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 444, in background_asyncio_service
    for _, exc_value, exc_tb in manager._errors
  File "/usr/local/lib/python3.7/site-packages/async_service/base.py", line 300, in _run_and_manage_task
    await task.run()
  File "/usr/local/lib/python3.7/site-packages/async_service/asyncio.py", line 35, in run
    await self._async_fn(*self._async_fn_args)
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 128, in run
    await self._quietly_fetch_full_skeleton()
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 148, in _quietly_fetch_full_skeleton
    await self._fetch_full_skeleton()
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 168, in _fetch_full_skeleton
    launch_headers = await self._find_launch_headers(peer)
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 315, in _find_launch_headers
    newest_matching_header = await self._find_newest_matching_skeleton_header(peer)
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 256, in _find_newest_matching_skeleton_header
    skeleton_launch_headers = await self._fetch_headers_from(peer, start_num, skip=skip)
  File "/usr/src/app/trinity/trinity/sync/common/headers.py", line 466, in _fetch_headers_from
    reverse=False,
  File "/usr/src/app/trinity/trinity/protocol/eth/exchanges.py", line 89, in __call__
    timeout,
  File "/usr/src/app/trinity/p2p/exchange/exchange.py", line 70, in get_result
    timeout,
  File "/usr/src/app/trinity/p2p/exchange/manager.py", line 59, in get_result
    async for payload in stream.payload_candidates(request, tracker, timeout=timeout):
  File "/usr/src/app/trinity/p2p/exchange/candidate_stream.py", line 85, in payload_candidates
    f"Timed out waiting for {self.response_cmd_name} request lock "
p2p.exceptions.ConnectionBusy: Timed out waiting for BlockHeadersV65 request lock or connection: Connection-<Session <Node(0xe44bbd@88.99.161.14)> cefd5046-d66e-4a22-97a5-88a0469ab079>[0m
    INFO  2020-06-18 15:27:59,108            HTTPServer  Closing HTTPServer...
    INFO  2020-06-18 15:27:59,151      ComponentManager  Received shutdown request: Unexpected error in <trinity.components.builtin.syncer.component.SyncerComponent object at 0x7ff9fa69c790>
[1m[33m WARNING  2020-06-18 15:27:59,152      ComponentManager  Received multiple shutdown requests, ignoring[0m
sys:1: ResourceWarning: unclosed <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 30303)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
    INFO  2020-06-18 15:28:02,297      ComponentManager  Components stopped.
    INFO  2020-06-18 15:28:02,306               trinity  Terminating DB process
    INFO  2020-06-18 15:28:02,642                  root  Shutting down Trinity (Node exiting. Triggering shutdown)
``` 

### How can it be fixed

Haven't investigated yet but maybe the `p2p.exceptions.ConnectionBusy` just needs to be handled?

**Comment by carver** [comment]
> maybe the `p2p.exceptions.ConnectionBusy` just needs to be handled?

To clarify my comment on the PR about why this contention is bad: depending on the caller, we might care about getting headers as fast as possible, or other times be okay with longer delays. (eg~ primary sync or backfill sync)

If they all just hit the same peers at the same time, then all the requests politely wait in line, like the primary sync requests line up behind the backfill requests. This isn't terrible if there's just one or two, but if you have a really pathalogical setup, then you might queue up tens or hundreds of backfill requests on the same peer, while primary sync is stuck waiting. So in general, we just try to avoid asking the same peer for the same command very much at all.

**Comment by cburgdorf** [comment]
Ok, so this is in fact caused by the header backfill and comes up reliably when we are connected to a single peer.
The two obvious ways of approaching this could be:

1. Disallow header backfill with the primary sync peer
2. Just swallow the error like #1837 does

Both doesn't feel great. The first option will basically prevent backfill with just a single peer.

Another possible way could be to try to prioritize the general sync over backfill in case these requests have to be made on a single peer. I haven't investigated yet what it would take to do that.

But considering that the header backfill is the shortest of all syncing operations we might get away with kicking the can down the road and just take #1837 for now and create an issue to improve this area post-MVP, maybe even post-beta.

Thoughts?

**Comment by carver** [comment]
> The first option will basically prevent backfill with just a single peer.

Lots of things are sub-optimal if we are only connected to one peer. This particular downside doesn't concern me too much.

---

> Ok, so this is in fact caused by the header backfill and comes up reliably when we are connected to a single peer.

Curious: is it happening after you're caught up to the chain tip? It looks like we aren't doing the pause/resume on the headers the same as we are on the body backfill.

---

Another option we have is to increase `NUM_QUEUED_REQUESTS` to 4. The header syncer might make 2 concurrent requests, so with a duplicate header syncer, it might make 4 total concurrent requests for headers to the same peer.

If we're going to do that, then I'd want to say we should be sure not to run the header syncer in the background until we're at the tip. The pause/resume looks a little trickier to implement on the header syncer, but maybe I'm missing some simple solution. Alternatively, we could at least wait to make sure we're caught up to the tip before launching header backfill the first time.

**Comment by carver** [comment]
Another way we could sort of simulate pause/resume is to limit the range of headers that the header backfill tries to fill. So even if it's a 10M block gap, we only try to fill 100k headers at a time. Then it shuts down and we check if we're lagging behind the tip. If not, we start it up again to get the next 100k headers.

Either way, I think we need to do this:


> increase `NUM_QUEUED_REQUESTS` to ~4~ 5

because if a skeleton peer ghosts us and starts timing out on every request, then we're just about guaranteed to get a `ConnectionBusy`. Because we will probably have 4 pending requests on the queue, and the exception triggers on 3 consecutive timeouts.

**Comment by cburgdorf** [comment]
>Another way we could sort of simulate pause/resume is to limit the range of headers that the header backfill tries to fill. So even if it's a 10M block gap, we only try to fill 100k headers at a time. Then it shuts down and we check if we're lagging behind the tip

Yep, that sounds plausible :+1: 

>because we don't want to roll the dice on the last consecutive request timeout

I don't really understand this part. I think you are saying that, as the code stands, the last request has a slight disadvantage over the previous requests but why is that? `total_timeout` is set to `ROUND_TRIP_TIMEOUT` (unless set by caller)  and so it seems that every requests gets assigned the same timeout. Also instead of doing `timeout=total_timeout * (NUM_QUEUED_REQUESTS + 0.5),` I guess we could also just set `NUM_QUEUED_REQUESTS` to `4.5` instead of `4` or did you mean to write `timeout=(total_timeout * NUM_QUEUED_REQUESTS) + 0.5,` ? 

So, this part isn't clear to me, would be happy if you could elaborate further on it.

**Comment by carver** [comment]
> > because we don't want to roll the dice on the last consecutive request timeout
> 
> I don't really understand this part. I think you are saying that, as the code stands, the last request has a slight disadvantage over the previous requests but why is that? `total_timeout` is set to `ROUND_TRIP_TIMEOUT` (unless set by caller) and so it seems that every requests gets assigned the same timeout. Also instead of doing `timeout=total_timeout * (NUM_QUEUED_REQUESTS + 0.5),` I guess we could also just set `NUM_QUEUED_REQUESTS` to `4.5` instead of `4` or did you mean to write `timeout=(total_timeout * NUM_QUEUED_REQUESTS) + 0.5,` ?
> 
> So, this part isn't clear to me, would be happy if you could elaborate further on it.

I think of `NUM_QUEUED_REQUESTS` as a maximum limit on the supported concurrent requests to a peer. We don't ever actually make concurrent requests, so we queue them up internally. If we issue 4 requests at the same time, and the peer starts timing out to each one consecutively, then by the last timeout, there is a race condition. Either the last request will time out normally, or a `ConnectionBusy` will get raised. But with a little more buffer (that extra 0.5), we should be able to run 4 concurrent requests and have them all timeout without getting a CB exception.

... Though as I'm typing it out, I realize it's fine without any extra buffer, because the 4th request only has to wait on that lock for the previous 3 timeouts. So it's like it already includes a buffer of a single complete timeout.

**Comment by carver** [comment]
Here is the sequence of events, showing why the 4th header requester has to wait for at most 3 consecutive timeouts while trying to get the shared request lock. Header requesters are: tipskel (requesting the headers at the tip, for the skeleton peer), tipmeat (requesting the headers to fill in the skeleton headers, from the same peer), backskel (backfilling headers on a skeleton peer), backmeat (fill in the headers of the skeleton on the backfilling service).
```
+-------+      +---------+       +---------+       +-----------+      +-----------+
| lock  |      | tipskel |       | tipmeat |       | backskel  |      | backmeat  |
+-------+      +---------+       +---------+       +-----------+      +-----------+
    |               |                 |                  |                  |
    |      acquire? |                 |                  |                  |
    |<--------------|                 |                  |                  |
    |               |                 |                  |                  |
    |               |        acquire? |                  |                  |
    |<--------------------------------|                  |                  |
    |               |                 |                  |                  |
    |               |                 |         acquire? |                  |
    |<---------------------------------------------------|                  |
    |               |                 |                  |                  |
    |               |                 |                  |         acquire? |
    |<----------------------------------------------------------------------|
    |               |                 |                  |                  |
    | acquired      |                 |                  |                  |
    |-------------->|                 |                  |                  |
    |               | -----------\    |                  |                  |
    |               |-| time out |    |                  |                  |
    |               | |----------|    |                  |                  |
    |               |                 |                  |                  |
    |       release |                 |                  |                  |
    |<--------------|                 |                  |                  |
    |               |                 |                  |                  |
    | acquired      |                 |                  |                  |
    |-------------------------------->|                  |                  |
    |               |                 | -----------\     |                  |
    |               |                 |-| time out |     |                  |
    |               |                 | |----------|     |                  |
    |               |                 |                  |                  |
    |               |         release |                  |                  |
    |<--------------------------------|                  |                  |
    |               |                 |                  |                  |
    | acquired      |                 |                  |                  |
    |--------------------------------------------------->|                  |
    |               |                 |                  | -----------\     |
    |               |                 |                  |-| time out |     |
    |               |                 |                  | |----------|     |
    |               |                 |                  |                  |
    |               |                 |          release |                  |
    |<---------------------------------------------------|                  |
    |               |                 |                  |                  | -----------------------------------------------------\
    |               |                 |                  |                  |-| has been waiting on the request lock for 3*timeout |
    |               |                 |                  |                  | |----------------------------------------------------|
    |               |                 |                  |                  |
    | acquired      |                 |                  |                  |
    |---------------------------------------------------------------------->|
    |               |                 |                  |                  | -----------\
    |               |                 |                  |                  |-| time out |
    |               |                 |                  |                  | |----------|
    |               |                 |                  |                  |
    |               |                 |                  |          release |
    |<----------------------------------------------------------------------|
    |               |                 |                  |                  |
```

**Comment by cburgdorf** [comment]
Great ascii art! (wondering if you are using [monodraw](https://monodraw.helftone.com/) for that).

>showing why the 4th header requester has to wait for at most 3 consecutive timeouts 

Yes, it makes sense that the 4th header requester has to wait for as long as 3 consecutive timeouts. But that sounds to me as if the 4th request would get assigned a longer timeout than the second and the second would get a longer timeout than the first. But that doesn't match up with the code I'm looking at.

The response timeout is a fixed constant

https://github.com/ethereum/trinity/blob/3eb3628b2d29c4081ef40ad6d8f2f39e04d26586/p2p/exchange/candidate_stream.py#L40

...unless it gets overwritten but even than it isn't taking the number of queued requests into account.
https://github.com/ethereum/trinity/blob/3eb3628b2d29c4081ef40ad6d8f2f39e04d26586/p2p/exchange/candidate_stream.py#L74

It is then multiplied with `NUM_QUEUED_REQUESTS` which again is a constant.

https://github.com/ethereum/trinity/blob/3eb3628b2d29c4081ef40ad6d8f2f39e04d26586/p2p/exchange/candidate_stream.py#L81

So, from what I am seeing, there is nothing actually scaling up the timeouts with the number of queued requests.

**Comment by carver** [comment]
> Great ascii art! (wondering if you are using [monodraw](https://monodraw.helftone.com/) for that).

Used https://textart.io/sequence 

> So, from what I am seeing, there is nothing actually scaling up the timeouts with the number of queued requests.

Right, the timeout for acquiring the lock is always `timeout * NUM_QUEUED_REQUESTS` so `ConnectionBusy` will only be raised if we are attempting to make more than `NUM_QUEUED_REQUESTS` and they are all timing out. But yeah, the timeout doesn't scale up with the number of known tasks currently waiting on the lock.

Then the timeout clock for the calling request doesn't even start until the lock is acquired. ie~ this line is after the lock acquisition:
https://github.com/ethereum/trinity/blob/3eb3628b2d29c4081ef40ad6d8f2f39e04d26586/p2p/exchange/candidate_stream.py#L89

**Comment by cburgdorf** [comment]
>Then the timeout clock for the calling request doesn't even start until the lock is acquired. ie~ this line is after the lock acquisition:

Ah, right! These are individual timeouts (for acquiring the lock and the actual request)

One last question though: Currently `NUM_QUEUED_REQUESTS` is set to `3`. With two more consumers (skeleton backfill, meat backfill) shouldn't we be increasing that to `5` instead of `4`?

**Comment by carver** [comment]
> One last question though: Currently `NUM_QUEUED_REQUESTS` is set to `3`. With two more consumers (skeleton backfill, meat backfill) shouldn't we be increasing that to `5` instead of `4`?

Three is just a general good-enough number, I don't think we were using the full 3 queued requests for headers before (I think we were only using 2).
