### ISSUE TITLE
trinity fails to bootstrap from a genesis state (timeouts)

### ISSUE THREAD

**Issue by rayrapetyan** [ethereum/trinity#182]
* py-evm Version: master
* Python Version (python --version): Python 3.6.7

### What is wrong?
trinity needs more than 10 seconds (`def wait_for_ipc(ipc_path: pathlib.Path, timeout: int=10) -> None:`) to start with a genesis state (trinity/assets/eip1085/mainnet.json, has ~8K accounts to parse inside).
So instead of properly starting it interrupts after 10 seconds of execution with:
```
    INFO  01-16 22:39:44               trinity  Process 70852 has already terminated
    INFO  01-16 22:39:44               trinity  Process 70852 has already terminated
usage: trinity [-h]
trinity: error: Timed out waiting for database start
```
Note: for me similar to https://github.com/ethereum/trinity/issues/87.

### How can it be fixed
One way to fix that is increasing a timeout param mentioned above (this happened once before in https://github.com/ethereum/py-evm/pull/1197, so it's definitely a wrong way). 
But the root reason is much deeper.

I believe it's a fundamental architecture problem to avoid mutability in all possible ways (even when there is no rationale for that, the thing I was arguing about in https://github.com/ethereum/py-evm/pull/1421 which also triggered a discussion: https://github.com/ethereum/snake-charmers-tactical-manual/issues/27). 

When starting from a genesis state, trinity spends 82% of the time in `apply_state_dict` function. It's a perfect example of why immutability can be an evil. Function splits into `set_balance`, `set_code` and `set_nonce`. Each of these three functions performs `get_account` and `set_account` (heavy copy on set) so we have an avalanche of rlp encode\decode-s.

![perf](https://user-images.githubusercontent.com/4700523/51301046-b1ee5280-19e2-11e9-99a1-e45bbeddf5ba.png)

I'm pretty sure we can increase performance here (and in many other places) x10 times had we not been afraid of mutable objects so fanatically, sorry. Thanks.

**Comment by carver** [comment]
Thanks for doing a deep writeup!

> I'm pretty sure we can increase performance here (and in many other places) x10 times had we not been afraid of mutable objects so fanatically

"fanatically" is not an accurate description of how this project avoids mutation. There is quite a bit of mutation in places where it makes more sense. Immutability is just the default, and a good one!

If all these can be confirmed:
a) copying the objects is the main bottleneck
b) the best way to improve the performance is to use mutation
c) the relevant implementation is otherwise unlikely to change in the medium term

then it seems natural that we'll use mutation to solve the problem. But this issue isn't a good reason to change our *default* implementation from immutable to mutable.

**Comment by rayrapetyan** [comment]
Making default implementation "immutable" forces developers add more and more inefficient blocks giving back a false assurance that code is more secure. It's a time bomb, no one notices performance degradation until one day app is not able to bootstrap.

**Comment by pipermerriam** [comment]
We're aware that immutable by default often has performance implications and it's a trade-off we've willingly and knowingly chosen.  Our reason is that we believe the benefits outweigh the downsides.

And as @carver pointed out, we're more than willing to accept mutation based approaches when the trade-offs are right.  This *may* be such a case.  Confirmation of the items mentioned by @carver would be natural pre-requisites to merging a mutation based approach.

However, I believe this is a situation where *caching* could provide significant performance improvements.

https://github.com/ethereum/py-evm/blob/master/eth/db/account.py#L64

We *used* to have something like that in place but we evidently removed it/broke it at some point as the `account_cache` linked above is not used anywhere (and I'm pretty sure it used to be).  I'm betting that some simple caching logic in `_get_account` and `_set_account` would do the trick.

**Comment by pipermerriam** [comment]
I'll add that it would be *nice* if we could also implement a secondary UX improvement here.

1. detect whether the genesis state has been initialized
2. check how many accounts need to be persisted to the DB
3. somehow report either an estimate to how long we expect it to take or better, report progress in persisting this data to the db

Figuring out how to actually estimate time to initialize the db **or** report progress is the hard part here as it's not obvious to me how this would be done but I'm sure we can figure something out.

**Comment by rayrapetyan** [comment]
Using `account_cache` reduces `apply_state_dict` execution time from ~5.8s to ~4.15s (so a ~30% performance boost). Then `persist` following `apply_state_dict` takes ~10.5s to complete. There is no single function requiring optimization inside `persist` it's just "slow", maybe committing algorithm require some fundamental revise.

For now, to allow new users to bootstrap can we just increase timeout to say 30s?

**Comment by carver** [comment]
> We _used_ to have something like that in place but we evidently removed it/broke it at some point as the `account_cache` linked above is not used anywhere (and I'm pretty sure it used to be). I'm betting that some simple caching logic in `_get_account` and `_set_account` would do the trick.

IIRC, this got replaced with `_trie_cache`:
https://github.com/ethereum/py-evm/blob/6abf213883970a94fcd2427a106c1a6e80bf4970/eth/db/account.py#L190-L194

Without diving in right now, I'm guessing that `apply_state_dict` might be persisting to disk more often than it needs to.

---

> I'll add that it would be _nice_ if we could also implement a secondary UX improvement here

:+1: would be sweet

**Comment by pipermerriam** [comment]
I bet we can get that `10.5` seconds down by implementing the ability to do bulk commits.  We should be able to gather up all the key/value pairs that need to be committed and transmit them in bulk to the base database and then use the batch commit APIs for leveldb to commit them in a single operation.  Should be a reasonably easy API to implement on our `BaseDB` and then to leverage in our various DB wrappers.

**Comment by rayrapetyan** [comment]
> IIRC, this got replaced with `_trie_cache`:
> https://github.com/ethereum/py-evm/blob/6abf213883970a94fcd2427a106c1a6e80bf4970/eth/db/account.py#L190-L194
I believe @pipermerriam mean another cache on a higher level (to avoid account rlp encode\decode) on every get\set.

> Without diving in right now, I'm guessing that apply_state_dict might be persisting to disk more often than it needs to.
I believe it doesn't persist anything to disk at all, persisting happens explicitly after `apply_state_dict`.

> I bet we can get that 10.5 seconds down by implementing the ability to do bulk commits. We should be able to gather up all the key/value pairs that need to be committed and transmit them in bulk to the base database and then use the batch commit APIs for leveldb to commit them in a single operation. Should be a reasonably easy API to implement on our BaseDB and then to leverage in our various DB wrappers.
Worth to try, thanks.

**Comment by rayrapetyan** [comment]
@pipermerriam, seems LevelDB impact is negligeable, I've commented out https://github.com/ethereum/py-evm/blob/master/eth/db/backends/level.py#L58 and made sure mainnet/chain-eth1/full has no data created after calling `persist`. Same ~10.5s.
Wondering if anyone else sees similar delays? Btw they are all with --profile enabled. Without --profile they're about 50% less.

**Comment by pipermerriam** [comment]
@rayrapetyan sounds like just extending timeout to around ~30 seconds is a reasonable way to try and remedy this for the time being.

**Comment by rayrapetyan** [comment]
So with disabled --profile my results are:

apply_state_dict time: 3.4938145759515464 (cache disabled)
persist time: 6.1162566469283774

apply_state_dict finished: 2.467690506950021 (cache enabled)
persist finished: 6.084604273899458

**Comment by pipermerriam** [comment]
@rayrapetyan if you want to open another PR enabling the cache, that performance boost seems desirable.

**Comment by rayrapetyan** [comment]
PR enabling the cache is complete: https://github.com/ethereum/py-evm/pull/1718
