### ISSUE TITLE
Flaky hypothesis test

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1822]
### What is wrong?

https://circleci.com/gh/ethereum/trinity/247074?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### How can it be fixed

Haven't looked into it but there's a hint that maybe it is just the `deadline` that needs to be turned off.

**Comment by carver** [comment]
Annoying that it seems to be a very fast test usually. Yeah, the deadline is the think I fight with the most on hypothesis. I suppose we aren't really meant to be using hypothesis as a benchmarking tool. I wonder what the logic for converting from warning to error is. The CI boxes are surely shared and are likely to have really high variability.

I guess :+1: to drop the deadline.
