### ISSUE TITLE
Update imports so eth1 trinity doesn't depend on eth2 modules

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1849]
> The wheel-cli tests (as far as I understand them) ensure users will by able to install and run Trinity via `pip`. They are basically creating a package, install it and then run the CLI tests which run a real Trinity instance and perform some basic tests against it.
> 
> In its current state, this PR seems to break this. In other words, a user trying to install and run Trinity would run into this missing dependency error.

Yup, exactly, this is a great example of a kind of thing that the test is meant to catch.

I think the ideal solution is to update things so that a basic run of trinity on eth1 mainnet doesn't try to load eth2 libraries (then `eth2` dependencies would be optional again). But this solution seems okay in the short term. We definitely don't want to get in the way of eth2 progress.

_Originally posted by @carver in https://github.com/ethereum/trinity/pull/290#issuecomment-465305569_

**Comment by carver** [comment]
That means reverting this commit: https://github.com/ethereum/trinity/pull/290/commits/b0813950438fb45d5d59fcd6c35ca6dccd4ec8c8

As well as doing something like:
01265e467ef39940570b17

Then resolve anything that breaks.

**Comment by ralexstokes** [comment]
i actually started doing this yesterday before i realized it wasn't going to help the issue i was working on and it was not very involved...

i haven't found the time but i'm thinking we make a (temporary) `trinity2` package w/ all of the eth2-trinity stuff and then we can quite cleanly separate them... there has been a little bit of talk of uncoupling the projects further which this gets at.
