### ISSUE TITLE
Testnet Sync

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/trinity#1856]
It's currently not possible to import blocks from a multiclient testnet, such as [altona](https://github.com/goerli/altona/tree/master/altona), for a number of reasons. [This branch](https://github.com/ethereum/trinity/compare/master...g-r-a-n-t:testnet-sync) contains the fixes required to connect to and sync altona, but are hacky and need to be cleaned up.

The following things need to be fixed in separate PRs:
- do not ignore multiaddrs passed in under the `bootstrap-nodes` parameter https://github.com/ethereum/trinity/pull/1869
- revert back to secio as the default libp2p transport upgrade https://github.com/ethereum/trinity/pull/1857
- parameterize the chain config (altona, mainnet, minimal) https://github.com/ethereum/trinity/pull/1900
- add a parameter for a genesis state ssz file https://github.com/ethereum/trinity/pull/1864
- handle block_by_range requests that exceed max size https://github.com/ethereum/trinity/pull/1881

**Comment by ralexstokes** [comment]
some thoughts/suggestions:

> * revert back to secio as the default libp2p transport upgrade #1857

we could just have both transports with priority to `secio` (until `noise` is sorted).

> * add a parameter for a genesis state ssz file

i'd suggest rolling this into the `trinity-beacon-trio network-generator` command, with an option to specify the genesis state.

operations will be simpler for us in the future if we can just pass off the one config file for a given testnet...

> * handle block_by_range requests that exceed max size

seems like the lightest weight thing to do right now is just add a method to `trinity.nodes.beacon.full.SyncRequest` that yields a iterable of blocks by range requests (of the appropriate size). down the line, this functionality could be managed by a syncer component that e.g. gets blocks in parallel and more sophisticated things...
