### ISSUE TITLE
Flaky test: test_beam_syncer_loads_recent_state_root

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1860]
### What is wrong?

This test failed: https://circleci.com/gh/ethereum/trinity/252645?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### How can it be fixed

Needs investigation.

**Comment by cburgdorf** [comment]
Just making sure you see it @carver

**Comment by carver** [comment]
Ah, this looks like a local change that accidentally went to master. I think this was the old setting:
```diff
-           await wait_for_head(chaindb_fresh, target_head, sync_timeout=5)
+           await wait_for_head(chaindb_fresh, target_head, sync_timeout=10)
```

Circle occasionally takes *really* long so we have to leave a long timeout in case. And it finishes early, so it doesn't really hurt CI to have long timeouts (only local testing). I'll open a PR.
