### ISSUE TITLE
Logger-specific levels don't work for external library loggers

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1866]
### What is wrong?

We can pass `-l p2p=info` to limit the `p2p` logger to >=INFO, but that doesn't work for external library loggers like `async_service` or `asyncio_run_in_process`. IOW, if you pass `-l async_service=info` you'd still get all of its DEBUG logs.

### How can it be fixed

Need to investigate, but this seems to happen because we use our custom `get_logger()` helper here: https://github.com/ethereum/trinity/blob/ea0d08e36c51ac6cf56d483215f401ba72462639/trinity/_utils/logging.py#L157-L169

If we use `logging.getLogger()` it works as expected

**Comment by pipermerriam** [comment]
Copy/Pasta from my comment in #1865 

So the reason this doesn't work is very likely related to this code from `eth-utils`

https://github.com/ethereum/eth-utils/blob/386863e6b7d95ac5acb11f6ba81619dc88ed6eb9/eth_utils/logging.py#L78-L81

The stdlib `logging` module caches logger instances and that code is ensuring that the logger instance is using the logger class specified...

Maybe a better way to approach this would be something like:

```python
if name.startswith('trinity.') or name.startswith('p2p.'):
    # use get_logger
else:
    # use logging.getLogger
```

**Comment by Elnaril** [comment]
Hello @gsalgado,
It seems to me the fix mentioned above has been applied.
Is this issue still open ?
