### ISSUE TITLE
Geth's checkpoint challenge is ignored by us, causing remote to disconnect

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1907]
### What is wrong?

Upon connecting a geth instance to my local trinity, trinity consistently ignores geth's initial checkpoint challenge (https://github.com/ethereum/go-ethereum/blob/6d74d1e5f762e06a6a739a42261886510f842778/eth/handler.go#L344-L361), even though trinity has the header requested. Because of that geth assumes we're useless as we advertise a certain HEAD and do not provide a header prior to that when asked to

It looks like the checkpoint challenge request (the first msg after the handshake) is being dropped because when it arrives the peer has no subscribers, so https://github.com/ethereum/trinity/blob/50a2c376d49e606aaef2a73f0b8a4be5c13d6246/p2p/peer.py#L316-L321 is a no-op

In the original handshake implementation, I remember dealing with something similar, which was addressed by temporarily storing those messages and manually adding them to the subscriber's queues once the peer was added to the pool: https://github.com/ethereum/trinity/blob/50a2c376d49e606aaef2a73f0b8a4be5c13d6246/p2p/peer_pool.py#L307-L328

But we're no longer using the second argument to `_add_peer()`: https://github.com/ethereum/trinity/blob/50a2c376d49e606aaef2a73f0b8a4be5c13d6246/p2p/peer_pool.py#L290

**Comment by carver** [comment]
> But we're no longer using the second argument to `_add_peer()`:
> 
> https://github.com/ethereum/trinity/blob/50a2c376d49e606aaef2a73f0b8a4be5c13d6246/p2p/peer_pool.py#L290

Hah, yeah, that looks obviously broken. :clap: for a clear write-up.
