### ISSUE TITLE
Write integration tests for metrics component

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1908]
### What is wrong?

Starting Trinity with metrics enabled is currently broken (investigation ongoing at this point) and the fact we didn't notice is because we don't have any tests for that area of the code base.

### How can it be fixed

I could imagine two different scenarios for integration tests:

A.) We run a test that spins up Trinity to run against our deployed metrics infrastructure. We would put the credentials in CircleCI environment variables.

PRO: - easy
CON: - could be flaky if the metrics infrastructure or connection to it is unreliable (cough cough, seems offline at the time of writing)

B.) The test spins up its own InfluxDB locally (there may be a ready to use docker image for that to become easier)

PRO: -less flaky
CON: - more effort

**Comment by cburgdorf** [comment]
@njgheorghita Possibly something you could be interested to tackle

**Comment by njgheorghita** [comment]
@cburgdorf Taking the fact that trinity-bench just crashed as a sign, I'd agree that #2 is probably the better solution. In #1903 - do you know approximately how long the node was running before the error occurred? Was it instant? AKA in this test, how long should the node report metrics for to more-or-less conclude that everything works as expected?

**Comment by cburgdorf** [comment]
>AKA in this test, how long should the node report metrics for to more-or-less conclude that everything works as expected?

I would say the test is successful as soon as we were able to read written metrics out of the influxdb. I would say we can start simple with only checking for values that are known to be written immediately such as the system metrics.
