### ISSUE TITLE
Monitor the backfill progress on the grafana dashboard

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#1938]
### What is wrong?

We do currently only track the current head.

![image](https://user-images.githubusercontent.com/521109/88272672-5983c980-ccd9-11ea-9b78-b64053a22a46.png)

But this can give a wrong impression because beam sync is supposed to track the head of the chain even long before it has caught up with all historical headers and blocks.

### How can it be fixed

Our `ChainDB` exposes two APIs to find out about the current integrity of the chain, namely:

- `get_header_chain_gaps()`
- `get_chain_gaps()`

Both return `ChainGaps` which consist of sequences of block ranges (`(1, 20), (45, 789), ...` as well as a marker of the first missing header or block at the tip of the chain (e.g. `10_000_457`).

It would be super neat to put this into a nice visualization.

**Comment by cburgdorf** [comment]
@njgheorghita just pinging you for visibility as it may be interesting to you :)

**Comment by njgheorghita** [comment]
@cburgdorf Yeah, looks cool! I'm traveling to js land for the next week or so, heads down on implementing ethpmv3 support in truffle, but as soon as I return to python land I'll tackle this
