### ISSUE TITLE
Blocked event loop canary

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#1962]
### What is wrong?

This is sort of a bug report and an architecture idea.

First the bug:   Block imports are reported on a 5 second interval and when I watch the `elapsed` part of the log message it regularly is something like `5.1` seconds and quite often you'll see variance up to even a few extra seconds.  This seems to indicate something is either blocking the event loop or the event loop is simply being overloaded.  I don't know how to tell the difference.

```
    INFO  2020-07-25 07:56:39,208    BodyChainGapSyncer  blks=1     txs=151    bps=0    tps=1     elapsed=5.0  head=#10528187 feee..eab8  age=8h59m31s
    INFO  2020-07-25 08:11:10,446   FastChainBodySyncer  blks=0     txs=0      bps=0    tps=0     elapsed=5.0  head=#10529063 a24a..8af6  age=6h2m3s
    INFO  2020-07-25 08:11:18,144    BodyChainGapSyncer  blks=6     txs=1100   bps=0    tps=8     elapsed=6.3  head=#10529000 2637..a0af  age=6h14m53s
    INFO  2020-07-25 08:11:23,145    BodyChainGapSyncer  blks=0     txs=0      bps=0    tps=8     elapsed=5.0  head=#10529000 2637..a0af  age=6h14m58s
    INFO  2020-07-25 08:11:29,744    BodyChainGapSyncer  blks=0     txs=0      bps=0    tps=7     elapsed=6.6  head=#10529000 2637..a0af  age=6h15m4s
    INFO  2020-07-25 08:11:35,771    BodyChainGapSyncer  blks=11    txs=2430   bps=0    tps=27    elapsed=6.0  head=#10529011 a8be..397e  age=6h12m29s
    INFO  2020-07-25 08:11:41,881    BodyChainGapSyncer  blks=5     txs=912    bps=0    tps=33    elapsed=6.1  head=#10529016 f5b2..7bdd  age=6h11m47s
    INFO  2020-07-25 08:11:46,881    BodyChainGapSyncer  blks=7     txs=1077   bps=0    tps=42    elapsed=5.0  head=#10529023 4e72..9fef  age=6h10m54s
    INFO  2020-07-25 08:11:52,662    BodyChainGapSyncer  blks=5     txs=722    bps=0    tps=46    elapsed=5.8  head=#10529028 3c82..a747  age=6h10m5s
    INFO  2020-07-25 08:11:59,229    BodyChainGapSyncer  blks=8     txs=1512   bps=0    tps=56    elapsed=6.6  head=#10529036 1fca..6a17  age=6h8m17s
    INFO  2020-07-25 08:12:04,397    BodyChainGapSyncer  blks=10    txs=1495   bps=0    tps=67    elapsed=5.2  head=#10529046 61ce..2f30  age=6h6m36s
```

Second: We should be able to detect this by simply running a loop with a sleep and measuring expected time vs actual time.

### How can it be fixed

In whatever process we have that *might* end up with this problem, we could implement a simple service that does the following.

```python
async def monitor_event_loop_performance():
    while True:
        timer = Timer()
        await asyncio.sleep(10)
        elapsed = timer.elapsed()
        if elapsed - 10 > 0.1:
            logger.warning("Event loop blocked or overloaded:  variance=%f", elapsed - 10)
```

Logging output might also benefit from including process id and maybe even a text identifier that we explicitly provide.  This would give us a "canary in the coal mine" to help us identify how often this is happening.  If we can actually address whatever is currently causing this problem, this type of architecture should give us some early warnings when/if we introduce new code which causes the loop to be blocked.

#### Open Question

Is there any way for us to differentiate between the loop being blocked and the loop being overloaded....  That would be nice.

**Comment by gsalgado** [comment]
> Is there any way for us to differentiate between the loop being blocked and the loop being overloaded.

I couldn't find any, but if our monitoring task also iterated over all running tasks and reported the top X ones ordered by cumulative cpu time (provided that's even possible), it might help identify those issues

**Comment by pipermerriam** [comment]
Reporting total number of tasks is probably just nice information to have as we might be able to at least draw some correlation there.

**Comment by pipermerriam** [comment]
Some quick experimentation showed that my event loop would become congested at around 1300-1400 tasks.

```python
import asyncio
import time


global num_tasks
num_tasks = 0
global blocked
blocked = False


async def canary():
    global blocked
    while True:
        start_at = time.monotonic()
        await asyncio.sleep(1)
        end_at = time.monotonic()
        elapsed = end_at - start_at
        if elapsed > 1.01:
            print(f'BLOCKED({num_tasks}): {elapsed}')
            blocked = True
        else:
            print(f"OK({num_tasks}): {elapsed}")


async def clog():
    while True:
        await asyncio.sleep(0)


async def do_it():
    global num_tasks
    tasks = []
    tasks.append(asyncio.ensure_future(canary()))
    while not blocked:
        num_tasks = len(tasks)
        tasks.append(asyncio.ensure_future(clog()))
        await asyncio.sleep(0.001)
    await asyncio.sleep(5)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(do_it())
```

we could actually measure this value and emit warnings when the number of tasks exceeds our measured value.  Maybe enable this with a CLI flag so that it isn't always on but it's easy for us to turn it on when we run locally.

**Comment by pipermerriam** [comment]
Last thing.  This *might* be worth running in our component processes as well but that gets more complex.

**Comment by gsalgado** [comment]
Just found that uvloop has a bunch of debug properties (https://github.com/MagicStack/uvloop/blob/6ef69a797db0afe781b5ddcd74691767f8261a53/uvloop/loop.pxd#L96-L130) but those are only available on a debug build as they probably add significant overhead. Might be worth looking into that, although it wouldn't be exactly trivial to enable and all the attributes are private so our reporter may stop working even with minor version updates

**Comment by gsalgado** [comment]
Also, I just realized that if we use a monitoring task that keeps track of how often it gets scheduled it will only issue warnings if the loop is blocked at the time it was supposed to be scheduled, so if we have one rogue task that runs frequently and on every iteration blocks for less than the monitoring task's report interval, we'd never get any warnings.  One (hackish) alternative would be to use a custom event loop that inherits from python's default one and overwrites the `_run_once()` method, to keep track of how frequently the event loop is being called and possibly other things

**Comment by pipermerriam** [comment]
> Also, I just realized that if we use a monitoring task that keeps track of how often it gets scheduled it will only issue warnings if the loop is blocked at the time it was supposed to be scheduled

I agree here.  We would only see the warning if the blocking task is running at the time that the canary should wake up.

> so if we have one rogue task that runs frequently and on every iteration blocks for less than the monitoring task's report interval, we'd never get any warnings.

I don't think this is true.  Suppose that our monitoring task is scheduled to wake up in `0.1` seconds.  If our blocking task takes `0.3` seconds to run, and the loop runs it within `0.2` seconds before the canary task is scheduled to wake up, the canary task will end up being woken up late and would report the deviation.  It's not ideal since we could be in a position where this only occurs occasionally, but I still think this is the behavior we want, especially since the larger the blocking time, the larger the chance that it gets detected by the canary, and the smaller the block, the less important it is to worry about it.

**Comment by gsalgado** [comment]
> Last thing. This might be worth running in our component processes as well but that gets more complex.

Actually, the event loop running in the main process doesn't do much heavy lifting, right? Isn't it mainly taking care of collecting logs and state updates from the component processes? If that's the case I think what we really need is to run a separate monitoring task on the event loop of each component process

**Comment by cburgdorf** [comment]
>Isn't it mainly taking care of collecting logs and state updates from the component processes?

Yes, that's the correct. Specifically, the logs from the syncing progress that sparked the discussion originate from the syncer / peerpool component. So, I guess it really are the component processes that need to be monitored.

**Comment by gsalgado** [comment]
> Some quick experimentation showed that my event loop would become congested at around 1300-1400 tasks. This number is probably bogus because I'm syncing both turbogeth and geth on my machine and my CPU load is high.

Mine was the same, on a completely idle machine. I guess it is what a single core (which is all python gets, right?) can handle
