### ISSUE TITLE
BaseComponent.logger gets overwritten with a Logger instance

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#1971]
Inside `BaseComponent.run_process()` self.logger is an `ExtendedDebugLogger`, but then in `BaseComponent._do_run()` it is a `Logger`, so any calls to `debug2()` crash.

Need to figure out what's causing that and fix it

**Comment by pipermerriam** [comment]
this might be relevant: https://github.com/ethereum/eth-utils/blob/master/eth_utils/logging.py#L66-L86

**Comment by gsalgado** [comment]
This is actually caused by the way pickling is implemented for `logging.Logger`: https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1740-L1746

Our components are implemented as methods on `*IsolatedComponent`, so when we pass those methods to `run_in_process()`, the `*IsolatedComponent` instance will be pickled (together with the logger) and sent to the subprocess, but in the subprocess the logger will be recreated by calling `getLogger(name)` (the return value of `logging.Logger.__reduce__()`, so it will be a `Logger` instance.

This is not a problem if we pickle/unpickle in the same process as the `ExtendedDebugLogger` instance will be cached in the logging module, so the `getLogger(name)` call will return that

Maybe what we need is a custom `ExtendedDebugLogger.__reduce__()`:

```
    def __reduce__(self):
        return get_extended_debug_logger, (self.name,)
```
