### ISSUE TITLE
Profiling: a third of CPU time is spent looking up sync task dependencies

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#200]
... and another 9% constructing sync task objects?..

-----

* py-evm Version: `master` and a WIP branch, see below
* OS: Arch Linux
* Python Version (python --version): 3.7.2
* Environment (output of `pip freeze`): [gist](https://gist.github.com/veox/d46ed02d3973cb9b0489b697cbeb9515)

### What is wrong?

Currently syncing main-net, around block `#4_000_000`: often blocked due to single-CPU execution.

The following (selective) log illustrates it well:

```
    INFO  01-20 03:18:15   FastChainBodySyncer  blks=0     txs=0      bps=1    tps=100   elapsed=7.2  head=#3931833 15f4..f26f  age=1y6m3w                                                                                                    
    INFO  01-20 03:18:30   FastChainBodySyncer  blks=0     txs=0      bps=1    tps=95    elapsed=14.8  head=#3931833 15f4..f26f  age=1y6m3w                                                                                                   
    INFO  01-20 03:18:35   FastChainBodySyncer  blks=0     txs=0      bps=1    tps=91    elapsed=5.0  head=#3931833 15f4..f26f  age=1y6m3w                                                                                                    
    INFO  01-20 03:18:59   FastChainBodySyncer  blks=0     txs=0      bps=1    tps=86    elapsed=23.9  head=#3931833 15f4..f26f  age=1y6m3w                                                                                                   
    INFO  01-20 03:19:18   FastChainBodySyncer  blks=0     txs=0      bps=1    tps=82    elapsed=18.7  head=#3931833 15f4..f26f  age=1y6m3w                                                                                                   
    INFO  01-20 03:19:29   FastChainBodySyncer  blks=11    txs=696    bps=1    tps=81    elapsed=11.7  head=#3931844 526b..2b18  age=1y6m3w                                                                                                   
    INFO  01-20 03:19:34   FastChainBodySyncer  blks=299   txs=18832  bps=4    tps=265   elapsed=5.0  head=#3932143 7cc1..8aa5  age=1y6m3w                                                                                                    
    INFO  01-20 03:19:39   FastChainBodySyncer  blks=240   txs=15116  bps=6    tps=402   elapsed=5.0  head=#3932383 d0ac..ff77  age=1y6m3w                                                                                                    
    INFO  01-20 03:20:20   FastChainBodySyncer  blks=28    txs=1829   bps=6    tps=385   elapsed=40.6  head=#3932411 534c..09b4  age=1y6m3w                                                                                                   
    INFO  01-20 03:20:25   FastChainBodySyncer  blks=21    txs=1387   bps=6    tps=379   elapsed=5.0  head=#3932432 92ba..2488  age=1y6m3w                                                                                                    
    INFO  01-20 03:20:30   FastChainBodySyncer  blks=3     txs=111    bps=5    tps=361   elapsed=5.1  head=#3932435 35e5..1ea4  age=1y6m3w                                                                                                    
    INFO  01-20 03:20:35   FastChainBodySyncer  blks=376   txs=20108  bps=9    tps=544   elapsed=5.0  head=#3932811 34b0..e4c5  age=1y6m3w                                                                                                    
    INFO  01-20 03:20:56   FastChainBodySyncer  blks=12    txs=909    bps=8    tps=519   elapsed=21.0  head=#3932823 03e1..8183  age=1y6m3w                                                                                                   
    INFO  01-20 03:21:05   FastChainBodySyncer  blks=125   txs=7801   bps=9    tps=538   elapsed=8.7  head=#3932948 f6c5..33e5  age=1y6m3w                                                                                                    
    INFO  01-20 03:21:16   FastChainBodySyncer  blks=0     txs=0      bps=8    tps=511   elapsed=10.8  head=#3932948 f6c5..33e5  age=1y6m3w                                                                                                   
    INFO  01-20 03:22:33   FastChainBodySyncer  blks=3     txs=250    bps=8    tps=485   elapsed=77.2  head=#3932951 14b0..221e  age=1y6m3w                                                                                                   
    INFO  01-20 03:22:38   FastChainBodySyncer  blks=6     txs=462    bps=7    tps=466   elapsed=5.1  head=#3932957 25ef..e801  age=1y6m3w                                                                                                    
    INFO  01-20 03:22:43   FastChainBodySyncer  blks=343   txs=17344  bps=10   tps=616   elapsed=5.0  head=#3933300 bd78..c471  age=1y6m3w                                                                                                    
    INFO  01-20 03:22:48   FastChainBodySyncer  blks=114   txs=5943   bps=11   tps=644   elapsed=5.0  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:22:55   FastChainBodySyncer  blks=0     txs=0      bps=10   tps=612   elapsed=7.6  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:23:02   FastChainBodySyncer  blks=0     txs=0      bps=10   tps=581   elapsed=6.2  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:23:11   FastChainBodySyncer  blks=0     txs=0      bps=9    tps=552   elapsed=9.0  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:23:18   FastChainBodySyncer  blks=0     txs=0      bps=9    tps=525   elapsed=6.9  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:23:23   FastChainBodySyncer  blks=0     txs=0      bps=8    tps=498   elapsed=5.1  head=#3933414 f7e2..b44f  age=1y6m3w                                                                                                    
    INFO  01-20 03:23:39   FastChainBodySyncer  blks=0     txs=0      bps=8    tps=473   elapsed=15.9  head=#3933414 f7e2..b44f  age=1y6m3w
```

Guess: data starts coming in, but is soon shut off due to block/transaction processing not being able to keep up.

Therefore evaluating inefficiencies and multi-CPU options.

Stats (moved from https://github.com/ethereum/trinity/issues/120#issuecomment-455797061):

On my [`sync-hodge-podge`](https://github.com/veox/trinity/commits/sync-hodge-podge) branch, sync-task pruning takes up 31.6%. :( Adding some debug statements shows most tasks are pruned at depth 1 (no big surprise, I guess).

On `master` (at commit 8cedd0529020270cbe7eba1f67b62a7655562eca), it's 33.9%, so about the same as above (but less stable).

**Profiling for the above:** [in gist](https://gist.github.com/veox/ff3b7114a2869b2d9067ac2aed623755) (<10 minutes run each).

`sync-hodge-podge` is a WIP thing with a lot of garbage and some sync-fixing PRs; of which only PR #165 is still unmerged, and seems merge-worthy to me.

`s-h-p` is able to keep limping on for hours, and demonstrates the above log pattern coming and going in waves. CPU core load remains at constant >=99.9% on syncing thread - therefore my conclusion about saturation above.

### How can it be fixed

Review sync-tasks, in particular:

https://github.com/ethereum/trinity/blob/8cedd0529020270cbe7eba1f67b62a7655562eca/trinity/_utils/datastructures.py#L650-L658

Previous profiling (many months ago) had `sedes`-related processing in first place (now also major, but second). Have not reviewed `sedes`-providing package for inefficiencies (e.g. object-based processing vs. class-based).

`py-evm` has PR https://github.com/ethereum/py-evm/pull/1497 to move some syncing into a plugin (and therefore separate thread). I've not looked at it yet.

**Comment by veox** [comment]
Ping @carver, I guess, as this relates to issue #120: changes made there will likely affect task pruning efficiency, as described here.

**Comment by veox** [comment]
It seems that lowering `_default_max_depth` has the desired effect of spending less time in `datastructures.py`; but I'm cargo-culting at this point.

**Comment by carver** [comment]
Cool, definitely helpful to know that this is a significant bottleneck. The most obvious note is that looking up the oldest task is `O(n)` time on the length of historical tasks (which goes up to max-depth, and jives with the idea that reducing max-depth should lower the cost).

Some options:
1. cache intermediate results, only re-verifying that old root is still root
2. track root tasks explicitly and keep lookups from leaf -> root
3. keep lookups to `max_depth` nodes back, and probably reverse pruning order

All of these cost `O(n)` space to reduce time lookups to `O(1)`.

I favor number 1 as the smallest change from current implementation.

---

As a side note, since this is performance-sensitive, we should not raise an exception so often (in this case: "no nodes available to prune").

**Comment by pipermerriam** [comment]
Maybe this is worth having a small benchmark script for so that we can more easily reason about performance changes to this API.

**Comment by carver** [comment]
Yeah, benchmarking should be part of the deliverable for any PR focusing on performance :+1:

**Comment by cburgdorf** [comment]
Let me echo what I just dropped in the chat:

It would be great to have a performance test that works roughly like this:

spin up too geth nodes, both with a fixed database, both not connected to any other peers except our Trinity node
spin up one Trinity node with disabled discovery and hard wired to these two gethnodes (can use the addPeer API for that)
Run it and measure the time it takes to sync up to the tip of the gethnodes.
Ideally we would have that all wrapped up in a docker image to have a truly stable system. I believe this would give us a very valuable benchmark to improve against. One that takes into account how efficient our networking code runs.

Ideally, we would connect to even more peers but currently it is hardwired to only connect to 2 boxes with the same API to prevent eclipse attacks. We could make that configurable for testing but I guess running too many boxes on the same machine will start skewing the results further from reality.

Does anyone agree that would be nice to have or where that might fall or short or if something else might be better?

**Comment by pipermerriam** [comment]
Conceptually :+1: but I'm hesitant to put much time towards it until we can actually have a client which syncs semi-reliably.

**Comment by cburgdorf** [comment]
@pipermerriam yes, I agree. Just wanted to throw it out to get a quick sanity check on the concept.

**Comment by carver** [comment]
If you feel like being adventurous @veox the branch at #236 should be good to run and significantly faster at pruning. (it's only :x: for linting stuff)
