### ISSUE TITLE
Leaked custom exceptions (e.g. SerializationError) may cause asyncio-run-in-process to crash

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#2023]
As reported in #2000, a leaked `SerializationError` exception crashed the discovery component but failed to cause trinity to stop. That's because that exception cannot be pickled and causes `asyncio-run-in-process` to crash: https://github.com/ethereum/asyncio-run-in-process/issues/28

**Comment by gsalgado** [comment]
Again, this was not really a component crashing but actually a crash in `asyncio-run-in-process` (caused by a python bug): https://github.com/ethereum/asyncio-run-in-process/issues/28

I'll keep this open until we find a way to work around it in `asyncio-run-in-process`

**Comment by pipermerriam** [comment]
@gsalgado can we just fix this the other way around and update `SerializationError` to be pickleable by implementing a `__reduce__` method?

**Comment by gsalgado** [comment]
We could update that (and all other exceptions in `rlp.exceptions`), but there may be other custom exceptions outside of our control that would still cause `asyncio-rip` to crash. That may be our only option, though

**Comment by gsalgado** [comment]
With https://github.com/ethereum/asyncio-run-in-process/pull/29 we get a more meaningful error and the component process terminates, causing trinity to stop
