### ISSUE TITLE
Release naming scheme

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#22]
### What is wrong?

- I love names!
- I especially love named software releases!

But names are hard!

### How can it be fixed

I suggest we continue from the origins of the name "Trinity" and name our releases after badass women.  Maybe we can use this tread to collect some names?

**Comment by cburgdorf** [comment]
https://en.wikipedia.org/wiki/Natascha_Artin_Brunswick
https://en.wikipedia.org/wiki/Yvette_Amice
https://en.wikipedia.org/wiki/Izabela_Abramowicz

**Comment by veox** [comment]
https://en.wikipedia.org/wiki/Lynn_Margulis

More near-contemporary photos are available [on Wikimedia](https://commons.wikimedia.org/wiki/Category:Lynn_Margulis); or historical images all-around, with unstated copyright status (but they do feature microscopes!).

-----

Is there a single-page list of names that have already been used?..

**Comment by cburgdorf** [comment]
>Is there a single-page list of names that have already been used?

It's not on a single page but all releases are listed (with pagination) here: https://github.com/ethereum/trinity/releases

**Comment by cburgdorf** [comment]
https://en.wikipedia.org/wiki/Xia_Peisu (Chinese)

**Comment by cburgdorf** [comment]
@veox I took your Lynn Margulis suggestion for the latest release https://github.com/ethereum/trinity/releases/tag/v0.1.0-alpha.36

**Comment by v9k8** [comment]
> Hah, well I like the Constantinople connection, and would love to use a suggestion from veox, since he contributed so much to the release. But... I am not keen to honor someone who committed heinous war crimes. Any other suggestions, @veox ?

That was wise choice. The topic of Rus' is quite complex and you would bring more pain to your release naming than benefits :D Olga of Kyiv was a regent on behalf of their son Svyatoslav and what she did to Drevlians wasn't just because she was bad, Drevlians killed her husband Igor and she "paid back" with the coin to them.
