### ISSUE TITLE
Make epochs first class citizens and epoch trans at end of epoch

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#235]
### What is wrong?

Spec-PRs:
- Make epochs first-class citizens: https://github.com/ethereum/eth2.0-specs/pull/499
- Epoch trans at end of epoch: https://github.com/ethereum/eth2.0-specs/pull/492

### How can it be fixed
- Move epoch transition to the last slot in the epoch
- Change a lot `slot` to `epoch` (see https://github.com/ethereum/eth2.0-specs/pull/492)

These two goals are twisted together. Ideally, we can start at https://github.com/ethereum/eth2.0-specs/pull/499 and then do https://github.com/ethereum/eth2.0-specs/pull/492 separately, but I suspect it will be harder to review...

**Comment by NIC619** [comment]
What's left from #228 : 
- `slot_to_epoch`
- move `get_current_epoch_attestations`/`get_previous_epoch_attestations` to `state`
