### ISSUE TITLE
Dead fixtures in the codebase

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#237]
### What is wrong?

Found `pytest-deadfixtures` that can detect dead fixtures in the codebase.

```
$ pytest --dead-fixtures

Hey there, I believe the following fixture(s) are not being used:
Fixture name: chain_without_block_validation, location: tests/conftest.py:230
Fixture name: nodekey, location: tests/core/initialization/test_initialize_data_dir.py:27
Fixture name: beacon_chain_without_block_validation, location: tests/eth2/beacon/chains/conftest.py:60
Fixture name: chain, location: tests/eth2/beacon/chains/test_chain.py:24
Fixture name: sample_recent_proposer_record_params, location: tests/eth2/beacon/conftest.py:273
Fixture name: sample_validator_registry_delta_block_params, location: tests/eth2/beacon/conftest.py:329
Fixture name: init_shuffling_seed, location: tests/eth2/beacon/conftest.py:377
Fixture name: init_validator_privkeys, location: tests/eth2/beacon/conftest.py:392
Fixture name: chain_fixture, location: tests/json-fixtures-over-rpc/test_rpc_fixtures.py:380
Fixture name: chain, location: tests/json-fixtures-over-rpc/test_rpc_fixtures.py:388

1 error in 3.01 seconds
```

### How can it be fixed

- Check and remove the dead fixtures
- Maybe add the check to ci, if the check is reliable?

**Comment by ChihChengLiang** [comment]
For eth2 part, `chain`, `beacon_chain_without_block_validation`, `sample_validator_registry_delta_block_params`, `sample_recent_proposer_record_params`, `init_shuffling_seed`, and `init_validator_privkeys` are all manually confirmed dead.

**Comment by carver** [comment]
Nice, I'll remove the eth1 dead fixtures:

 - [x] chain_without_block_validation, location: tests/conftest.py:230   -     seems to be used in:
```
tests/json-fixtures-over-rpc/test_rpc_fixtures.py:388:def chain(chain_without_block_validation):jk
```                                                  
 - [x] nodekey, location: tests/core/initialization/test_initialize_data_dir.py:27                                                    
 - [x] chain_fixture, location: tests/json-fixtures-over-rpc/test_rpc_fixtures.py:380
 - [x] chain, location: tests/json-fixtures-over-rpc/test_rpc_fixtures.py:388 - this and `chain_fixture` seem to be used in:
```
tests/json-fixtures-over-rpc/test_rpc_fixtures.py:401:async def test_rpc_against_fixtures(chain, event_bus, ipc_server, chain_fixture, fixture_data):
```

Well I was optimistic at first, but the false positive rate is kinda high, at 3/4 of detections being incorrect. (unless I'm missing something)
