### ISSUE TITLE
Fix `validate_attestation_aggregate_signature`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#243]
### What is wrong?

https://github.com/ethereum/eth2.0-specs/pull/532/

### How can it be fixed

- Update `validate_attestation_aggregate_signature` in `eth2/beacon/state_machines/forks/serenity/block_validation.py`
- Plus: go through again validate_attestation logic, compare the with the spec to confirm that we didn't miss other new spec changes.

**Comment by ralexstokes** [comment]
i can do this one

**Comment by ralexstokes** [comment]
looking to sync this w/ the spec and it is unclear to me if we are keeping the logic around the custody bit -- iirc it was going to be removed completely from the spec but it seems like it is still partially here -- are we moving ahead of the spec and just leaving those checks out?

@hwwhww @djrtwo ?

**Comment by djrtwo** [comment]
Yup, discussion can be found here -- https://github.com/ethereum/eth2.0-specs/pull/488
We removed stuff that was more likely to change and kept stuff that would require too much reworking between phase 0 and 1

**Comment by ralexstokes** [comment]
@hwwhww talked to @djrtwo and it sounds like per this discussion: https://github.com/ethereum/eth2.0-specs/pull/488 we are going to keep some of it in -- i'll move ahead w/ my edits and we can always modify later if we need to

**Comment by hwwhww** [comment]
@ralexstokes @djrtwo Yes! The latest `dev` branch would be the better reference to clean up the codebase logic. 👍
