### ISSUE TITLE
Remove all custody and VDF placeholders

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#244]
### What is wrong?

See https://github.com/ethereum/eth2.0-specs/pull/488

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by hwwhww** [comment]
pending on #247

**Comment by ralexstokes** [comment]
i can handle this one as well....

it looks like #247 was resolved by #248, right @hwwhww ?

so i'll just go through and remove the custody and VDF stuff -- happy to also handle the renaming in #247 if i missed something :)

**Comment by ralexstokes** [comment]
oh i see you are already assigned -- ignore my previous comment if you are already working on this :)

**Comment by hwwhww** [comment]
@ralexstokes  That's right, #247 and #244 are twisted together and we missed the changes between them. 😱 
I have a WIP PR #250, mind taking a look? (Tests are coming!)
