### ISSUE TITLE
Remove/change xor(seed, epoch) in shuffling

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#257]
### What is wrong?

Spec issue: https://github.com/ethereum/eth2.0-specs/issues/550
Spec PR: https://github.com/ethereum/eth2.0-specs/pull/552

### How can it be fixed

Update `generate_seed`:
```python
    return hash_eth2(
        get_randao_mix(state, epoch - SEED_LOOKAHEAD) +
        get_active_index_root(state, epoch) +
       epoch.to_bytes(32, 'big')
    )
```

Pending on #256

**Comment by ralexstokes** [comment]
looks like this is unblocked so i can address it
