### ISSUE TITLE
Set `GENESIS_SLOT` to `2**32`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#259]
### What is wrong?

Spec PRs: ethereum/eth2.0-specs#505 (master branch, January Release) and ethereum/eth2.0-specs#537 (dev branch)
- Set `GENESIS_SLOT` to `2**32`
### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ralexstokes** [comment]
i'll address this but may wait to see the outcome of our call on thursday in case this changes :)

**Comment by hwwhww** [comment]
Update: now [`GENESIS_SLOT` is `2**32`](https://github.com/ethereum/eth2.0-specs/blob/c4c1903460068aee06152db6efa14e431f8c6e8f/specs/core/0_beacon-chain.md#initial-values). Also need to update `GENESIS_EPOCH`.
