### ISSUE TITLE
Implement all JSON-RPC endpoints

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#26]
Checklist of endpoints to support, and which are supported in master or pull requests

- [x] support all the `web_*` methods
  - [x] `web3_clientVersion` #834
  - [x] `web3_sha3` #836
- [ ] support all the `net_*` methods
  - [x] `net_listening`
  - [x] `net_peerCount`
  - [x] `net_version` #840
- [ ] support all the `eth_*` write methods
  - [ ] make list of methods
- [ ] support all the `eth_*` read-only methods
  - [x] `eth_protocolVersion`
  - [x] `eth_syncing`
  - [x] `eth_coinbase`
  - [x] `eth_mining`
  - [x] `eth_hashrate`
  - [x] `eth_gasPrice`
  - [x] `eth_accounts`
  - [x] `eth_blockNumber`
  - [x] `eth_getBalance`
  - [x] `eth_getStorageAt`
  - [x] `eth_getTransactionCount`
  - [x] `eth_getBlockTransactionCountByHash`
  - [x] `eth_getBlockTransactionCountByNumber`
  - [x] `eth_getUncleCountByBlockHash`
  - [x] `eth_getUncleCountByBlockNumber` block int
  - [x] `eth_getUncleCountByBlockNumber` block string
  - [x] `eth_getCode`
  - [x] `eth_call`
  - [x] `eth_estimateGas`
  - [x] `eth_getBlockByHash`
  - [x] `eth_getBlockByNumber` block int
  - [x] `eth_getBlockByNumber` block string
  - [x] `eth_getTransactionByHash`
  - [x] `eth_getTransactionByBlockHashAndIndex`
  - [x] `eth_getTransactionByBlockNumberAndIndex`
  - [x] `eth_getTransactionReceipt`
  - [x] `eth_getUncleByBlockHashAndIndex`
  - [x] `eth_getUncleByBlockNumberAndIndex` block int
  - [x] `eth_getUncleByBlockNumberAndIndex` block string
  - [ ] ~~`eth_getCompilers`~~ (deprecated)
  - [ ] `eth_getLogs`
  - [x] `eth_getWork`

**Comment by Bhargavasomu** [comment]
@pipermerriam as part of implementing `eth_getTransactionReceipt`, I would like to add a new function `def get_transaction_receipt(self, header: BlockHeader, transaction_index: int, receipt_class: Type[Receipt]) -> Receipt` to `ChainDB`. I feel that this function would be good for the `API`. Please confirm. Thankyou.

**Comment by cburgdorf** [comment]
I believe we can close this for the same reason that we closed #20 (they seemed fairly overlapping) but feel free to reopen in case I misunderstood.

**Comment by carver** [comment]
Yeah, I think the "write" methods were the main difference, and since trinity won't host keys for the foreseeable future, I'm good with closing :+1:
