### ISSUE TITLE
Implement fork choice rule

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#260]
### What is wrong?

Implement LMD-GHOST
Ref:
- https://github.com/ethereum/research/blob/master/ghost/ghost.py
- https://github.com/protolambda/lmd-ghost/

### How can it be fixed

Fill this in if you know how to fix it.

The current STUB fork choice rule is only scoring by block slot number: 
https://github.com/ethereum/trinity/blob/master/eth2/beacon/db/chain.py#L374
We can modify it to an abstract switchable fork choice rule.

**Comment by ralexstokes** [comment]
@hwwhww yep, i'll start on this :)

**Comment by ralexstokes** [comment]
leaving a note to investigate how the codebase reacts to reorgs and orphaned blocks -- unclear we are handling them right now and may be complicated (compared to the pow chain) given that we are in some sense tracking a block tree on top of a 'slot tree'
