### ISSUE TITLE
Consider having LESProtocol methods generate/return request IDs instead of taking them as arguments

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#27]
As suggested in https://github.com/ethereum/py-evm/pull/841#discussion_r192138205

**Comment by Bhargavasomu** [comment]
@pipermerriam I was going through this, and later came to know that the `LESServer` gets a `request` with a specific `request_id` and has to use the function `send_block_headers` to the specific `request_id` of the peer which has made a request. So I think that the design here would be to make the argument `request_id=None` in the `LESProtocol` methods, and only if it is none, we generate the `request_id` in the methods. Is this approach right or am I missing something?
