### ISSUE TITLE
Implement swap-or-not shuffle

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#272]
### What is wrong?
Spec issue: https://github.com/ethereum/eth2.0-specs/issues/563
Spec PRs: 
1. introduce swap-or-not shuffle: https://github.com/ethereum/eth2.0-specs/pull/576
2. max list size in `get_permuted_index: https://github.com/ethereum/eth2.0-specs/pull/634
3. fix out-of-bounds in `get_shuffling`: https://github.com/ethereum/eth2.0-specs/pull/641

### How can it be fixed
1. Add constants: `SHUFFLE_ROUND_COUNT = 90`
2. `eth2.beacon._utils.random.py`
    - Implement `get_permuted_index`: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_permuted_index
    - Implement the optimize version for shuffling the whole validator registry: https://github.com/ethereum/eth2.0-specs/commit/70e482be28a10ca0d37de34fb3a0b5cd94108ad3

p.s. the benefit of #271 refactoring will reduce the cost of adding `SHUFFLE_ROUND_COUNT` to EVERYWHERE.

**Comment by ChihChengLiang** [comment]
Also need to fix this together https://github.com/ethereum/eth2.0-specs/pull/641
