### ISSUE TITLE
Use factoryboy for random object generation in tests.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#279]
### What's the problem?

https://github.com/ethereum/trinity/blob/3a09276d2f21adfc5b233272e1b1cc2ad1a0c11e/tests/p2p/helpers.py#L17-L25

https://github.com/ethereum/trinity/blob/3a09276d2f21adfc5b233272e1b1cc2ad1a0c11e/tests/p2p/test_discovery_v5.py#L22

https://github.com/ethereum/trinity/blob/3a09276d2f21adfc5b233272e1b1cc2ad1a0c11e/tests/p2p/test_kademlia.py#L257-L267

We have multiple implementations for generating random nodes and addresses.  Here's a new one coming in this 

PR: https://github.com/ethereum/trinity/pull/270/files/6af1a64abff48e5e56f7da134c5503653734da2b#diff-7e73dc6326965d5487d2171f23c63beaR59

### How can it be fixed.

We could fix this by just ensuring that we **always** import the one from `tests/p2p/helpers.py` but this is problematic because 

1. I don't think it's a great pattern to be importing across test modules
2. If we extract the `p2p` module from the `trinity` codebase then those imports will break on the `trinity` side.
3. Having to import this utility makes writing tests more cumbersome and boilerplate heavy.

We can fix part of this by moving the utilities into `p2p.tools.helpers`.  This uses our convention of moving non-core utilities into a namespace that can be reliably imported, even by 3rd party libraries.  But this still means that you have to import the `random_node` function in your tests and it doesn't actually give much control over any details such as setting the `address` but randomly generating the public key.

We can fix this by expanding the `random_node` function signature to allow overriding the various fields as optional function arguments.  However, at this point, we've re-created [`factoryboy`](https://factoryboy.readthedocs.io/en/latest/)

So, I propose we establish a convention of using `library.tools.factories` as a standard namespace that houses `factoryboy` based factories for the various objects we want to generate during test runs.

As for reducing the overhead of having to manually import these in each test file...

#### Option 1 - fix import overhead with a fixture

Create a base fixture in `conftest.py` that looks roughly like this.

```python
# tests/conftest.py
from p2p.tools.factories import (
    AddressFactory,
    NodeFactory,
)

class MetaFactory:
    AddressFactory = AddressFactory
    NodeFactory = NodeFactory

@pytest.fixture
def factories():
    return MetaFactory()
```

Then in our tests we can do:

```python
# tests/p2p/test_thing.py
def test_thing(factories):
    node = factories.NodeFactory()  # generates a random `kademlia.Node`
```

#### Option 2 - auto inject access to the factories in tests

> This could be difficult to get right due to **not** wanting to add `factoryboy` as a core dependency but maybe we can get around that with good error reporting.

We could expose the fixture by default using the pytest plugin API

https://docs.pytest.org/en/latest/writing_plugins.html#making-your-plugin-installable-by-others

```python
# p2p/tools/factories/meta.py
from .kademlia import (
    AddressFactory,
    NodeFactory,
)

class MetaFactory:
    AddressFactory = AddressFactory
    NodeFactory = NodeFactory

# p2p/tools/factories/plugin.py

@pytest.fixture
def p2p_factories():
    try:
        import factoryboy
    except ImportError:
        raise Exception("A friendly error message that lets the user know they need to install factory boy")
    from .meta import MetaFactory
    return MetaFactory()

# setup.py

setup(
    ...
    entry_points={
        "pytest11": ["devp2p = p2p.tools.fixtures.plugin"]},
    },
    ...
)
```

With this model, the `p2p_factories` fixture would be available by default, even when installed as a 3rd party library.

**Comment by pipermerriam** [comment]
cc @hwwhww as I think many of the `bcc` helper functions could be cleaned up using this pattern, and similarly I looking at sections like this:

https://github.com/ethereum/trinity/blob/3a09276d2f21adfc5b233272e1b1cc2ad1a0c11e/tests/core/p2p-proto/test_block_bodies_request_object.py#L25-L73

We could do major cleanup, probably removing most if not all of those helper functions.

**Comment by lithp** [comment]
Yeah, this sounds wonderful. I'm too much of a PEP20 fan and I've had to debug ruby too often to like option 2 but option 1 is great :+1:
