### ISSUE TITLE
Use `NamedTuple` instead of `Dict` for Command messages

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#28]
### What is wrong?

We currently are using dictionaries for the `msg` portion for commands like `GetBlockHeaders`.  It's hard to specify types for these, as well as them being inherently mutable structures.

### How can it be fixed

Commands should decode into a `NamedTuple` instead when they have key/value data.

**Comment by Bhargavasomu** [comment]
@carver @pipermerriam I was thinking of something like using a `Metaclass` which would take the `structure` variable in each `Command` subclass and create the `message_class` from the `structure` itself. The only thing that stopped me from doing this automatic `NamedTuple` class generation was that I couldn't dynamically interpret the `sedes` object to the corresponding `data type` unless we have some kind of mapping. For example, we could have a map from `sedes.big_endian_int` to `int` data type. This would make the `CountableList` mapping to a `python data type` bit complex, but still doable.

So should I go ahead with this approach (or) stick on to creating a `NamedTuple class` for each `Command Sub Class`?

**Comment by pipermerriam** [comment]
I see the appeal but I think we should avoid the complexity.  These data structures are **extremely** static and do not change.  Having them explicitely declared seems like it won't introduce code maintenance issues.  Also, givien that we'll likely *need* these data types for type hinting, I don't believe that dynamically generating them will coexist well with our type checker.

**Comment by Bhargavasomu** [comment]
@pipermerriam ok then, since it is clear that every `Command Class` needs a separate `Message Class` inherited from `NamedTuple`, would it be better to have that new class in a separate file or place it just above the `Command Class`?

**Comment by pipermerriam** [comment]
> would it be better to have that new class in a separate file or place it just above the Command Class?

As long as things are easily visually grouped in the code and named in such a way that it isn't confusing I don't have a preference.
