### ISSUE TITLE
Misc renamings round 2

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#282]
### What is wrong?

Spec PR: https://github.com/ethereum/eth2.0-specs/pull/534
💇‍♂️👽💆‍♀️

- [x] penalized -> slashed
- [x] exit -> voluntary exit
- [x] operations -> transactions
- [x] initial, startup -> genesis
- [x] `ChainStart` -> `Eth2Genesis`
- [x] Remove `Number` from custom types 
- [x] `SEED_LOOKAHEAD` -> `MIN_SEED_LOOKAHED`
- [x] `ENTRY_EXIT_DELAY` -> `ACTIVATION_EXIT_DELAY`
- [x] `INCLUDER_REWARD_QUOTIENT` -> `ATTESTATION_INCLUSION_REWARD_QUOTIENT`
- [x] `latest_index_roots` -> `latest_active_index_roots`
- [x] `current_epoch_start_shard` -> `current_shuffling_start_shard`, `current_shuffling_epoch`, `current_shuffling_seed`
- [ ] `MIN_VALIDATOR_WITHDRAWAL_EPOCHS` -> `MIN_VALIDATOR_WITHDRAWAL_DELAY`
- [ ] `MAX_WITHDRAWALS_PER_EPOCH` -> `MAX_EXIT_DEQUEUES_PER_EPOCH`
- [x] `ETH1_DATA_VOTING_PERIOD` -> `EPOCHS_PER_ETH1_VOTING_PERIOD`
- [x] `SLOT_DURATION` -> `SECONDS_PER_SLOT`
- [x] `EPOCH_LENGTH` -> `SLOTS_PER_EPOCH`

### How can it be fixed

Search and replace.

**Comment by ralexstokes** [comment]
i'll knock this out -- be ready for merge conflicts :(

**Comment by hwwhww** [comment]
@ralexstokes You're the hero. 😭 

I'm fixing `MIN_VALIDATOR_WITHDRAWAL_EPOCHS` -> `MIN_VALIDATOR_WITHDRAWAL_DELAY` in #283. It became `MIN_VALIDATOR_WITHDRAWAL_TIME` -> `MIN_VALIDATOR_WITHDRAWABILITY_DELAY`.
