### ISSUE TITLE
Implement sparse merkle tree utils

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#289]
### What is wrong?

current merkle tree utils in `eth2/_utils/merkle` requires all leaves to compute tree root. It will not be practical to use it to compute deposit tree in Deposit contract(which is a sparse merkle tree).

### How can it be fixed
1. Rename the old `eth2/_utils/merkle.py` to `eth2/_utils/merkle_normal.py`
2. Add `eth2/_utils/merkle_sparse.py`

**Comment by djrtwo** [comment]
The progressive merkle results in the same root as the normal merkle right?

**Comment by hwwhww** [comment]
Root is the same, but we no longer be able to get the Merkle proof from the contract. Opened the issue in the spec: https://github.com/ethereum/eth2.0-specs/issues/660
