### ISSUE TITLE
Implement eth_sendRawTransaction over RPC

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#29]
An important component of this is to add a Local Broadcast Transaction Queue

This queue of transactions should exclusively contain transactions that were broadcasted locally (eg~ over json-rpc's `eth_sendRawTransaction`).

The queue should persist across Trinity sessions, broadcast to all peers, and be immune to local transaction pool eviction strategies.

**Comment by lithp** [comment]
Related to #26

**Comment by cburgdorf** [comment]
Should we add this to the beta milestone?

**Comment by carver** [comment]
Yeah, seems like MVP to me, good catch.

**Comment by cburgdorf** [comment]
This landed with #1855 but some of the discussion was moved over to #1887
