### ISSUE TITLE
Test state.finalized_epoch in test_demo.py

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#294]
### What is wrong?

The test in tests/eth2/beacon/state_machines/test_demo.py does not justify or finalize any epochs.

### How can it be fixed

- Need to add correct `epoch_boundary_root` and `justified_block_root` to attestations in `create_mock_signed_attestations_at_slot`.
  - https://github.com/ethereum/eth2.0-specs/issues/652 would be a block for this issue. A workaround is to skip attestations when `slot % epoch_length == 0`
- `assert` epoch processing variables such as `state.finalized_epoch` and `state.justified_epoch`, etc.

**Comment by hwwhww** [comment]
I'm going to investigate it since it's blocking others.
