### ISSUE TITLE
Wrap `bls.verify` into `validate_bls_signature`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#296]
### What is wrong?
The interface of `bls.verify` is defined in the BLS spec and we'd keep it for test vectors. However, there is a common pattern that we call `bls.verify` and raise `ValidationError` if it returns `False`.
For example:

https://github.com/ethereum/trinity/blob/caf9f3886b3577683dfb5d57aad57146856a755a/eth2/beacon/deposit_helpers.py#L39-L54

and

https://github.com/ethereum/trinity/blob/e93f0e38d124e3a6087dd8ce319dc60a3398a32b/eth2/beacon/state_machines/forks/serenity/block_validation.py#L107-L119

### How can it be fixed

1. We can add a `validate_bls_signature` function in `eth2/beacon/validation.py`, so that we don't need to rewrite the error message format everywhere.
2. Add an extra parameter `validator_index: Validator=None`, so that we can print out the validator index corresponding to the given pubkey in error message. i.e., after #295: `def validate_bls_signature(message_hashes: Hash32, pubkey: BLSPubkey, signature: BLSSignature, domain: int, validator_index: Validator=None) -> None`.

**Comment by ralexstokes** [comment]
seems like we did this, right? if so, let's close it :)
