### ISSUE TITLE
Correct titles and social URI links

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#3]
Please open a pull request (or just edit in-place) with your preferred job title as well as correct URIs for twitter/github/whatever ASAP.  Website launch will happen with tuesday's release.

- [x] @gsalgado : https://github.com/ethereum/trinity/blob/master/docs/index.html#L203
- [ ] @cburgdorf : https://github.com/ethereum/trinity/blob/master/docs/index.html#L193
- [x] @carver : https://github.com/ethereum/trinity/blob/master/docs/index.html#L183

**Comment by pipermerriam** [comment]
cc @cburgdorf if you want to make any changes or maybe you did and just didn't check the box.  closing.

**Comment by cburgdorf** [comment]
Yep, forgot the checkbox
