### ISSUE TITLE
Refactor signature hashing to use new unified ssz method

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#304]
### What is wrong?

Spec PR: https://github.com/ethereum/eth2.0-specs/pull/633

### How can it be fixed

**Blocking**: Pending on SSZ https://github.com/ethereum/py-ssz/issues/44.

1. Update `ProposerSlashing` fields
2. Update `ProposalSignedData` fields and rename it to `Proposal`
3. Apply SSZ `signed_root` for signing.

IMO (1, 2) and 3 can be two tasks.

**Comment by ralexstokes** [comment]
(1) and (2) were probably outdated by work in #470.

It looks like we can update which `py-ssz` we are using and then use the inherited `signing_root` :)

**Comment by ralexstokes** [comment]
Looks like #499 will close this. I'll loop back around once it is merged

**Comment by ralexstokes** [comment]
Looks like we did this, closing
