### ISSUE TITLE
Trio as an alternative to asyncio

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#31]
Trio is a third party async library similar to asyncio. According to their documentation

> Trio was built from the ground up to take advantage of the latest Python features, and draws
> inspiration from many sources, in particular Dave Beazley’s Curio. The resulting design is
> radically simpler than older competitors like asyncio and Twisted, yet just as capable. Trio is
> the Python I/O library I always wanted; I find it makes building I/O-oriented programs easier,
> less error-prone, and just plain more fun. Perhaps you’ll find the same.

The main reason why I prelimiarily prefer it over asyncio is that all concurrency is explicit: Parents can spawn child tasks, but only inside a "nursery" context manager. Whenever a nursery is being exited, all child tasks are awaited and all exceptions are collected. In particular, one cannot spawn tasks that just run somewhere in the void like with `asyncio.ensure_future` (whose exceptions may just get ignored if not handled explicitly).

As a result all tasks form an easy to overlook tree, enabling a second neat feature: Cancel scopes. Tasks can have (potentially nested) cancel scopes created with a context manager or inherited from their parent. This seems to fulfill the same functionality as our cancel tokens, but one doesn't have to pass them around explicitly (less clutter, less errors, and due to the task tree structure probably more clear).

The obvious concern is ecosystem adoption: The project is still young. It seems to be [actively developed](https://github.com/python-trio/trio/graphs/contributors) since 1 1/4 years, but mainly by a single developer (although in the last month there have been commits by 8 contributors). It doesn't seem like there are major projects already using it (I don't know of a good way to find them though). Requests is apparently [experimenting](https://twitter.com/kennethreitz/status/974963822682427393) with Trio for their version 3.0. There is a [pytest plugin](https://github.com/python-trio/pytest-trio). A couple of projects are being ported [here](https://github.com/python-trio), including click and PyMySQL. There's also [trio-asyncio](https://github.com/python-trio/trio-asyncio) which apparently allows using libraries written with asyncio support from trio.

On that topic, a relevant quote by the author:

> If you need to ship something to production next week, then you should use asyncio (or Twisted or Tornado or gevent, which are even more mature). They have large ecosystems, other people have used them in production before you, and they're not going anywhere.
>
> [...]
>
> If you want to ship something to production a year from now... then I'm not sure what to tell you. Python concurrency is in flux. Trio has many advantages at the design level, but is that enough to overcome asyncio's head start? Will asyncio being in the standard library be an advantage, or a disadvantage? (Notice how these days everyone uses requests, even though the standard library has urllib.) How many of the new ideas in trio can be added to asyncio? No-one knows. I expect that there will be a lot of interesting discussions about this at PyCon this year :-).

References:
- https://github.com/python-trio/trio
- https://trio.readthedocs.io/en/latest/index.html
- https://stackoverflow.com/a/49485603

(Note: I'm not necessarily advocating to switch to Trio, I just want to make sure that an active and informed decision is made.)

**Comment by pipermerriam** [comment]
@jannikluhn I think you guys should look into using this when you implement the beacon node syncing.

**Comment by jannikluhn** [comment]
Apparently it's not easily possible to embed trio code in an asyncio project. From the [trio-asyncio docs](https://trio-asyncio.readthedocs.io/en/latest/usage.html):

> If you’d like to keep your plain asyncio main loop and call Trio code from it, there’s one small problem: It won’t work. Sorry.

They suggest two workarounds: 1) run trio code in a separate thread or 2) use a trio main loop and run all asyncio code from there in parallel to the trio code. 2) doesn't sound very appealing to me as we would have to replicate all existing plugin/service code. For 1) I'm not sure how well threads fit into Trinity's architecture, but I suspect that this could also create problems.

So I don't think this is a good opportunity to try out Trio as it wouldn't be straightforward and the result would look quite different to a Trio only implementation. Maybe the better way would be to triorize the plugin/service architecture from the bottom up, but allow asyncio services/plugins to run in there.

**Comment by pipermerriam** [comment]
> Maybe the better way would be to triorize the plugin/service architecture from the bottom up, but allow asyncio services/plugins to run in there.

Yeah, a plugin approach might be an ideal isolated testing ground for this.  Going to leave this open just so it remains visible.  We can close it in another 6-12 months if this goes nowhere.

**Comment by carver** [comment]
@cburgdorf @lithp would lahja support non-asyncio interface as well, so we can experiment with trio in an isolated process? I think that's one of the few things that would currently lock an isolated plugin into using asyncio (but just a guess).

**Comment by cburgdorf** [comment]
A short term solution might involve creating something like a an adapter that wraps a lahja `Endpoint` and maybe throws together some of [these helpers](https://trio-asyncio.readthedocs.io/en/latest/usage.html#calling-asyncio-from-trio) to expose trio compatible APIs.

**Comment by veox** [comment]
Can this be closed?..
