### ISSUE TITLE
Problem with definition of `check_proposer_signature`?

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#320]
### What is wrong?

In the function `per_block_transition` (in `.../state_transitions.py`, we take a boolean variable named `check_proposer_signature`. I think this variable is being used in the opposite sense of how it is named.

If `check_proposer_signature` is `True`, then we skip the validation of the proposer signature. If the parameter is `False`, then we do validate the proposer signature. I looked a bit at its uses across the codebase and couldn't add much more to the picture.

### How can it be fixed

If I can confirm the semantics, I would suggest we change the `if not check_proposer_signature:` conditional to `if check_proposer_signature` and patch the existing call sites. (we could also change the name but i would rather make the non-local edits in this case and keep the name).

@hwwhww looks like you were the last to touch this line?

**Comment by hwwhww** [comment]
Agreed!!!
I recalled that was `is_proposer` but was changed to `check_proposer_signature` per 
https://github.com/ethereum/trinity/pull/241#discussion_r252768490, my fault that I didn't reverse `True` and `False` in PR feedback.
