### ISSUE TITLE
Porting BLS module to py_ecc

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#329]
### What is wrong?

As the API in BLS module stabilized, it's time to port it to py_ecc. Better benchmarking and optimization would be easier to work there.

### How can it be fixed

The steps of migration:

1. [x] Port `BLSPubkey` and `BLSSignature` types to eth_typing. The BLS module depends on these two. https://github.com/ethereum/eth-typing/issues/12
2. [ ] Port APIs in `eth2/_utils/bls.py` to py_ecc repo. https://github.com/ethereum/py_ecc/issues/51
3. [ ] On the new releases of eth_typing and py_ecc. Remove `eth2/_utils/bls.py` and use the functions from the packages.

**Comment by hwwhww** [comment]
Note that it becomes higher priority task because the ultra goal is wrapping BLS modules with Cython for performance! https://github.com/ethereum/py_ecc/issues/50
