### ISSUE TITLE
Ability to blacklist peers

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#33]
### What is wrong?

When disconnecting from a peer, some kinds of disconnects suggest that we should not try to reconnect to it later (is peer myself? is it replying with protocol-breaking headers? etc). It would be best to not try to connect to it again later, but nothing is preventing us from retrying.

### How can it be fixed

- Add a peer blacklist
- Check peer against blacklist before trying to connect to it
- Add peer to blacklist for certain kinds of peer failures (like a protocol error)

The blacklist can be in-memory, resetting on every `trinity` reboot.

**Comment by pipermerriam** [comment]
This was added recently.
