### ISSUE TITLE
Discussion: curio vs trio?

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#338]
It has come to my attention that our currently hand-rolled concurrency framework for handling services is subpar, especially around working w/ cancellations. @pipermerriam mentioned one possible improvement here which would be the adoption of the `curio` ([https://github.com/dabeaz/curio](https://github.com/dabeaz/curio)) framework for async IO.  I was looking at the framework and ran across a (slightly?) newer project called `trio` ([https://github.com/python-trio/trio](https://github.com/python-trio/trio)).

I'm wondering if anyone has any thoughts or comments on this approach in general (moving to what seems like a very solid concurrency library) or if anyone has heard anything about `trio` that may help us decide which is worth exploring further. At a cursory glance, it seems `trio` aims to patch up some difficulties found in the usage of `curio` (e.g. avoiding the problem where the `async` keyword spills everywhere, having clearer semantics around what is a cancellable or scheduleable point and what isn't), however given how little experience we all collectively have w/ async APIs I don't know if we have good standards for what works better. (and hence, I'm curious to hear your experiences).

**Comment by pipermerriam** [comment]
I'd like to toss out the idea of building a small plugin with each and seeing what happens.  This gives us some objective experience to base the decision from.

**Comment by hwwhww** [comment]
A long time ago: https://github.com/ethereum/trinity/issues/31
/cc @jannikluhn

**Comment by pipermerriam** [comment]
I'm going with curio sans any objections (but I'm very open to them if anyone wishes to raise them).  I'll plan on starting with the isolated plugins and expanding outwards from there, likely tackling the networking process last.

**Comment by pipermerriam** [comment]
cc @carver @lithp @ralexstokes @cburgdorf  (and @hwwhww and folk.  We'll leave you guys alone while we figure it out and then probably infect your code once we have things mostly figured out)

**Comment by cburgdorf** [comment]
Guess we settled with trio. Closing.
