### ISSUE TITLE
ReadtheDocs builds failing

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#339]
### What is wrong?

ReadTheDocs builds are failing, because `python-snappy` won't install. I can't seem to get root access to install the snappy deb during Circle's setup stage. The config files don't seem to offer an option to install custom libraries.

### How can it be fixed

- Maybe don't install the `p2p` extra (or `python-snappy` in particular), just during the docs build.
- Bigger change, maybe cleaner: stop trying to install any of the extras, and run the doctests in circle instead (I think we can get away with not installing the project on RTD, if we only want to build the docs)

This isn't working (with or without `sudo`): https://github.com/ethereum/trinity/commit/97134e17d04e40ac28d75daf735281dd6f3c5bfe

**Comment by gsmadi** [comment]
Removing `p2p` doesn't seem to fix this since the pip install will fetch all the required packages.

RTD uses docker for the build detailed [here](https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile). As a non root user its just difficult to fiddle around in there to force the snappy install.

Best option here might be your second suggestion and simplify the doc build. Any inclination for installing the Sphinx requirements if doing a simpler build? From a docs.requirements.txt file?

**Comment by gsmadi** [comment]
Submitted a passing doc build fix on #402.

**Comment by carver** [comment]
> Removing `p2p` doesn't seem to fix this since the pip install will fetch all the required packages.

Hah, right, my head was still in the `py-evm` repo where it was optional.
 
> RTD uses docker for the build detailed [here](https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile). As a non root user its just difficult to fiddle around in there to force the snappy install.

Nice, thanks for the link.

> Best option here might be your second suggestion and simplify the doc build. Any inclination for installing the Sphinx requirements if doing a simpler build? From a docs.requirements.txt file?

As @cburgdorf mentioned, this approach breaks autodoc, which is a dealbreaker. Some more options:
1. Do some [setup.py environment check magic](https://github.com/ethereum/trinity/commit/97134e17d04e40ac28d75daf735281dd6f3c5bfe#diff-2eeaed663bd0d25b7e608891384b7298R97) to only include snappy if not in a RTD build, [mocking snappy during autodoc import](https://github.com/ethereum/trinity/pull/402/files#r265592566)
2. Run autodoc locally and commit the built docs, as a step in the release process. Super error prone
3. Wrap python-snappy in an `eth-snappy` that delegates to a specific implementation depending on the environment: prefer `python-snappy` but fall back to an [all-python implementation](https://github.com/ethereum/py-snappy) if the compiled backend is unavailable. This is very similar to what we did with [eth-hash](https://github.com/ethereum/eth-hash) which has been fruitful.

Number 3 is my current favorite, it feels the least hacky. But # 1 would certainly be faster.

**Comment by gsmadi** [comment]
Agreed and agreed. Solution 3 sounds much much better and cleaner. Solution 1 might get the docs back while something more mature like sol 3 can be rolled out. Going to try @cburgdorf suggestion.
