### ISSUE TITLE
Move `eth2.beacon._utils.*` to `eth2._utils.*`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#356]
### What is wrong?

`eth2.beacon._utils.*` was the directory when we were working under `Py-EVM` repo. Now it can be moved to `eth2._utils.*` level.

### How can it be fixed
Move the files, tests, and also fix all the importing path.

**Comment by s0b0lev** [comment]
Looks like it was already moved: https://github.com/ethereum/trinity/tree/master/eth2

**Comment by hwwhww** [comment]
Yep! Thank you @s0b0lev!
