### ISSUE TITLE
Experiment with other databases (e.g RocksDB)

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#36]
At ECDC [RocksDB](https://rocksdb.org/) was mentioned as a [possibly faster](https://www.influxdata.com/blog/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/) alternative to leveldb.

Also comes with [Python bindings](https://github.com/twmht/python-rocksdb)

Another nice property of RocksDB is that it seems to [allow multiple concurrent processes *reading* from the database](https://github.com/facebook/rocksdb/issues/908) which I think isn't possible with leveldb.

**Comment by carver** [comment]
Experimented! Looks like the key issue right now is that opening a read connection gets a static view of the database at open time. A fix for that is in progress by other teams (see #173 ). So we can revisit later.
