### ISSUE TITLE
TODOs for the very basic state transition

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#366]
Trying to re-prioritize it. 

## Goals
1. The most basic state transition - without any transaction/operation
2. Correctness
    * @hwwhww: it's still hard to target at one certain spec release when debugging the spec, but hopefully we can aim at the next release...
3. And then adding attestation transactions/operations into the game

### Trinity

| Issue | Description | PR | Done |
| ------------------------ | --- | --- | --- |
#272 | Implement swap-or-not shuffle | #363 | <ul><li>- [x] </li></ul>
#345 | Fix `validate_attestation_slot` | #352 | <ul><li>- [x] </li></ul>
#343 | Sync with the spec - data structures | #349, #355, #353, #351 | <ul><li>- [x] </li></ul>
#223 | Implement "per-epoch processing - validator registry" section | #314 | <ul><li>- [x] </li></ul>
#284 | Enable RANDAO | #367 | <ul><li>- [x] </li></ul>
#365 | Enable SSZ tree hashing **-> blocking by Py-SSZ issues?** | | <ul><li>- [ ] </li></ul>
#323 | Implement beacon chain state transition `process_exit_queue` | #385 | <ul><li>- [x] </li></ul>
#326 | Implement `eth1_data_vote` processing per block | #375  | <ul><li>- [x] </li></ul>
#259 | Set `GENESIS_SLOT` to `2**32` | #371  | <ul><li>- [x] </li></ul>

### BLS

| Issue | Description | PR | Done |
| ------------------------ | --- | --- | --- |
| #329 | Port to py_ecc + bugfixes | ethereum/py_ecc/pull/52 | <ul><li>- [ ] </li></ul>

### Py-SSZ
https://github.com/ethereum/py-ssz/milestone/1

Please comment if I missed anything. 🙏 

edit: added PR for #259.

**Comment by hwwhww** [comment]
Update: added #259

**Comment by ralexstokes** [comment]
looks like we have done everything here?
