### ISSUE TITLE
Tab-complete CLI options

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#370]
### What is wrong?

My fingers expect tab-complete to work, eg~

```sh
$ trinity --ro
<TAB>
# should auto-complete to:
$ trinity --ropsten
```

Also,

```sh
$ trinity fi
<TAB>
# should auto-complete to:
$ trinity fix-unclean-shutdown
```

This should install automatically, when trinity is installed.

### How can it be fixed

It looks like we can get 90% of the way there with an non-customized integration of:
https://argcomplete.readthedocs.io/en/latest/index.html

(We can close this ticket after merging that basic auto-complete and adding another issue for the remaining 10%)

An example of the remaining 10% might be things like:
- auto-completing network ID from the set of recognized IDs
- only auto-completing genesis files to those with a `.json` ending
- etc

**Comment by s0b0lev** [comment]
@carver I mention in PR that autocomplete require to add  in **~/.bashrc**:
```
eval "$(register-python-argcomplete trinity)"
````
Maybe it is better to mention such instruction in README.md? So user will decide if he wanna add additional configuration.

**Comment by carver** [comment]
Hm, can we make this a part of running `pip install`?

I'm not really familiar with best/common practices here.

**Comment by s0b0lev** [comment]
Yes, we can modify setup.py to include post-install instruction.

The post-install script will add `eval "$(register-python-argcomplete trinity)"` to ~/.bashrc.

I will test this scenario and update PR.

**Comment by s0b0lev** [comment]
@carver I update setup.py, it is possible to install trinity with autocomplete now using:
```
$ python setup.py install
```

Also, I add one more shell command. This command provides one-time activation of argcomplete (user can use argcomplete without reloading shell or source ~/.basrhc command):
```python
subprocess.call('eval "$(register-python-argcomplete trinity)"', shell=True)
```
Autocomplete for `python setup.py install` works well.

Did I miss any installations way?

**Comment by carver** [comment]
Now we're getting pretty specific, so I'll move convo to the PR. I think it's okay for that PR to only work for bash completion, but we should not add a bunch of cruft if the user isn't using bash.

**Comment by s0b0lev** [comment]
Thanks for feedback @carver, I think the main issue here that we force argcomplete library installation.

Here for example how it works in other projects.

There are 3 ways to configure it:

1. **Add documentation step:**
- https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/enable-tab-completion.html
- https://docs.pytest.org/en/latest/bash-completion.html
- https://github.com/regisb/slack-cli/blob/f4b51b3029afcabb0eee64473dde80eedfaf7de7/README.rst#autocomplete

2. **Argcomplete already** [activated globally](https://argcomplete.readthedocs.io/en/latest/#activating-global-completion)

In that case, we can use `# PYTHON_ARGCOMPLETE_OK` in main cli file
This method works if argcomplete 

> The section on Global Completion states that "bash will look for the string PYTHON_ARGCOMPLETE_OK in the first 1024 bytes of any executable that it's running completion for", which is exactly what it does.


3. **Autoconfiguration.**

It is a more complex setup, found it only in azure-cli.

https://github.com/Azure/azure-cli/blob/f06ad2ea8b251030117cae927b532c733babfcfa/scripts/release/debian/build.sh#L43


I think it's not worth to create complexity in installation only for activating tab-complete. 

The best option, in my opinion, is adding a documentation page. 
What do you think?

**Comment by cburgdorf** [comment]
Hey @s0b0lev thanks for tackling this and diving down the rabbit whole. I personally think an entry in the docs should be fine for now. I think this would be a good place to put it.

https://trinity-client.readthedocs.io/en/latest/api/api.cli.html

**Comment by s0b0lev** [comment]
Hi @cburgdorf , I will revert last commits with changes in setup.py and update documentation at api.cli.html

**Comment by s0b0lev** [comment]
Hey @carver PR was merged: https://github.com/ethereum/trinity/pull/768

Are you going to create a new task for the rest of autocomplete stuff?

> - auto-completing network ID from the set of recognized IDs
> - only auto-completing genesis files to those with a .json ending
> - etc

I can continue work on autocomplete stuff.

**Comment by pipermerriam** [comment]
@s0b0lev feel free to continue, if you want to create a tracking issue for yourself for the various individual features that will allow you to update it yourself since you'll have edit rights.
