### ISSUE TITLE
Circular dependency in `p2p.kademlia`

### ISSUE THREAD

**Issue by goshaQ** [ethereum/trinity#372]
### What is wrong?

When importing `p2p.kademlia` module there appears circular dependency between two modules: `p2p.kademlia` and `trinity.config`. That happens because of the following import statement:
```
from trinity._utils.validation import validate_enode_uri
```

Here is an example of output of the error that appears:
```
Traceback (most recent call last):
  File "transaction.py", line 18, in <module>
    from p2p.kademlia import Node
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/p2p/kademlia.py", line 33, in <module>
    from trinity._utils.validation import validate_enode_uri
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/trinity/__init__.py", line 29, in <module>
    from .main import (  # noqa: F401
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/trinity/main.py", line 22, in <module>
    from trinity.bootstrap import (
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/trinity/bootstrap.py", line 21, in <module>
    from trinity.initialization import (
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/trinity/initialization.py", line 8, in <module>
    from trinity.config import (
  File "/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/trinity/config.py", line 35, in <module>
    from p2p.kademlia import Node as KademliaNode
ImportError: cannot import name 'Node' from 'p2p.kademlia' (/home/gosha/workspace/anaconda3/envs/ethereum/lib/python3.7/site-packages/p2p/kademlia.py)
```

### How can it be fixed

Either `validate_enode_uri` method should be moved to the `p2p` package (to the existent `_utils` module), or `__name__` guard should be added to the `__init__.py` file of the `trinity` package.

**Comment by pipermerriam** [comment]
If `trinity` needs this then potentially locate this in `p2p.validation` to keep it within the public API namespace.

**Comment by carver** [comment]
> That happens because of the following import statement:
> 
> ```
> from trinity._utils.validation import validate_enode_uri
> ```

Yeah, with an eye on eventually splitting p2p and trinity, I agree that it is a bug to import trinity from p2p.

It's a type of bug we have tolerated for a while, because there are a long list of p2p API improvements we'd like to make before that split. So cleaning up the "little things" hasn't been top of list.

**Comment by goshaQ** [comment]
I'm not sure how it would be better to resolve this issue...

The simplest solution will be just delete the validation of the uri in `from_uri` method, but doing so I seems to me wrong. Alternatively, the dependency can be removed by moving it to a separate package (like common, idk) or by duplication of the method in some module within `p2p` package (i.e. `p2p.verification`), but again none of them seems to me appropriate. 

Also the import can be hacked by adding path to the `trinity._utils.verification` module to the system path and importing it as a normal module instead of as a sub-module. Or just adding `__name__` guard to the `__init__.py` file of the `trinity` package. But doing so is awkward. And it only partially solves the problem.

Any suggestions?

**Comment by pipermerriam** [comment]
The utility function should be moved to `p2p.tools.enode` (or some other appropriately named module) and then trinity should import from `p2p.tools.<whatever>`.
