### ISSUE TITLE
Spec sync - Meteorite 711

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#379]
Spec PR: https://github.com/ethereum/eth2.0-specs/pull/711

| Issue | Description | PR | Done |
| ------------------------ | --- | --- | --- |
#380 |parent root reconstruction + granular state roots + body/header segregation  | #470   | <ul><li>- [x] </li></ul>
#381 | Merkleization friendly pending attestations | #390| <ul><li>- [x] </li></ul>
#382 |`get_previous_epoch` returns `current_epoch - 1` in all cases  | #469 | <ul><li>- [x] </li></ul>
#383 | Per-epoch processing - Crosslink updates/bugfixes | #390 | <ul><li>- [x] </li></ul>
#384 | Per-epoch processing - Rewards and penalties updates/bugfixes | #390 | <ul><li>- [x] </li></ul>

**Comment by ralexstokes** [comment]
heads up @hwwhww @NIC619 i'm going to update the `SignatureDomain` enum in my PR #397.... seems to fit in w/ the header segregation.

**Comment by ralexstokes** [comment]
and the update the `Transfer` fields

**Comment by ralexstokes** [comment]
i believe we have addressed all the work in this issue -- shall we close this one @hwwhww ?
