### ISSUE TITLE
Review and rework per-epoch processing: crosslink

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#383]
### What is wrong?

Spec Meteorite 711 Pythonized the per-epoch processing, also made the logic much more clear than before. We would need to ensure we are following the correct logic.

### How can it be fixed
Know issues:
- [ ] tie break for `winning_root` favors lexicographically _higher_ hashes rather than lower
- [ ] handle case when no attestations available for a particular shard when crosslinking (https://github.com/ethereum/eth2.0-specs/pull/711/commits/47cca60148dbf74af01ef491e7b58fbac0241b75) (bugfix)

And also, check our codebase is aligning with the spec.

**Comment by NIC619** [comment]
Closed in #390
