### ISSUE TITLE
Review and rework per-epoch processing: rewards and penalties

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#384]
### What is wrong?

Spec Meteorite 711 Pythonized the per-epoch processing, also made the logic much more clear than before. We would need to ensure we are following the correct logic.

### How can it be fixed
Know issues:
- [ ] Inactive slashed validators only pay inactivity penalties until withdrawable (https://github.com/ethereum/eth2.0-specs/pull/711/commits/ec12460b8bae49c2272870b4490039a68f3c4761) (bugfix)
- [ ] handle `get_base_reward` when no previous balance (https://github.com/ethereum/eth2.0-specs/pull/711/commits/02e8e8974049f1965df3f7b0b9b874a46a26c150) (bugfix)

And also, check our codebase is aligning with the spec.

**Comment by NIC619** [comment]
Closed in #390
