### ISSUE TITLE
Trinity client identifier should include git commit ID when in dev mode

### ISSUE THREAD

**Issue by gsalgado** [ethereum/trinity#39]
### What is wrong?

When developing it's important to know the commit ID that was in use on a given trinity run

### How can it be fixed

use the following algorithm to compute version string.

- use `d = pkg_resources.get_distribution('trinity')` to lookup the distribution information for `trinity`

If `d.location` is a git repository, then construct the version string as follows.  The git commit portion can be retrieved using a `subprocess` call to `git rev-parse HEAD`

```
<d.version>-dev.<git-commit-hex-to-8-chars>
"1.2.3-dev-9e977472"
```

If `d.location` is not a git repository, then use `d.version` as the version string.

If the call to `pkg_resources` throws and exception then the `setup_trinity.py` file should be parsed (regex?) for the version string.

```
<version-string>-dev-<git-commit-hex-to-8-chars>
```

**Comment by carver** [comment]
Ref: https://github.com/ethereum/py-evm/pull/1394
