### ISSUE TITLE
epoch transition at start of epoch

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#391]
### What is wrong?

Spec PR: https://github.com/ethereum/eth2.0-specs/pull/732

It seems twisted with #380 

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ralexstokes** [comment]
i started doing this in #397 and will get it all together on `master` :)

**Comment by ralexstokes** [comment]
i have a patch for this: https://gist.github.com/ralexstokes/37f6c3779038705c7795962fd0147c1d

it introduced a bug in the mock attestation utility when we hit an epoch boundary and change the shuffling of the validators... i have not fully debugged but can do so soon.
