### ISSUE TITLE
Trinity chain data sharding

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#40]
### What is wrong?

More than 90% of the hard drive footprint is chain data (headers/blocks/transactions/receipts).

We can both reduce the hard drive footprint as well as the time it takes to sync a node if we only store a subset of the chain data.  This will be referred to as *sharding* the chain data.

### How can it be fixed

The simple concept is for each node to only store `1/N` blocks.  We'll refer to `N` as the `sharding_factor`

Strategies:

- store every other block
- use function `f(block_hash, enode_public_key)` which has an even distribution.

In addition to only storing `1/N` blocks we need to also be able to lazily retrieve blocks as needed for things like the `JSON-RPC` server.

In addition to only storing `1/N` blocks we need to keep a cache of the most recent `X` blocks.  We can start with something simple like `X = 1024`.

**Comment by carver** [comment]
Another approach is pruning, but it has some unsolved problems as well: https://gist.github.com/karalabe/60be7bef184c8ec286fc7ee2b35b0b5b
