### ISSUE TITLE
Fix `cache_state` and `advance_slot`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#410]
### What is wrong?

Spec PR: https://github.com/ethereum/eth2.0-specs/pull/741/
Related to #380 and #391

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ralexstokes** [comment]
i also did this but it is tied up w/ #470.

**Comment by ralexstokes** [comment]
i also did this but it is tied up w/ #470.

**Comment by coreyandersonbuilders** [comment]
Fraud hi- jacked account

**Comment by ralexstokes** [comment]
fixed in #470. closing now.
