### ISSUE TITLE
Use hash_tree_root instead of merkle_root

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#419]
### What is wrong?

Spec PR: https://github.com/ethereum/eth2.0-specs/pull/739

pending on py-ssz and #380.

**Comment by ralexstokes** [comment]
@hwwhww @jannikluhn are there `py-ssz-` updates we need to address this issue that are not covered by #486 (and the implied version of `py-ssz` used in that PR)?

**Comment by hwwhww** [comment]
@ralexstokes I'd say you can go ahead and let's see if #486 or the PR or #409 be merged earlier.
