### ISSUE TITLE
Slot ticker in the beacon-node

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#437]
### What is wrong?

IIUC from the discussion in https://github.com/ethereum/eth2.0-specs/issues/497, a client should maintain a current slot view of the state, rather than updating slot only when a block is received.

So we need a slot ticker somewhere in the codebase that increases the slot number, performs `per_slot_transition`, and updates state every 6 seconds.

Not sure if it makes sense to let the slot ticker have its own service or plugin. It looks like Syncer, RequestServer, and PeerPool all have their own job and thus not the best place for the slot ticker.

#NOTE: probably related to #260

cc @cburgdorf @ralexstokes @hwwhww

**Comment by cburgdorf** [comment]
Maybe it would make sense to have a `SlotTicker` as a service that raises something like a `NewSlotEvent` on the event bus. Different parts of the code base such as sync, request server, attestation pool etc could listen and react upon that event. But I don't think this service needs to run in its own dedicated plugin. It sounds like something that could run in the same process that hosts the sync.
