### ISSUE TITLE
Smoke tests on CircleCI for OSX

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#452]
> We should setup some smoke tests on CircleCI for OSX since I'm pretty sure they offer it as an environment we can test against.

_Originally posted by @pipermerriam in https://github.com/ethereum/trinity/issues/404#issuecomment-473490856_

We shouldn't duplicate all tests, but definitely a couple high-level ones like the cli and wheel ones.

See: https://circleci.com/docs/2.0/hello-world-macos/

**Comment by gsmadi** [comment]
Does trinity use a circleci paid plan?

**Comment by pipermerriam** [comment]
Yes, we run under a paid plan.
