### ISSUE TITLE
DSL for testing asynchronous services.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#454]
Inspired by the tests from: https://github.com/ethereum/trinity/pull/449

### What is wrong?

When we want to test certain code paths in our various classes which handle complex interactions like synchronization it requires a *lot* of hard to maintain code to construct exactly the right situation.

### How can it be fixed

It would be cool if we could describe these sort of synchronization things in a declarative DSL-like language and have a tool that generated code to do the actual logic.  Something like:

```python
test = generate_p2p_peer_sync(
  peer=genesis_peer(<genesis-params>),
  actions=(
    peer_connect(
      new_peer_at(chain_at_height1), 
      capabilities=(serve_headers_through_height_1,),
      disconnect_if=<after-served-header-height-1>,
    ),
    peer_connect(
      new_peer_at(chain_at_height2), 
      capabilities=(serve_headers_through_height_2,),
    ),
  ),
)
```

Really rough sketch with lots of hand-waving but the general idea is to create basic primitives that let us declare a *local* peer that runs the code we want to test, and then define the peer connections it makes and explicit behavior of those peers.

**Comment by cburgdorf** [comment]
I had recently started something in that area but threw it away because I
wasn't happy with the stuff I came up with. 100 % agree something like this
would be valuable.

**Comment by carver** [comment]
Yeah, would be cool to make something like this work.

One hard thing that I don't know how to represent is that we need to constrain the order that internal mechanisms run. So like in the test to replicate [this scenario](https://github.com/ethereum/trinity/pull/449#issuecomment-477262051), we needed the header syncer to collect the headers from the second peer before the body syncer has persisted the headers from the first peer.

Maybe the right thing to do there is to write a database adapter that lets you do funky things like drop or delay writes. :man_shrugging:

**Comment by pipermerriam** [comment]
I'd suggest anyone looking to run with this to look through our existing tests and find as simple an example as possible and try running with that to get things started and then we can start addressing more complex use cases once the base concepts have been established.

Agreed that it gets a lot more complex once we need to enforce event ordering within existing async code.
