### ISSUE TITLE
Hive Integration

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#46]
### What is wrong?

Trinity is not included on hive tests: http://hivetests.ethstats.net/

### How can it be fixed

Information on where to get started:

- See https://github.com/karalabe/hive/blob/master/README.md
- Here's the old pyethereum integration: https://github.com/karalabe/hive/tree/master/clients/pyethereum:develop
- Here's how geth integration looks: https://github.com/ethereum/hive/tree/master/clients/go-ethereum_master

One dockerfile, and one shellscript to init, load blocks, and start rpc services.
The shellscript translates env vars into client-specific configuration

(Info courtesy of @holiman and of course, karalabe)

**Comment by xiaods** [comment]
Is this bounty still open ? I'd love to help with it

**Comment by xiaods** [comment]
hi owner, i will working on it asap. see the approve message right now.

**Comment by carver** [comment]
I think @voith was interested in taking a look, but I'm not sure if he's able to now.

**Comment by voith** [comment]
Yes, I was planning to work on this from next week? @xiaods Do you mind if I take this over?

**Comment by xiaods** [comment]
@voith go on, buddy.

**Comment by cburgdorf** [comment]
Noting that Trinity does support `export` and `import` commands these days which are compatible with `geth`'s so that should make this ticket more approachable now.

I'm going to assign it to me to take ownership but that should not stop anyone who really wants to work on this on grabbing it anyway (just leave a comment here if you plan on tackling it).

**Comment by voith** [comment]
@cburgdorf Please take this over! I don't get enough free time these days to work on this.

**Comment by cburgdorf** [comment]
@voith No worries! But also @xiaods if you are still interested in doing this you should feel free to do so. I basically just assigned myself as in "I'm going to take responsibility for getting this done" but it doesn't necessarily need to be me coding it. I have other things queued up but I'll tackle it if no one else does.
