### ISSUE TITLE
Fix circular dependency when embedding block roots in state by using `signed_root`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#466]
### What is wrong?
Spec PR: https://github.com/ethereum/eth2.0-specs/issues/797
Spec issue: https://github.com/ethereum/eth2.0-specs/pull/816

### How can it be fixed

Fill this in if you know how to fix it.

**Comment by ralexstokes** [comment]
i'm tackling this as part of addressing the work in #397

**Comment by ralexstokes** [comment]
fixed in #470.
