### ISSUE TITLE
Corrupted compressed block contents crashes chain syncer (both fast and full)

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#494]
* trinity Version: trinity-v0.1.0-alpha.20-840-g3b52bdee (current `master`, commit 3b52bdeef6e145f9d079de1dfdf0e246bcf62b54)
* OS: Arch Linux
* Python Version (python --version): 3.7.3
* Environment (output of `pip freeze`): [in gist](https://gist.github.com/veox/4c6e69aad14f652e63716c5ab63f0cac#file-1-pip-freeze-txt)

Run as:

``` sh
trinity --ropsten --max-peers=5 --log-level=DEBUG --preferred-node $DATNODE
```

### What is wrong?

After the error is encountered, `trinity` does not retry the data chunk (i.e. doesn't recover to normal operation), but also does not stop its processes.

[DEBUG output in gist](https://gist.github.com/veox/4c6e69aad14f652e63716c5ab63f0cac#file-0-trinity-ropsten-log-py).

First time I see this.

### How can it be fixed

Haven't investigated.

**Comment by carver** [comment]
Yikes, so I have no idea what to do if leveldb is corrupted. I think we just have to tell the user to dump the whole db and try again.

As for things continuing to run, it looks like fast sync ended, and we have a weird thing where fast sync ending just rolls over into regular sync. I think we've talked about having a service exit code (since the caller who started the service can't currently tell if it ended cleanly), but I can't find an issue for that. So this issue can serve as a reminder.

**Comment by veox** [comment]
Had this happen on regular sequential full-sync, too, so edited title.

-----

Telling the user to dump DB and start from scratch isn't very helpful, I'm afraid. This forces the node operator to either make manual DB backups (somewhat wasteful) or run several nodes behind a load-balancer (wasteful for many use cases and operationally complex).

The issue would "solve itself" (in a sense) if historic snapshots are available (during full-sync; not really considering fast-sync anymore); a roll-back could then be performed, theoretically.

**Comment by pipermerriam** [comment]
Given that this is a leveldb database issue I'm not quite sure how to come at this.  ideally we need a way to reliably reproduce this error so we can know why it happens.  Any chance you've recently updated your version of `plyvel` or `libsnappy` or your system `leveldb`?  can you pull those versions as well for us?

**Comment by veox** [comment]
I think the corruption in both cases happened due to system lock-up on restore-from-suspend, with `trinity` not safely terminated.

Surely was the case the first time around; not sure about the later one.

-----

System packages:

* `snappy` is v1.1.7 and hasn't been updated since 2017-12-02;
* `leveldb` is v1.21 and hasn't been updated since 2019-04-04 (before this issue was opened);
* `python-plyvel` not installed system-wide.

Virtualenv Python packages `python-snappy` and `plyvel` are same as in [OP-linked gist](https://gist.github.com/veox/4c6e69aad14f652e63716c5ab63f0cac#file-1-pip-freeze-txt) and haven't changed since then.

**Comment by pipermerriam** [comment]
:+1: hoping to address the dirty shutdown issue with our conversion to curio and dropping the multiprocess-based object sharing for our database in the near term future.

**Comment by carver** [comment]
> Telling the user to dump DB and start from scratch isn't very helpful, I'm afraid. This forces the node operator to either make manual DB backups (somewhat wasteful) or run several nodes behind a load-balancer (wasteful for many use cases and operationally complex).

Oh yeah, for sure it's a terrible thing to tell operators. I'm just not sure it's something that makes sense to fix 

> The issue would "solve itself" (in a sense) if historic snapshots are available (during full-sync; not really considering fast-sync anymore, in light of issue #511); a roll-back could then be performed, theoretically. Possibly relevant py-evm issue: ethereum/py-evm#1759

I'm not even sure that leveldb snapshots will work if it's corrupted that badly

https://github.com/wbolster/plyvel/issues/8#issuecomment-17480039

Maybe something busted in snappy? ^
