### ISSUE TITLE
No simple way to use preferred peers only

### ISSUE THREAD

**Issue by veox** [ethereum/trinity#501]
* trinity Version: trinity-v0.1.0-alpha.20-840-g3b52bdee (current `master` at commit 3b52bdee).
* OS: Arch Linux
* Python Version (python --version): 3.7.3
* Environment (output of `pip freeze`): [in gist](https://gist.github.com/veox/ab0be400c4565e62c1331b10628c0d91#file-pip-freeze-txt)

### What is wrong?

I'd like to fast-sync from another node also under my control. Naively:

``` sh
trinity --ropsten --port=$PORT_TRINITY --log-level=debug \
    --disable-discovery --max-peers=1 --preferred-node $ENODE_GETH
```

This doesn't work:

1. Entries from previous runs are still in the peer DB, at `~/.local/share/trinity/ropsten/nodedb-eth1`.
2. Bootnodes are still in the viable peer list, via [`p2p/constants.py`](https://github.com/ethereum/trinity/blob/3ad7f02cf5b89d155160f3daa85a21753c9b68c7/p2p/constants.py#L85).
3. Inbound connections are still handled.

To work around, one can:

1. Remove the peer DB.
2. Comment out the bootnodes.
3. Close the port via firewall to all IPs but the preferred peer's.

... but this is a lot of busywork.

-----

Another issue is the fact that if no preferred peers are specified, then there's a "default preferred peers list" (in [`trinity/constants.py`](https://github.com/ethereum/trinity/blob/3ad7f02cf5b89d155160f3daa85a21753c9b68c7/trinity/constants.py#L57)).

I'd argue this violates the principle of least surprise to node operators: "no preferred peers" should mean just that: there is _no_ peer preference.

Also, this puts a strain on those "preferred by default" nodes, some of which are also in the bootnodes list. This is not what bootnodes are for!

### How can it be fixed

Not sure. Introduce `--preferred-only`?..

But take also into consideration:

* #440 - Decouple "preferred" from "discovery".
* #24 - Maintain updated pool of recommended peers.

**Comment by pipermerriam** [comment]
I think I'd split responsibilities up as follows.

- New flag: `--peer-backend`.
    - Can be provided multiple times or maybe with a comma separated list of values
    - `--peer-backend discovery-v4`: enables the v4 discovery protocol
    - `--peer-backend discovery-v5`: enables the v5 discovery protocol
    - `--peer-backend static`: enables the static peers API (previously known as preferred peers)
- `--disable-discovery`: becomes an alias for: `--peer-backend discovery-v4` (or maybe v5)

This isolates the concept of "how do I find out about peers" and fits in well with this: https://github.com/ethereum/trinity/pull/496

Next, we isolate the idea of "bad peer tracking".  Maybe to start we do something like:

- `--peer-tracking`
    - `disable` disables this mechanism, swapping in the [`NoopPeerInfo`](https://github.com/ethereum/trinity/blob/master/p2p/persistence.py#L66) backend
    - `memory` could use a new *in memory only* database that only persists for the lifetime of the node.
    - `sqlite3` (default) would use the SQLite3 database of peer history.

Next we isolate the issue of incoming connections.

- `--allow-inbound-connections` or `--forbid-inbound-connections` as mutually exclusive options which determine whether we open the listening service.

**Comment by carver** [comment]
> * `--disable-discovery`: becomes an alias for: `--peer-backend discovery-v4` (or maybe v5)

I didn't follow this. I think `--disable-discovery` would be `--peer-backend static` in this model, no?

I assume that the previously connected peers would only be tried again on restart if `discovery-v*` is enabled.
