### ISSUE TITLE
Redesign a config API and replace Eth2Config with it

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#503]
### What is wrong?

In Eth2Config, we use Namedtuple to 

1. Create a class defining some required fields of properties, and 

```python
Eth2Config = NamedTuple(
    'Eth2Config',
    (
        # Misc
        ('SHARD_COUNT', int),
        ('TARGET_COMMITTEE_SIZE', int),
        ...
    )
```

2. then create the object specifying the desired value

```python
SERENITY_CONFIG = Eth2Config(
    SHARD_COUNT=2**10,
    TARGET_COMMITTEE_SIZE=2**7, 
    ...
)
```

Namedtuple serves the purpose well, but it's really difficult to change the value of the config object. One way to do this is by using the private method of Namedtuple, which might be a bad practice.

```python
NEW_CONFIG = SERENITY_CONFIG._replace(
    SHARD_COUNT=10,
)
```

One of the methods this new API could provide is `copy`

```python
NEW_CONFIG = SERENITY_CONFIG.copy(
    SHARD_COUNT=10,
)
```

### How can it be fixed

- Create the new API
- Replace Eth2Config with it.

**Comment by ralexstokes** [comment]
Closing due to staleness.
