### ISSUE TITLE
Figure out generic API for finding an available peer for a given request type.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#51]
### What is wrong?

We have some version of this pattern in place in multiple places across the codebase where we need to distribute requests across multiple peers while enforcing some set of requirements:

- only peers without active requests
- only peers who's `HEAD` total difficulty is above a certain low water mark.
- prefer high throughput peers (not implemented anywhere yet)
- only `ETHPeer` peers for many types of requests.

### How can it be fixed

The exact way that this gets implemented is yet to be figured out, but I suspect the round trip request/response API that's been recently implemented will play a part.

**Comment by carver** [comment]
This is a small step on the way there:
https://github.com/ethereum/trinity/blob/76276d586f5a365acdf79d8b7e823b607ea419a9/trinity/sync/common/peers.py#L24-L28
