### ISSUE TITLE
Justification is not persisted in the `BeaconChainDB`

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#523]
This is a bit of an issue meant for discussion as I figure out the best way to introduce the fork choice rule to the beacon chain, which touches on a number of issues relating to getting a "minimum viable testnet" node.

### What is wrong?

An instance of the Beacon node will receive blocks from the network (and possibly ones we create as a proposer). These blocks are passed to an instance of the `BeaconChain` class and processed by its method `import_block`.

This method delegates to some internal machinery, producing the state after applying the operations in this block and persisting the block, the new state and running the fork choice to yield the extension to the canonical chain.

It would seem that there is important data in the resulting state that we are not incorporating into the `BeaconChainDB`, namely the resulting justification data produced as a result of the beacon chain state transition.

We will need to incorporate this data if we expect the node to function properly :)

### How can it be fixed

My recommendation is to add another property we track like the `finalized_head`, namely the `justified_head`, which is the justified block of the greatest epoch we have produced via the state transition of valid blocks (starting from genesis). It seems feasible to compute the justified head on demand via the appropriate state but unless we are worried about the volume of DB writes I think it will make it simpler to go ahead and materialize this field in the DB.

When we import a block, we produce the resulting post-block state and both data should be saved to the DB. Right now (pending #522), we will only save data we know are valid to the DB. In this case, we can write the data unconditionally.

I would suggest we go ahead and at this time compute any updates to the latest {finalized, justified} head and also write them to the database.

**Comment by pipermerriam** [comment]
With journaling/batching mechanisms you can make some trade-offs between having data "appear" to be written to the database in exchange for some level of boosted complexity in reasoning about the database itself.

I.E. write information to the database that you may not be entirely sure about yet but only actually persisting through to the underlying database at specified checkpoints once you know that data is *good*.

**Comment by carver** [comment]
Yeah, this sounds a whole lot like how you sometimes want to generate/access the state root without necessarily persisting it to the DB.

**Comment by ralexstokes** [comment]
thanks @pipermerriam @carver 

it sounds like we can look into these more complex mechanisms if we have issues around performance, like in the case that we want to track some head but not actually write it until we know more about the network state.

in this case, it seems that the justification property i'm referring to is monotonic in the sense that we are fine to go w/ the justified block at the highest slot...

not sure if it was clear above, but it is a concern if we have to do more dynamic management of tracking the justified head (and atm it seems like we dont!). this being said, these are good pointers to keep in mind in case we do need it for any future perf :)

**Comment by ralexstokes** [comment]
Fixed in #547.
