### ISSUE TITLE
Combine `PeerPool.is_valid_connection_candidate` with the peer backend system

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#526]
### What is wrong?

The `PeerPool.is_valid_connection_candidate` method is called by the server to determine whether to allow an inbound connection.  This mechanism seems very similar/related to the peer backend system and the peer tracking system.  It seems they should be combined.

### How can it be fixed

This combination only makes sense after the current refactors to the peer tracking are concluded, but look into combining these into a single API.

**Comment by carver** [comment]
This interesting case popped into my head: if we have marked a node as giving us a `TooManyPeers` failure, then we skip it when making outbound connections. But if it tries to make an inbound connection, then it seems like we should allow it. Just want to make sure that keeps working after a refactor.
