### ISSUE TITLE
Tracking issue for Curio migration

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#548]
Currently just a brain dump of desirables.

- new curio based service abstraction.
    - recreate concept using composition (service runner, service logic)
    - `curio.TaskGroup` looks like our coroutine management mechanism from within a service.  Seems to provide all or almost all primatives we need out-of-the-box.
    - services should be able to be written in isolation, but chained into a hierarchy using intuitive API
    - try to ensure that `ServiceA` waiting on `ServiceB.some_method()` which ends up raising a cancellation error when `ServiceB` is cancelled does not cancel `ServiceA` *accidentally*.

**Comment by ralexstokes** [comment]
building a thread to #338.

**Comment by pipermerriam** [comment]
* `lahja` dependence on `asyncio` is going to also have to be dealt with.

**Comment by cburgdorf** [comment]
We settled with trio and I guess we've also already moved past this stage. Closing.
