### ISSUE TITLE
Concurrent chain data and state sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#55]
### What is wrong?

Currently we *first* sync the chain data (blocks, receipts, etc) and then sync the state trie.  This approach won't reliably work for doing a full sync of the chain because:

- State sync currently takes around 5-10 days
- The state root which it syncs against is static
- Geth (and probably parity) garbage collect old state tries (geth defaults to only keeping state data for 128 blocks)

This means that unless trinity happens to be connected to a node running in archive mode (extremely rare) that by the time it completes the state sync there will be missing trie nodes which will not be available from most any peer it connects to.

And **even if** trinity happens to be connected to an archive node, in order to hit the necessary performance numbers for Trinity to be viable, we will need to process these two syncs concurrently.

### How can it be fixed

An initial exploratory attempt can be found here: https://github.com/ethereum/py-evm/pull/1231

Running the two sync processes concurrently is reasonably easy to do, however, the problems that need to be solved are related to how we orchestrate these two sync processes.

### HEAD tracking

See: https://github.com/ethereum/trinity/issues/54

We need a reference to the HEAD chain header that we are syncing towards.  

- For chain data sync, this merely acts as an anchor for when we have fully synced.
- For state trie, we use the `state_root` as our sync target.

Currently the chain data sync updates the target but the state trie sync does not.   We need to address the security issues laid out in #1233 as well as implement a mechanism for the state sync to update the `state_root` that it is targeting.

### Decouple header and body syncing

> This isn't exactly required, however I believe it will make this easier to manage.

Currently chain data sync syncs headers and bodies together.  This should be separated such that we sync the full header chain **ahead** of the block bodies, effectively making it into two sync processes.

- One process which syncs only the headers (akin to light sync)
- Another process which syncs the bodies.

By moving the header sync into a dedicated process we can institute the head tracking in that process and then cue off of the current target HEAD in the block body and state trie sync.

### Updating the target `state_root`

A naive approach for updating the `state_root` is to simply abandon the previous syncer and start a new one.  This however is likely to incur potentially significant performance overhead since it will require re-walking the entire state trie.

Intelligent updating of the state root would ideally involve 

- preserving all of the `SyncRequest` objects that are still valid for the new state root
- discarding all of the `SyncRequest` objects which are no longer valid **and** removing their entries from the database.

Due to the overhead we also cannot migrate to a new state root on every block.  Since go-ethereum garbage collects trie nodes after 128 blocks, it is likely appropriate to only migrate to a new target state root at around that interval.

### Coordinating chain and state sync

Once we have a reliable way for both chain data and state trie sync to update the targets they are syncing towards, we need a mechanism to synchronize these two processes, i.e, ensure that both sync processes are syncing towards the same target.

Since updating state sync incurs overhead we likely need to only update the sync target every 128 blocks.  This means that both state sync and chain data sync will need to be able to pause if they catch up to the sync target and to only resume *if* the other process does not also complete before the next update.

For the chain data at least, once it has caught up to the sync target we **should** be able to continue to download the chain data but to cache it in memory, only processing it once the sync target has been updated which would allow chain data sync to catch up faster than trie data sync.

**Comment by lithp** [comment]
Re updating the `state_root`, I think it'll be possible to rebase every time a new block comes in.

I just hacked a `SingleAddressStateSync` which replaces `StateSync` and only traverses the nodes required to reach a single address. I've let it sit for a while and re-crawl on every new block, and done that against a few different addresses.

Most addresses are 6 nodes deep into the tree, and after each new block typically just the first two nodes change before we reach a part of the tree which stays fixed. Here's an example, each line is the hash of the nodes on the path from sequential state roots to the target address:

```
['0x3e0a4eb96c2c', '0x463f4f58ce29', '0x7297230ce302', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0xc0cd81f8ba64', '0x463f4f58ce29', '0x7297230ce302', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x8a60fd22517f', '0x63375261f1e2', '0x07751d684e98', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0xad2852bb6bf9', '0x63375261f1e2', '0x07751d684e98', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x3a2ff139b7d1', '0x9df2d17cee15', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x3a2ff139b7d1', '0x9df2d17cee15', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x5eff0bc161c2', '0x9df2d17cee15', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x9e127afcf60b', '0xe78498a70cab', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0x0c46b62d030f', '0x40ffce60e5af', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0xfacb1c415847', '0x40ffce60e5af', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
['0xcf5eb317970d', '0x40ffce60e5af', '0xa0c6379eaf2c', '0xb9dc0d181c75', '0x564704b9b6e7', '0xa5d7a19ea1ca', '0xbdf6ff80df0b']
```

It's possible I just found a quinescent part of the tree, and this is a very rough estimate, but if on average just the top two layers change that's 256 nodes. Fetching 256 nodes is relatively fast, and almost all of the rest of the tree stays fixed between blocks, I think it should be possible to update the state root every time a new block comes in. If the StateDownloader were to optimistically keep crawling every part of the tree which is was already crawling, and only prune branches once it discovers that a branch is out of date, I think almost no work would be wasted.

I don't think it'll be hard to create a `TreeDiffStateSync` which diffs each subsequent state tree against each other and reports how many nodes changed between each block. I think I'll try that next.

**Comment by lithp** [comment]
This also gave me an idea, something like `TreeDiffStateSync` would make it possible to start verifying blocks as if trinity was running a full sync, but without needing to download the entire state tree first.

This could be useful for more easily performance testing trinity against the transactions which are happening right now.

Or it might be helpful for making the transition between `FastChainSyncer` and `RegularChainSyncer`. Instead of atomically switching from one to the other there could be a period of time during which they both run.

**Comment by pipermerriam** [comment]
@lithp I think your last comment points in a direction I've been thinking about.  I'll call it "FigureItOutAsWeGoSync".

Basically, let fast sync happen in the background.

When we get a new block, execute it against the previous blocks state root (which we do not have).  This execution uses a special account database which fetches trie nodes lazily as it finds they are missing.  This would mean we are simultaneously backfilling all the state values that are not changing **and** filling in any new state trie nodes and effectively keeping up with the HEAD of the chain.

Another way to think about this is as a hybrid light/full mode which exposes full node functionality even before the chain is fully synced.
