### ISSUE TITLE
Beacon chain testnet 2

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#562]
### What is wrong?

With #488 finished, goals defined in #438 are mostly achieved.

In this stage, we can target that validators can send attestations and keeps them in an attestation pool, and thus enabling the rewards/penalties calculation and state finalization.

### Tasks in this stage

- [ ] before #533, proposer self creates other validators attestations (the proposer has all the keys 😈) . Disable bls verification if necessary.
- [ ] #533 Store `Attestations` into an `AttestationPool`

... to be updated

### Tasks not in this stage

- Maintaining an Eth1 chain at this stage

**Comment by ralexstokes** [comment]
can we close this issue? not sure if its still relevant w/ the latest we have going on

**Comment by NIC619** [comment]
Yes I think these two tasks are completed. Closing.
