### ISSUE TITLE
Snappy compression

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#57]
### What is wrong?

Based on a note within the AllCoreDevs channel snappy compression may be manditory very soon.  

### How can it be fixed

We'll need to implement compression/decompression in our networking layer.

#### Requirements

- Need to do content negotiation upon connecting to a peer to determine whether they support compressed messages.
- For peers that support this, **all** messages should be considered compressed, and receipt of a non compressed message should be considered an error case.
- For peers that **do not** support compression, receipt of a compressed message should result in an error.
- Must be compatible with however geth & parity do things.

**Comment by Bhargavasomu** [comment]
I'm taking this up.

**Comment by veox** [comment]
This can be closed.

(Implementing PR had stray word between keyword and issue number.)

**Comment by pipermerriam** [comment]
Fixed in #108
