### ISSUE TITLE
Rate limit inbound peer requests

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#573]
### What is wrong?

(This may be a duplicate but I wanted to write it down)

We need to impose some limits on requests that our peers make to us.

### How can it be fixed

Needs some thought and experimentation but:

- For LES which isn't a high priority right now, we might need a quota based system
- For all requests we should limit how much time we are willing to spend generating a response and return impartial responses when that time limit is hit.
- High level stuff like disconnecting from a peer who makes redundant requests, asking for the same `header/receipts/etc` multiple times after we've already given them what they asked for.

**Comment by carver** [comment]
> * High level stuff like disconnecting from a peer who makes redundant requests, asking for the same `header/receipts/etc` multiple times after we've already given them what they asked for.

Disconnecting might be a little harsh for this activity, but maybe rate-limiting or responding with empty results. (or maybe even just continuing to serve unless the node is overall strained) -- I've certainly done this quite a bit with locally testing two nodes, where I sync, wipe the DB, and reconnect to sync again.

**Comment by pipermerriam** [comment]
:+1: to using a soft/forgiving approach (at least to start with)  empty responses seems appropriate.
