### ISSUE TITLE
Tracking: Libp2p client daemon tests are broken

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#575]
### What is wrong?

The libp2p daemon client tests intermittently fail in the CI.

It is hard to repeat these failures locally which suggests the CI environment is presenting some resource constraints that aren't immediately obvious. These client tests should be tolerant to any of these environments.

We have temporarily disabled the tests to unblock others working on unrelated parts of this repo. This issue is a tracking issue to ultimately re-enable the tests.

### How can it be fixed

Need to debug the client daemon bindings to see why/how they are failing.

**Comment by mhchia** [comment]
Thanks for opening this tracking issue 👍

**Comment by carver** [comment]
If this issue starts to get stale, then we should probably just skip the specific flaky tests rather than the whole module (and maybe skip only if running in CI). Of course, it's all moot when the tests are no longer flaky. :)

**Comment by ralexstokes** [comment]
@mhchia we got rid of the daemon bindings (in favor of `py-libp2p`), correct? if so, we can just close this issue

**Comment by ralexstokes** [comment]
closing as we no longer are using the libp2p daemon client
