### ISSUE TITLE
Implement ENRs

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#583]
### What is wrong?

First step of implementing discv5 is implementing the ENR format. The spec can be found [here](http://eips.ethereum.org/EIPS/eip-778).

### How can it be fixed

Add a class representing ENRs with methods to

- create them based on a set of key-value pairs
- sign them
- validate their signature
- get values by key
- compare sequence numbers of two records

Add an RLP sedes object to serialize/deserialize them. We can probably not just use `rlp.Serializable` as the number of fields isn't fixed.

**Comment by carver** [comment]
Related issue: support for sedes of objects with variable field length https://github.com/ethereum/pyrlp/issues/112
(no active work currently, but curious for input on the API)
