### ISSUE TITLE
Rename `Peer.inbound`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#589]
### What is wrong?

https://github.com/ethereum/trinity/blob/9608a54c9985f60a32278b3115754f5fadf0cb6e/p2p/peer.py#L233

This property violates what I consider standard naming scheme for booleans.  Should be one of

- `is_inbound`
- `is_dial_in`

### How can it be fixed

- Decide which is better and update the codebase to use this terminology consistently. 
- Create a computed `@property` for the inverse (`is_outbound` or `is_dial_out`).

**Comment by carver** [comment]
Is this talking about a general property of the peer, or the way in which they connected this time? There might be times where the difference matters. The first time we connect to the peer, it's always the same. I'm imagining names like `is_inbound` and `was_discovered`. So on the first connection to a peer, this is always true:
```py
assert peer.is_outbound == peer.was_discovered
assert peer.is_inbound == not peer.was_discovered
```

But if we discover a peer and then they disconnect and connect back to us, we would have:
```py
assert peer.is_inbound == True
assert peer.is_outbound == False
assert peer.was_discovered == True

**Comment by pipermerriam** [comment]
I was talking about the simple first concept.  For the later it would imply that the peer database was a first class citizen and I have trouble thinking about it that way at this time but conversely, I agree that it would be a useful property.

**Comment by cburgdorf** [comment]
`was_discovered` seems to imply that all peers that *we connect to*  are candidates that came through the discovery which doesn't have to be the case. What if I used `--preferred-node` or the CLI to manually add the node.

If this is just a statistical information maybe something like `origin` represented as an enum would fit better?

```python
class PeerOrigin(enum.Enum):
    Discovery = 0
    External = 1
    Manual = 2
```

**Comment by pipermerriam** [comment]
Side note, with the new peer backend system, the entire preferred nodes system is ready to be extracted from the discovery mechanism.

**Comment by carver** [comment]
> What if I used `--preferred-node` or the CLI to manually add the node.

Yeah, I'm actually pretty comfortable calling `was_discovered=False` for an explicitly defined (preferred) node.

> If this is just a statistical information maybe something like `origin` represented as an enum would fit better?

Not opposed to this approach though, at first glance (apart from some name nitpicks on the enum, which we can bikeshed later).

**Comment by glaksmono** [comment]
> Decide which is better and update the codebase to use this terminology consistently.

Noticed that `inbound` has been used everywhere else in the codebase, and I thought of using `inbound` instead of `dial_in`. Thoughts?

**Comment by pipermerriam** [comment]
Anyone else have a strong preference.  I'm inclined towards `is_dial_in/is_dial_out` as I think they carry more semantic meaning than `is_inbound/is_outbound`.

**Comment by carver** [comment]
> I'm inclined towards `is_dial_in/is_dial_out`

Seems fine. Could also use `dialed_in` and `dialed_out` to avoid a couple underscores.

I still like the focus on the original discovery mechanism, like the `PeerOrigin` idea, but that can diverge from the current flag defining whether the peer `dialed_in`.

**Comment by pipermerriam** [comment]
@carver :+1: I am inclined to separate that like you said into `peer.origin` which I think would need to be some sort of `Enum` or at least a known set-like thing of values.
