### ISSUE TITLE
Remove hack around cancelling lahja streams

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#60]
### What is wrong?

We currently maintain this hack:

https://github.com/ethereum/trinity/blob/f61a48672fd5508fd86cd6868652750d8fcd59d2/p2p/peer.py#L771-L779

### How can it be fixed

We can get rid of this as soon as a new lahja release lands that supports cancelling async generators properly

**Comment by carver** [comment]
Done:
https://github.com/ethereum/trinity/blob/2deb0183b9265ca0f7b52d0639e6be1438d852a6/trinity/protocol/common/peer_pool_event_bus.py#L61-L66
