### ISSUE TITLE
Ensure SpuriousDragon transaction validation enforces `chain_id` match.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#63]
### What is wrong?

It doesn't appear that transaction validation in the SpuriousDragon fork (or subsequent forks) implements validation for EIP155 transactions to ensure that the encoded `chain_id` matches the `Chain.chain_id`.

### How can it be fixed

It looks like we'll need a new validation mechanism at the `Chain` level to do this enforcement.  We currently have `VM.validate_transaction_against_header` and `State.validate_transaction`.  I think we should add `Chain.validate_transaction_against_chain`.

It looks like this will need to be called in both `MiningChain.apply_transaction` and `Chain.build_block_with_transactions`

**Comment by carver** [comment]
This is related to some work happening for EIP-1344 in py-evm. Time to discuss the right approach for threading the chain ID into the place it's needed (presumably `ExecutionContext` for 1344).

An idea from chat:
> maybe a reasonable thing to do is to add a attribute like `chaindb.chain_id` and then pass that in as a new param to `create_execution_context()`

**Comment by fubuloubu** [comment]
I was working on a PR for 1344, got started here: https://github.com/fubuloubu/py-evm/tree/eip1344-chain-id

**Comment by carver** [comment]
> I was working on a PR for 1344, got started here: https://github.com/fubuloubu/py-evm/tree/eip1344-chain-id

Great!

Even better if you can open a PR with `[WIP]` in the title so we can see the diff. No need to worry about failing tests, dirty commits, etc. People know to ignore all that on a work-in-progress.

**Comment by fubuloubu** [comment]
PR: https://github.com/ethereum/py-evm/pull/1803
