### ISSUE TITLE
Address flaws in "Peer disconnected too quickly" approach

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#632]
### What is wrong?

https://github.com/ethereum/trinity/pull/629#issuecomment-493607901

As pointed out in that comment, if we treat `X` seconds as our minimum session length, a peer who is trying to disrupt our sync can wait `X + 1` seconds before disconnecting.

### How can this be fixed?

Ideas:

- introduce randomness for minimum session length on a per-connection basis.
- Take into account our existing sessions and scale blacklist timeout using this data:
    - e.g.  Apply a scaled blacklist to every peer that disconnects from us, very minimal for peers who stay long enough, and move exponentially towards an upper bound when you get closer to the zero.

**Comment by carver** [comment]
Another approach: track EMA of session length, averaging in 0 session length when the peer does not accept a connection. We can (still?) do an exponential backoff of attempts to connect when they refuse a connection, to avoid punishing the long-session-length peers too quickly when they become unavailable.

(Subtlety: we should *not* modify the average session length if we disconnect from a peer and it was a shorter than usual session. But we *should* modify it when we disconnect from a peer and it was a longer that average session.)
