### ISSUE TITLE
Uncaught error bubbling up: Wrong msg mac

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#648]
* Trinity version: v0.1.0-alpha.24 (technically 8569a253)
* OS: linux
* Python version (output of `python --version`): 3.6.7

### What is wrong?

I thought we had an issue for this, but I couldn't find it:

```
ERROR  05-21 12:42:47     DiscoveryProtocol  error unpacking message (b'') from Address(47.90.203.226:udp:30303|tcp:30303): Wrong msg mac
```

### How can it be fixed

Maybe a special-case handling of empty messages?

Or if this is just a known thing, it can probably be dropped down from `error` to a lower level like `debug`.

**Comment by stnbu** [comment]
I can confirm this happens at eaa3b040ffdf0848b8e00a5f329480662ecc7c11 

Not knowing myself... can this message be safely ignored/filtered?

**Comment by carver** [comment]
> can this message be safely ignored/filtered?

Yes, it's just a sign that we got a message from someone that doesn't conform to the expected spec. Since anyone can send anything to us, it's not something to act on as a user. This issue is actually about hiding the message from users. :+1:

**Comment by stnbu** [comment]
Thank you for the response and explanation!
