### ISSUE TITLE
Store Attestation.root -> (Block_root, index)

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#654]
### What is wrong?

This is a part of the attestation pool.

- When a block is processed, store Attestation.root -> (Block_root, index of Attestation)
- When received a new Attestation, discard if the root is seen before.

### How can it be fixed

Add API in the chaindb

**Comment by NIC619** [comment]
> When received a new Attestation, discard if the root is seen before.

Note: also need to check if the attestation is already in the attestation pool.
