### ISSUE TITLE
Super-linear blacklist timout scaling

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#663]
from: https://github.com/ethereum/trinity/pull/628#issuecomment-495492096

### What is wrong?

Currently, blacklist timeouts are scaled sub-linearly.

For certain cases, we probably want to scale linearly or super-linearly.  More generically, we probably want different strategies for different types of blacklisting.

### How can it be fixed

A mechanism for applying different business logic for different blacklist causes.

**Comment by lithp** [comment]
In-lining from my comment: an example of something where the timeout should scale super-linearly with the number of errors is `WrongNetworkFailure`. An ip address with the wrong network will likely not join our network any time soon and it's hard to imagine that a public key on the wrong network will ever join ours. For this error some kind of exponential back-off seems appropriate.

**Comment by lithp** [comment]
Something we could do in the far future is collect some kind of metrics, or run a node which is collecting metrics, and set timeouts / backoff strategies based on how often we observe nodes with particular errors later succeeding.
