### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#669]
### What is wrong?

As a newcomer to the project, it's hard to understand all of the components of Trinity (and Py-EVM) and how they fit together.

### How can it be fixed

Swarm has this really nice diagram

![MVP_Epic_Stability](https://user-images.githubusercontent.com/824194/58382647-ee7e1c00-7f89-11e9-8b7f-19cff4d2d911.png)

It shows:

- Overall structure with high level groupings of APIs
- Sub-components of the things in each group
- color coding to indicate stability

Having this should help onboard new contributors as well as reasoning about how we structure the client.  The generated visuals would be nice assets to include in the documentation.

I think we could do this with [graphviz](https://graphviz.org/) via dotfile, making it easy to have as part of the repository (and easy to update as part of a pull request).

**Comment by mhchia** [comment]
Structure diagram discussed in Denver.
![](https://i.imgur.com/2D4wBVy.jpg)

**Comment by pipermerriam** [comment]
Anyone have ideas on the right format for this to be converted to so that it's easy to edit/update?  Favorite tool for working with this type of thing?

**Comment by cburgdorf** [comment]
>so that it's easy to edit/update

I know it's not the answer you are looking for but creating this thing with Google Draw and just share it public would be pretty simple to edit/update (until Google shuts down Google Draw eventually :sweat_smile: )

**Comment by pipermerriam** [comment]
http://diagramo.com/ might be a good open source option

**Comment by ralexstokes** [comment]
it isn't free but you get ascii art for free: https://monodraw.helftone.com/
