### ISSUE TITLE
Convert `p2p.discovery` callback based architecture to use futures and timeouts.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#674]
### What is wrong?

https://github.com/ethereum/trinity/blob/86b1bfb6f5fcc7b943fb408ae206c047aecb828d/p2p/discovery.py#L830-L843

The callback base approach used here, as well as the way the function behaves could be better.  First, the callback approach is a more complex but functionally equivalent way of implementing an `asyncio.Future`.

Second, the function accounts for not receiving the pong message in time by returning the default *empty* values along with the `got_pong` boolean indicating success/failure.  This is return value checking which is an inherently error prone API design.

### How can it be fixed

The callback part should be fixed by using an `asyncio.Future` instead of the callback.

The return value checking *should* be able to be replaced with an exception based API, raising something like a `TimeoutError` in the case that a pong is not received in time.  Call sites will need to be adjusted to account for this change.

**Comment by gsalgado** [comment]
@pipermerriam now that we're using trio on DiscoveryService, I think the best alternative is to use channels here. How does https://github.com/gsalgado/trinity/commit/26809b09d396f298177664b5e405d1ab31a4c17a look like to you?

**Comment by pipermerriam** [comment]
:+1: on the direction in the linked github commit.  Left a few comments on that commit.
