### ISSUE TITLE
Rework `_compute_shared_prefix_bits`.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#675]
### What is wrong?

https://github.com/ethereum/trinity/blob/86b1bfb6f5fcc7b943fb408ae206c047aecb828d/p2p/kademlia.py#L373-L388

The current implementation of `_compute_shared_prefix_bits` uses the string representation of the binary form of the node ids to perform the check in a very indirect manner.  We are also likely to be incurring non-trivial overhead via all the string manipulation that has to occur.

### How can it be fixed

> This should be validated to match the existing implementation's functionality as well as add tests for the utility function if none exist.

We should be able to apply a binary `&` to reduce the entire list of node ids to a single value and then count the leading set bits on that value.

The new implementation should 1. be tested against the old one, 2. have tests  and 3. be profiled against the old one so we can have a sense for the speed difference.

**Comment by stobiewan** [comment]
Issue should be closed as obsolete.

**Comment by cburgdorf** [comment]
I believe you are correct @stobiewan. Thank you for the note.
