### ISSUE TITLE
Get rid of `with_queued_logging` magic

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#676]
### What is wrong?

We're still using a function decorator that I made a long time ago called `with_queued_logging` that sniffs the `kwargs` of the function to find the queue it needs to setup the queued logging.

I think this magic is not justified.

### How can it be fixed

Getting back into this code, I think we'd be better off doing this explicitly in the function bodies, probably with a helper, and explicitly passing the queued logger as one of the arguments.

**Comment by cburgdorf** [comment]
This issue has been addressed.
