### ISSUE TITLE
Eth1 plugin

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#679]
Documenting @NIC619's awesome idea

### What is wrong?

In eth2 we need to listen to events of the deposit contract on eth1.

#### In production

- Run an instance of a Trinity Eth1 chain, or this could be just another eth1 full client like Geth.
- Run the Eth1Plugin as a light client, it monitors the deposit event and notifies the BeaconPlugin to take actions.

#### In development

- Eth1Plugin generates fake deposit data.

**Comment by mhchia** [comment]
Close in favor of https://github.com/ethereum/trinity/issues/709.
