### ISSUE TITLE
Trinity: dev mode

### ISSUE THREAD

**Issue by rayrapetyan** [ethereum/trinity#69]
I would like to propose and work on a dev mode implementation for Trinity (as mentioned in "Do soon" list at https://github.com/ethereum/py-evm/issues/816). I suggest to follow ganache-cli behavior:

trinity --local

should start a local node, create accounts, reveal private keys for them, define gas-price and gas-limit (everything should be configurable).

Just want to ask if someone is already working on that and what are the main concerns here. Thanks.

**Comment by cburgdorf** [comment]
I just recently learned that `geth` has a `--dev` mode and so I wanted to revisit this issue to say that it may have become much simpler already to implement this. We've recently added a [guide that explains how to setup a private developer testnet](https://trinity-client.readthedocs.io/en/latest/guides/creating_a_custom_testnet.html) which makes me believe that the basic ingredients for a `--dev` mode should probably be here now.
