### ISSUE TITLE
Use web3's build_transaction() to build test chain

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#700]
Right now, there is some manual bit-fiddling to issue transactions as part of the `churn_state` database for some integration tests. If we add the *.abi files for the contracts, then we could use web3.py's `contract.functions.FUNC_NAME().build_transaction()` . That would make it easier to read & modify, and set a better example for future testing databases.

-----------
_Originally posted by @cburgdorf in https://github.com/ethereum/trinity/pull/694_

If we follow my recommendation to put the contracts into `sol` files and generate the interface files, we could use web3 here (after all, Trinity depends on web3 anyway) and make that less cryptic.

That being said, I appreciate the low level code as a learning experience :smile:

**Comment by pipermerriam** [comment]
Nick, this would be a good exploration use case for you to validate the tools you've been building.  See the linked comment as well.
