### ISSUE TITLE
Show aggregate logs during regular sync

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#701]
Sometimes regular sync imports a lot of blocks at once (like if you try to run regular sync from genesis). This spams the screen pretty hard right now.

#646 does a *very* basic solution which is to stop spamming and only show one import every 3 seconds at most (plus some wiggle room, via token bucket).

But it would be better to show some aggregate stats, so we can see things like: total number of transactions executed, and total time to import the blocks. Both of these should be shown since the last log (no matter how long ago that was)

---

> Thoughts on the actual log entry being updated to aggregate the log data?  Would result in two different messages, one that would trigger during fast imports, displaing aggregate info for multiple logs and then another for once things slow down that shows singular block data.

_Originally posted by @pipermerriam in https://github.com/ethereum/trinity/pull/646_

**Comment by AndrewBezold** [comment]
Should debug still show block-by-block, or should the aggregate logs be in both, or should the aggregate be only in info and debug have nothing?

**Comment by pipermerriam** [comment]
I think that DEBUG logs should still be block by block and the INFO logs should be the only place that the aggregate logs need to be displayed..

**Comment by carver** [comment]
Hm, I think this issue is cruft, and was closed by #646
