### ISSUE TITLE
Add eth1 service to monitor eth1 deposit contract

### ISSUE THREAD

**Issue by mhchia** [ethereum/trinity#709]
### What is wrong?
Eth2 client should monitor the deposit contract, and get notified when there are events happening.

### How can it be fixed
Have an `Eth1Monitor` service(and possibly a component) monitoring event logs from `deposit_contract` through web3.py.

`Eth1Monitor`
- stores the received event logs.
- exposes API for beacon node to make requests
    - `get_eth1_data() -> Eth1Data`
    - `get_deposit(deposit_root) -> Deposit`

======
Edit: rewrote `How can it be fixed` section.

**Comment by ralexstokes** [comment]
@mhchia can you update this issue by checking off the things above that are done in #710 ?

will be helpful to see what we need to finish as we start interop experiments

**Comment by mhchia** [comment]
@ralexstokes None of them got solved. #710 was just an initial PR. It was less prioritized later so I haven't continued to finish it.
