### ISSUE TITLE
Support for goerli testnet

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#72]
Depends on:

- [ ] https://github.com/ethereum/py-evm/issues/1457
- [x] https://github.com/ethereum/py-evm/issues/1299 

### What should be done.

We should add support for the new clique based POA testnet

https://github.com/goerli/testnet

**Comment by lithp** [comment]
Related, support for clique: https://github.com/ethereum/py-evm/issues/1457

**Comment by veox** [comment]
For ref, @cburgdorf implemented this in `py-evm`, in PR https://github.com/ethereum/py-evm/pull/1855. From the [related issue](https://github.com/ethereum/py-evm/issues/1457#issuecomment-549343343):

> (...) it won't be able to spin up a Py-EVM based node as an actual Görli validator but it's possible to sync the Görli network just fine.

There's a placeholder PR for this here at #1196 (which should at least mention this issue ;)).

**Comment by veox** [comment]
ethereum/py-evm#1457 is closed. Technically, there's Clique now, but there are still issues with syncing:

* likely consensus failure, #1478;
* can't handshake with Nethermind (not Goerli-specific, just very visible), no issue yet;
* some trouble with peer discovery (not sure if Goerli-specific), no issue yet.
