### ISSUE TITLE
Potential bug in state transition

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#727]
### What is wrong?

https://github.com/ethereum/trinity/blob/af4bc6b41831763a2f2676188eaab88d8f3e87e4/eth2/beacon/state_machines/forks/serenity/state_transitions.py#L42-L62

There should be a per_block_transition on `state.slot == slot` for the case that the state is a pre-state of a block.

### How can it be fixed

The spec now has a python [state transition function](https://github.com/ethereum/eth2.0-specs/blob/v0.7.0/specs/core/0_beacon-chain.md#beacon-chain-state-transition-function) specified,  maybe can be fixed in #714.

**Comment by ralexstokes** [comment]
@ChihChengLiang is this not what is happening on L55?

could you elaborate what you think is wrong or post a code snippet to illustrate the bug?

happy to update this code but i don't see the problem at the moment

**Comment by ChihChengLiang** [comment]
This is no longer an issue after the spec update.

The issue was if a state is a pre-state of a block, then the state and the block has the same slot. So everything in the loop is noop, including L55.
```
In [1]: for _ in range(5, 5):
   ...:     print(_)
   ...:     
<nothing>
```
