### ISSUE TITLE
Switch to new eth2 tests suite

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#748]
### What is wrong?

The v0.5.1 tests are in https://github.com/ethereum/eth2.0-tests, but the new test case and new test cases and new formats are in https://github.com/ethereum/eth2.0-spec-tests.

### How can it be fixed

Update the submodule fixture and the APIs.

**Comment by ralexstokes** [comment]
Closing as this issue seems to have gotten stale (we are now on v0.8.3 tests)
