### ISSUE TITLE
Create a plugin to offer a GraphQL API 

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#75]
### What is wrong?

Nick (@Arachnid ) recently started to build a GraphQL API (as an alternative to the JSON RPC API) on top of the Ethereum Go client.

https://github.com/ethereum/go-ethereum/pull/17903

There's a good chance that this will be standardized and become a thing across multiple clients. Apart from that, I believe it's a great use case for our Plugin API.

### How can it be fixed

The existing [JSON-RPC plugin](https://github.com/ethereum/py-evm/blob/master/trinity/plugins/builtin/json_rpc/plugin.py) can serve as a starting point but the rest is mostly "just figure it out".

**Comment by pipermerriam** [comment]
Replaced by https://github.com/ethereum/trinity/issues/302
