### ISSUE TITLE
Try `pyoxidizer` for building releases.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#753]
### What is wrong?

No clear path to building and distributing binaries.

### How can it be fixed

https://gregoryszorc.com/blog/2019/06/24/building-standalone-python-applications-with-pyoxidizer/

**Comment by ralexstokes** [comment]
we can try this out when we get to a testnet trinity-beacon release!

**Comment by cburgdorf** [comment]
>And unlike other tools in this space which tend to be operating system specific, PyOxidizer works across platforms (currently Windows, macOS, and Linux - the most popular platforms for Python today). 

:clap:
