### ISSUE TITLE
Adopt `newsfragments` pattern currently used in `trio` codebase (and maybe use `towncrier`)

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#754]
### What is wrong?

For each PR we have to also push a commit to the release notes.  I'm not loving the workflow.  I find it easy to forget to do.

### How can it be fixed

Take a look at this: https://github.com/python-trio/trio/tree/master/newsfragments

I believe it uses this tools to aggregate it: https://pypi.org/project/towncrier/

I think this would be a more reliable way to aggregate these changes and it is friendly to 3rd party contributors.

**Comment by pipermerriam** [comment]
cc @lithp @carver @cburgdorf @ralexstokes

**Comment by carver** [comment]
Related: #101

**Comment by carver** [comment]
I think this looks the most like the gitlab-writeup that veox ponted to:

> For this reason, [GitLab generates their change log from contributor-provided snippets](https://docs.gitlab.com/ce/development/changelog.html). The [reasoning section](https://docs.gitlab.com/ce/development/changelog.html#history-and-reasoning) is at the very end, but highlights a few rakes, so not worth skipping.

So probably worth a re-read of that post before changing the process.

**Comment by carver** [comment]
I just did a re-read of the reasoning, and of our conversation in 101. I think maybe some resistance was about the data being structured, which it appears the `towncrier` approach doesn't require (except for `rst` format, which isn't really a new constraint, and the filename format).

So I'm :+1: to switch if others are. It looks quite similar in output to our current release note approach, anyway.

**Comment by cburgdorf** [comment]
I support this and I happily volunteer to set it up if we agree we want it.

**Comment by pipermerriam** [comment]
![make-it-so](https://user-images.githubusercontent.com/824194/60905346-1a9be680-a232-11e9-892f-f967fbcc94cd.jpg)
