### ISSUE TITLE
Fix broken JSON-RPC eth_syncing API call

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#765]
### What is wrong?

The functionality got removed in https://github.com/ethereum/trinity/commit/4c87a663a0b426d418045ece74c54cb4d6c1eeb4#diff-8a563f755f9f95bd5dbd1e7b6a0f3c22L160 (probably accidentially ping @carver )

We had no tests for this so that went unnoticed for a while.

### How can it be fixed

Add it back in and then expand this test to ensure it doesn't break again.

https://github.com/ethereum/trinity/blob/b35ddb9b90a440ec98d5d141e3fbc6e2f1f35b2b/tests/integration/test_trinity_cli.py#L142-L143

**Comment by carver** [comment]
> The functionality got removed in [4c87a66#diff-8a563f755f9f95bd5dbd1e7b6a0f3c22L160](https://github.com/ethereum/trinity/commit/4c87a663a0b426d418045ece74c54cb4d6c1eeb4#diff-8a563f755f9f95bd5dbd1e7b6a0f3c22L160) (probably accidentially ping @carver )

Yup, almost certainly an accident.

**Comment by Patil2099** [comment]
@cburgdorf  Can I work on this issue? Can you explain it a little more>
Thanks!

**Comment by cburgdorf** [comment]
@Patil2099 sure, you can. You just have to be prepared to explore the exact path forward on your own.

To get you off the ground, here's what's wrong and how you can prove it.

1. Open a terminal and run `trinity`
2. Open a second terminal tab and run `trinity attach`
The terminal output in the second terminal should look like this:

```
$ trinity attach
    INFO  09-06 09:52:43               trinity  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  09-06 09:52:43               trinity  Started main process (pid=14010)
    INFO  09-06 09:52:43               trinity  Trinity/0.1.0a27/linux/cpython3.7.3
    INFO  09-06 09:52:43               trinity  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs-eth1/trinity.log
Trinity Console
---------------
An instance of Web3 connected to the running chain is available as the `w3` variable
The exposed `rpc` function allows raw RPC API calls (e.g. rpc('net_listening'))
```

3. Type `rpc('net_listening')` and hit enter
4. Your output so far should look like this.

```
In [1]: rpc('net_listening')
Out[1]: {'id': 0, 'jsonrpc': '2.0', 'result': True}
```

:point_up: is just to demonstrate that the RPC API works in general and what correct output would look like.

5. Now type `rpc('eth_syncing')` and hit enter
6. You'll notice that it just hangs for ten seconds until it hits a timeout

```
Timeout: 10 seconds
```

**This is what's broken**

7. Why is it broken? Because behind the scenes there is a `SyncingRequest` being fired that is waiting on a `SyncingResponse` but there's no one responding.

https://github.com/ethereum/trinity/blob/248efac0cc6daf43e49e5739a80f11737dd06161/trinity/rpc/modules/eth.py#L273-L281

8. Why is no one responding?

Because it was accidentally removed here: https://github.com/ethereum/trinity/commit/4c87a663a0b426d418045ece74c54cb4d6c1eeb4#diff-8a563f755f9f95bd5dbd1e7b6a0f3c22L160

9. What needs to be done is to figure out how to put back in the code that listens for the `SyncingRequest` and fires back an appropriate `SyncingResponse`.

Does that get you started?

**Comment by KimiWu123** [comment]
hi @cburgdorf ,

I tried to fix this, here is [my commit](https://github.com/KimiWu123/trinity/commit/2ce73860a5ed40d6a2e7d44fecb122ec5be75ac5). I haven't merged yet because it always has some error and my code doesn't be executed.
```
   DEBUG  2019-10-31 13:56:32,862  ETHPeerPoolEventServer  Running ETHPeerPoolEventServer
   ERROR  2019-10-31 13:56:32,866            FullServer  Unexpected error in <trinity.server.FullServer object at 0x1089e95c0>, exiting
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1109, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 51, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimi/CODE/trinity/p2p/service.py", line 117, in run
    await self._run()
  File "/Users/kimi/CODE/trinity/trinity/server.py", line 125, in _run
    await self._start_tcp_listener()
  File "/Users/kimi/CODE/trinity/trinity/server.py", line 115, in _start_tcp_listener
    port=self.port,
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/streams.py", line 119, in start_server
    return (yield from loop.create_server(factory, host, port, **kwds))
  File "uvloop/loop.pyx", line 1669, in create_server
  File "uvloop/loop.pyx", line 1113, in uvloop.loop.Loop._create_server
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 30303): address already in use
    INFO  2019-10-31 13:56:32,880            FullServer  Closing server...
   DEBUG  2019-10-31 13:56:32,880            FullServer  <trinity.server.FullServer object at 0x1089e95c0> halted cleanly
   DEBUG  2019-10-31 13:56:32,880              FullNode  <trinity.server.FullServer object at 0x1089e95c0> finished while <trinity.nodes.full.FullNode object at 0x1089bb588> is still running, terminating as well
   DEBUG  2019-10-31 13:56:32,880              FullNode  Cancelling service: <trinity.nodes.full.FullNode object at 0x1089bb588>
   DEBUG  2019-10-31 13:56:32,884              FullNode  <trinity.nodes.full.FullNode object at 0x1089bb588> finished: Cancellation requested by FullNode token
   DEBUG  2019-10-31 13:56:32,884              FullNode  Waiting for child services: [<trinity.protocol.eth.peer.ETHPeerPoolEventServer object at 0x108a0da20>, <trinity.server.FullServer object at 0x1089e95c0>]
   DEBUG  2019-10-31 13:56:32,887       BeamSyncService  <trinity.sync.beam.service.BeamSyncService object at 0x108a0def0> finished: Cancellation requested by FullNode token
   DEBUG  2019-10-31 13:56:32,887       BeamSyncService  <trinity.sync.beam.service.BeamSyncService object at 0x108a0def0> halted cleanly
   ERROR  2019-10-31 13:56:32,888  component(#SyncerComponent)  Sync ended unexpectedly. Shutting down trinity
```

I cloned the source directly and executed `trinity` without any arguments and didn't touch any configs. Have any ideas? thanks.

**Comment by cburgdorf** [comment]
@KimiWu123 the error suggests one of these things:

1. You have another Trinity instance running
2. You have something else running taking that port
3. Maybe a previous Trinity run did not shutdown cleanly.

I'd suggest you try running `trinity fix-unclean-shutdown` to see if that fixes the error.

However, that particular issue already has an [active PR](https://github.com/ethereum/trinity/pull/1237) by @voith open so I suggest looking for a different issue that doesn't have an open PR yet.

**Comment by voith** [comment]
hey guys, sorry for not posting here before. I wanted this issue fixed to use somewhere else.
