### ISSUE TITLE
LMD GHOST scoring is broken

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/trinity#782]
### What is wrong?

See https://github.com/ethereum/trinity/pull/685/files/b4dbf6a58d444578ee1b882ca21256eaf1a5f6a4#r294035068 on issue #685.

The score is the sum of the attestation data and the block root data but this obscures the semantics of the fork choice scoring.

The attestation data yields a balance and only upon ties do we want to consider the block root data. The code in #685 just sums them which could result in mis-scoring a block where the balances are close and the block root puts the incorrect block as having a higher score.

### How can it be fixed

We need a more flexible score type for the fork choice rule (including a way to {de,}serialize from disk).

1. The `ForkChoiceScoringFn` type should return an opaque `Score` type (instead of just an `int`).
2. Different fork choice scorings can provide different implementations of `Score` as makes sense -- the main thing `Score` needs is to satisfy a comparator interface and a {de,}serializing ability for writing scores to the DB.

something like:

```python
class Score(abc.ABC):
    @abstractmethod
    def cmp(self, other: Score) -> int:
        """ Return [-1, 0, 1] if ``self`` is [less than, equal to, greater than] ``other``."""
        pass

    @abstractmethod
    def serialize(self) -> bytesOrSomething:
        pass

    @abstractmethod
    @classmethod
    def deserialize(cls, contents: bytesOrSomething) -> Score:
        pass
```

**Comment by ralexstokes** [comment]
update from @carver 

use something like this: https://github.com/ethereum/eth-utils/blob/master/eth_utils/numeric.py#L5

to enforce the "comparator" interface on our `Score` type

**Comment by carver** [comment]
Some more background conversation: https://github.com/ethereum/eth-utils/pull/150#discussion_r275906374
