### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#804]
### What is wrong?

The documentation is rather sparse. This issue serves as a quick and dirty way to collect what's missing. 

### How can it be fixed

Everyone should fee free to add comments here with things they find missing from the docs. Ideally try to categorize things in these three buckets:

- **I am missing API docs on X**
- **I am missing a short recipe on how to do X**
- **I am mssing a detailed guide on X**

**Comment by pipermerriam** [comment]
* I am missing API docs on the new trio service ManagerAPI
* I am missing short recipes on how to do basic things with services:
    - make them using normal class inheritance
    - make them using a decorator and a normal async function
    - run them either using normal `await` or the context manager API
    - cancel them internally or externally
    - run background tasks (including the difference betwean *"deamo"*` tasks and non-daemon)
    - wait for them to finish (not the same as cancelled)
    - wait for them to be cancelled.

**Comment by s0b0lev** [comment]
@cburgdorf  what do you think about adding detailed CLI docs with [this extension](https://sphinx-argparse.readthedocs.io/en/stable/sample.html#generated-sample-1-command-with-subcommands)? 

This extension is able to generate full CLI doc with details about sub parser and it commands.

- **I am missing API docs on** detailed [CLI positional arguments](https://trinity-client.readthedocs.io/en/latest/api/api.cli.html)

**Comment by cburgdorf** [comment]
Haven't looked into it (I have some days off) but the generated docs look
good and I'd be happy to have this detailed coverage for the CLI docs.

**Comment by s0b0lev** [comment]
Ok @cburgdorf I can create PR with detailed CLI

**Comment by cburgdorf** [comment]
@s0b0lev Thanks! That would be great!
