### ISSUE TITLE
Release Process: towncrier build doesn't check for warnings

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#806]
# What is wrong?

Towncrier can generate release notes that will fail to build and be enshrined forever in the released version.

Our `make docs` fails on warnings, but when we run towncrier during `make release`, it doesn't check 

### How can it be fixed

Make sure that `make docs` would succeed on the generated release notes before tagging, upgrading, and pushing the commit.

**Comment by cburgdorf** [comment]
How about we do a last check in `make release` before any of the actual release process starts?

**Comment by carver** [comment]
Closed by 7cccbf7980
