### ISSUE TITLE
The procedure of `process_final_updates` is inconsistent with the spec

### ISSUE THREAD

**Issue by hwwhww** [ethereum/trinity#817]
### What is wrong?

In the spec [process_final_updates](compact_committees_roots):
1. Update `state.validators`
2. Update `state.start_shard`
3. Update `state.compact_committees_roots` by using the *updated* `state.validators` and `state.start_shard` to calcuate the new value.

And in Trinity side: https://github.com/ethereum/trinity/blob/b6ca964b0440d8608e94a60039e34d9ca3884749/eth2/beacon/state_machines/forks/serenity/epoch_processing.py#L832-L853
We update each field separately and then update all at the same time.

p.s. I love the readability of Trinity side more in this case. :'(
It's hard to find the sequential dependency in the deeper functions when we need to be consistent with the spec...

### How can it be fixed

Rewrite `process_final_updates`; at least fix `state.compact_committees_roots`.

**Comment by ralexstokes** [comment]
@hwwhww i think what you did here https://github.com/ethereum/trinity/pull/815/commits/78b4277c76500257a2e9bcbc7f468b18e76d3e84 is fine for now -- i'll push this change to master and then we can close this

**Comment by ralexstokes** [comment]
Fixed in #819.
