### ISSUE TITLE
Potential opportunity for performance boost via parallelization of response validation

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#82]
### What is wrong?

See: https://github.com/ethereum/py-evm/blob/a251ffbd773a6d062497341ae41789be8b76dcd3/trinity/protocol/common/managers.py#L265

We run a *normalization* step for each response from a peer request.  In cases for things like block bodies, this is expensive and thus we do it in an executor.  While this does offload CPU intensive operations to another process, it can be further optimized.

### How can it be fixed

Rather than running `normalizer.normalize_result` as a single operation in a single worker, we should look into parallelizing this across multiple workers as things like computation of the uncle hashes and computation of the transaction roots can be done in parallel.

**Comment by carver** [comment]
> This seems to work but it doesn't improve sync performance so I'm inclined to shelve it until we've eliminated whatever performance bottlenecks are sitting in front of it.

I'll take shelve to mean close now and re-open at appropriate time. :)
