### ISSUE TITLE
Flaky Eth2-core tests (Too long with no output (exceeded 10m0s))

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#821]
### What is wrong?

Some py{36, 37}-eth2-core failed and report "Too long with no output (exceeded 10m0s)". I tried running on local multiple times, and sometimes it hangs forever.

These are the sampled builds:

Failed tests

- https://circleci.com/gh/ethereum/trinity/65712
- https://circleci.com/gh/ethereum/trinity/65749
- https://circleci.com/gh/ethereum/trinity/66201
- https://circleci.com/gh/ethereum/trinity/65999
- https://circleci.com/gh/ethereum/trinity/65981

Successful tests

- https://circleci.com/gh/ethereum/trinity/65902

### How can it be fixed

Not sure

**Comment by ChihChengLiang** [comment]
If observed carefully, the length of the dots in the failing tests is exactly 316. But the tests near 316 should be short and fast one.

```
pytest  tests/eth2/core/ --collect-only |grep \<Function | nl
```

**Comment by pipermerriam** [comment]
You can add a `-v` to the test run so you can see exactly what test is running.
