### ISSUE TITLE
`factory` should not be under the main trinity code namespace.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#833]
### What is wrong?

This file should not be co-located with the main production code:

https://github.com/ethereum/trinity/blob/f1d0139d761316a5332231470ba2a94b9be8c230/trinity/protocol/bcc_libp2p/factories.py

This is because the `factory-boy` dependency is not part of the main code and so we've relegated things like this to live in a location like `trinity.tools.factories` or `p2p.tools.factories`.

### How can it be fixed

Move this module to either be under `p2p.tools.factories` or `trinity.tools.factories` and add a code block like this to ensure that there are nice errors if the dependency isn't installed.

https://github.com/ethereum/trinity/blob/f1d0139d761316a5332231470ba2a94b9be8c230/p2p/tools/factories.py#L21-L24

**Comment by mhchia** [comment]
Thanks for pointing this issue out. I opened a PR to fix this: https://github.com/ethereum/trinity/pull/840.
