### ISSUE TITLE
Move handling of peer requests to a plugin (and it's own process)

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#84]
### What is wrong?

The code which responds to peer requests for data runs alongside everything else.  This is problematic because the CPU time is shared between it **and** the networking code **and** the synchronization code.

This results in a high peer count and high volume of incoming requests having a direct impact on both our baseline networking performance as well as sync performance.

### How can it be fixed

Fully move the handling of peer requests into an isolated process (probably a built-in plugin).

**Comment by cburgdorf** [comment]
This landed with https://github.com/ethereum/trinity/pull/617
