### ISSUE TITLE
Trinity doesn't shut down cleanly

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#872]
* Trinity version: 6493c94656b907c
* OS: osx/linux

### What is wrong?

Ctrl-C no longer cleanly exits. You need a second Ctrl-C to get out. Occasionally, it leaves dirty IPC files, or even hanging processes that never exit.

### How can it be fixed

:man_shrugging: 

I ran `git bisect` and narrowed it down to the above commit. cc @cburgdorf  @pipermerriam

**Comment by pipermerriam** [comment]
I'll dig in on Monday as it seems this was my doing.
