### ISSUE TITLE
DiscV5 Low-level Services Tracking Issue

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/trinity#873]
### Main PRs

- :heavy_check_mark: [UDP sending/receiving services](https://github.com/ethereum/trinity/pull/816): Datagrams <--> UDP sockets
- :eyes: [Packet encoding/decoding services](https://github.com/ethereum/trinity/pull/863): Packets <--> Datagrams
- :construction: [Handshake services](https://github.com/ethereum/trinity/pull/868): Perform handshake as initiator or recipient
- :question: Packer services: Packets <--> Messages, manages handshake services
- :question: Message Dispatcher: High level interface to send/receive messages

### Secondary PRs

- :eyes: [Tags](https://github.com/ethereum/trinity/pull/864): Minor utility functions
- :question: Typing: Introduce some more specific types

------

### Symbols
:question: to do
:construction: WIP PR
:eyes: ready for/under review
:heavy_check_mark: merged

**Comment by pipermerriam** [comment]
One thing I had thought of was exposing some of this discovery data over JSON-RPC to make it a little easier to introspect and debug at runtime.  We'll end up with application logic that publishes records and holds onto other node records and being able to explore and dig into this data at runtime without restarting the services could be very valuable.  No need to prioritize this up-front but maybe something to think about as you get closer to a live working implementation and start wanting to see what's happening under the hood.

**Comment by pipermerriam** [comment]
Also, do you have a rough ETA on when this will be usable?  How long until we could run trinity as a bootnode for v5 discovery and actually do the node-finding for a specific topic.

cc @carver as this might be a good way for trinity nodes to find other trinity nodes were we to do something for beam sync such as a new subprotocol for nodes to gossip around block proofs.

**Comment by jannikluhn** [comment]
> Also, do you have a rough ETA on when this will be usable? How long until we could run trinity as a bootnode for v5 discovery and actually do the node-finding for a specific topic.

Originally, the plan was to have a working version at the end of this month. This still seems realistic for the plain DHT implementation, but not for topic discovery. However, if we want to, we can parallelize the work a little as the [DHT](#876) and especially [topic discovery](#875) are somewhat independent from the details of the lower layers I'm working on right now. I've opened two issues for those.
