### ISSUE TITLE
Allow beam sync to sync from a checkpoint header provided via CLI flag

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#892]
### What is wrong?

Before beam sync can start of doing its "beam magic", it still needs to download the chain of headers. While that's not the end of the world, it would be much nicer if the user could provide a checkpoint for a header that beam sync would trust (to start with) and build up on top.

### How can it be fixed

1. Add support for a CLI flag `--beam-sync-checkpoint <block-hash> <td>`

2. Make sure beam sync can build on top of this checkpoint

3. It should still fill up the headers in the background but same goes for blocks so not sure if this needs to be part of this mechanism.

**Nice to have:**

- Add support for a CLI flag that delegates reading a recent block / td from a website and use that as a checkpoint (e.g. `--beam-sync-checkpoint-source https://etherscan.io/`)

**Comment by pipermerriam** [comment]
We've used URI formats for things like this nicely.  dunno how you or others feel about this but.

- `block://<block-hash>/<total-difficulty>`
- `etherscan://<block-number-or-hash-or-latest>`
- `infura://<block-number-or-hash-or-latest>`

For the `block-number-or-hash-or-latest` my thought was that we could accept it as either the hash, the integert number, or the string `latest` which would do something like auto-computing the checkpoint at something like `HEAD - Nblocks`

**Comment by cburgdorf** [comment]
@carver @pipermerriam am I correct to assume that we need to do something about persist_header_chain in py-evm?

https://github.com/ethereum/py-evm/blob/d2ccc1e8a9be1cb92cb15a8bb117bb6a1972636e/eth/db/header.py#L194-L196

Because, on the evm level, persisting headers with missing parents is currently not possible. We could relax this but I'm wondering if you had already thought about this and have alternative ideas?

**Comment by cburgdorf** [comment]
But I guess we can not just relax it, we would probably need a different API to persist such "orphaned" headers which would also take the score into account.

Something like:

```python
    def persist_orphan_header(self, header: BlockHeaderAPI, score: int) -> None:
```

That's because in the regular case we would calculate the score based on the parent which we can't in this case. So, I'm thinking we just have to accept whatever is passed as `score` in another parameter. Does that make sense?

**Comment by cburgdorf** [comment]
This is turning into a public brain dump for myself. I figured out that even with a new API `persist_orphan_header` we'll still be in trouble because as soon as we start persisting blocks on top of the orphaned block we'll run into an exception here:

https://github.com/ethereum/py-evm/blob/d2ccc1e8a9be1cb92cb15a8bb117bb6a1972636e/eth/db/header.py#L235-L236

That's because `find_new_ancestor` will walk up the chain until it finds a common ancestor and by doing so it will eventually hit the first missing block from the gap that we left.

https://github.com/ethereum/py-evm/blob/d2ccc1e8a9be1cb92cb15a8bb117bb6a1972636e/eth/db/header.py#L279-L311

**Comment by pipermerriam** [comment]
Maybe we could do something like having `SkeletonHeaderDB` that stores the *orphaned* headers in a separate database than the main ones and has extra functionality to migrate non-orphaned headers to the main db once the gaps are filled in.

This would be inline with the direction I think we're going to end up going anyways which is to get some of this data that never gets modified out of the leveldb database entirely (See https://github.com/ethereum/py-evm/issues/1807)

**Comment by carver** [comment]
I think we only ever need one checkpoint at a time, so we could store it in an `enforced_checkpoint_hash` key. The skeleton header syncer can become aware of this key and check for it when deciding how far back to ask for headers.

Orphan is a surprising name for it, to me. I still like checkpoint, or maybe pseudo-genesis, or enforced-root, or launchpoint.

I agree that we should have a custom method to store this header, which necessarily trusts the input score and header:
```py
def persist_launch_header(self, header: BlockHeaderAPI, score: int) -> None:
```

**Comment by carver** [comment]
> We've used URI formats for things like this nicely. dunno how you or others feel about this but.
> 
> * `block://<block-hash>/<total-difficulty>`
> * `etherscan://<block-number-or-hash-or-latest>`
> * `infura://<block-number-or-hash-or-latest>`
> 
> For the `block-number-or-hash-or-latest` my thought was that we could accept it as either the hash, the integert number, or the string `latest` which would do something like auto-computing the checkpoint at something like `HEAD - Nblocks`

These things feel really shoe-horned into URIs, to me. I think it's easier to understand what's going on with an explicit difference between locally-specified and remotely determined:

```sh
# Locally specify a particular block
trinity --set-launch-header 0xhash --set-launch-score 123

# custom pre-loads for some well-known endpoints
trinity --trust-launch-header-by {etherscan,infura} --launch-header-blocks-to-tip 1000
```

**Comment by cburgdorf** [comment]
>I think we only ever need one checkpoint at a time, so we could store it in an enforced_checkpoint_hash key. The skeleton header syncer can become aware of this key and check for it when deciding how far back to ask for headers.

@carver are you proposing this as an alternative to the separate db that @pipermerriam was proposing?

If so, I'm not sure I follow. AFAICT, teaching the skeleton syncer about which headers to ask for isn't the big problem. The problem is, how do we persist these headers that aren't (yet) connected back to genesis. Storing these disconnected headers is rejected with our current Py-EVM APIs.

>Maybe we could do something like having SkeletonHeaderDB that stores the orphaned headers in a separate database than the main ones and has extra functionality to migrate non-orphaned headers to the main db once the gaps are filled in.

I guess collecting these disconnected headers in a separate db until we can connect them back to genesis might be an option. We could treat the first header (the checkpoint) as a pseudo genesis and then basically keep the same rules about enforcing contiguous headers on top of it just like we do it for the full chain today.

However, there might be another problem with that. While it is true that there's only one checkpoint at *runtime*, we may create lots of different checkpoints from run to run. Especially if we do something like `trinity --trust-launch-header-by etherscan --launch-header-blocks-to-tip 1000`. Then, each run will be with a different checkpoint and potentially in a different db?

I guess we could also keep things in the same db and just separate these disconnected stretches of headers by different lookup keys.

>Orphan is a surprising name for it, to me. I still like checkpoint, or maybe pseudo-genesis, or enforced-root, or launchpoint.

Yes, it's not quite the right term. Checkpoint and the like are good candidates to refer to the single header that we are starting off from. But I'm lacking a good name for the "stretch of headers" that form a contiguous chain *on top* of the checkpoint but are still disconnected from the genesis block until we have closed the gap.

**Comment by cburgdorf** [comment]
So, here's a think we can do relatively easily. Here's a working Py-EVM test.

```python

def test_headerdb_persist_disconnected_headers(headerdb, genesis_header):
    headerdb.persist_header(genesis_header)

    headers = mk_header_chain(genesis_header, length=10)

    score_at_pseudo_genesis = 154618822656
    # This is the score that we would reach at the tip if we persist the entire chain.
    # But we test to reach it by building on top of a trusted score.
    expected_score_at_tip = 188978561024

    pseudo_genesis = headers[7]

    # Persist the checkpoint header with a trusted score
    headerdb.persist_checkpoint_header(pseudo_genesis, score_at_pseudo_genesis)

    headers_from_pseudo_genesis = (headers[8], headers[9],)

    headerdb.persist_header_chain(headers_from_pseudo_genesis, pseudo_genesis.parent_hash)
    assert headerdb.get_score(headers[-1].hash) == expected_score_at_tip
```

We would do two things:

1. Add an API `persist_checkpoint_header` (or maybe just `persist_header_with_score`?). This API just saves the header and blindly trusts us with the score.

2. The `persist_header_chain` API would gets an additional * optional* parameter to let us overwrite what is internally used as `GENESIS_PARENT_HASH`. It defaults to the `GENESIS_PARENT_HASH` constant that is hardcoded today.

With that in place, `persist_header_chain` will continue to work exactly as it works today but allows persisting chains that just validate up until reaching some given checkpoint (treated as pseudo genesis). It also means that all existing validations continue to work as expected (e.g. it would still raise if there are gaps in the chain that we are trying to persist).

I'm not saying that's the best way to go but so far, to me, it seems to be a viable option that strikes me as particular simple.

**Comment by pipermerriam** [comment]
If you've got something that *works* for now that's simple lets run with that iterate from there.

**Comment by carver** [comment]
> * Add an API `persist_checkpoint_header` (or maybe just `persist_header_with_score`?). This API just saves the header and blindly trusts us with the score.

Yup, I like checkpoint, which is a stronger semantic indication that you are asserting something different about this header to persist.

> * The `persist_header_chain` API would gets an additional * optional* parameter to let us overwrite what is internally used as `GENESIS_PARENT_HASH`. It defaults to the `GENESIS_PARENT_HASH` constant that is hardcoded today.

I don't follow why, but I'm sure it will make sense when we are looking at the PR.

Agree with Piper, take the idea for a spin, and we can discuss inline on the code...
