### ISSUE TITLE
Trinity leaves behind locked-up processes

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#897]
* Trinity version: 96b1213ce1f4 (or before)

### What is wrong?

Trinity *appears* to shut down cleanly, but actually leaves a bunch of processes running. This is a quick and easy way to run out of RAM.

Example processes:
```sh
$ ps aux | grep 'trinity/venv'
jcarver  11964  0.0  0.0  33484 11132 pts/8    S    15:29   0:00 ./trinity/venv/bin/python3 -Wdefault -c from multiprocessing.semaphore_tracker import main;main(19)
jcarver  11965  0.1  0.2 262108 82552 pts/8    S    15:29   0:01 ./trinity/venv/bin/python3 -Wdefault -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=20, pipe_handle=24) --multiprocessing-fork
jcarver  11966  0.1  0.2 265108 85828 pts/8    S    15:29   0:02 ./trinity/venv/bin/python3 -Wdefault -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=20, pipe_handle=25) --multiprocessing-fork
...
```

### How can it be fixed

I suspect it's related to Beam Sync plugin processes that are locked up. Maybe we need some kind of return event that indicates a shutdown? (The processes might be stuck in a `lahja` `CollectMissingAccount` request that is waiting for a response)

**Comment by cburgdorf** [comment]
Uh, that sounds horrible. I'll dive in.

>(The processes might be stuck in a lahja CollectMissingAccount request that is waiting for a response)

Trinity should eventually `sigkill` every process on shutdown. Not sure how that happens. Anyway, I'll see what I can figure out about that.
