### ISSUE TITLE
Move functionality from `Peer` class down into `Protocol` class.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#90]
### What is wrong?

A while back I did a reasonably big effort to get the *EVM* stuff out of the `p2p` module.  One of the harder parts was the `Peer` classes.  This lead us to the idea that the functionality that is currently wrapped up in the `Peer` class should be split.

### How can it be fixed

The basic idea is:

- `Protocol` class gets the low level stuff
- `Peer` class gets the higher level stuff
- `Peer` class gets instantiated with a `Protocol` instance.

So, the `Protocol` class becomes a *Service* and gets instantiated with the reader/writer streams and other connection information.  It also gets the `read_msg` loop and needs to expose an API for consumer to stream those messages.  I believe that a single consumer model is appropriate here.  It seems prudent to have the *base* protocol messages partitioned from the *sub* protocol messages so that we can have a dedicated handler for `Ping/Pong/Disconnect`.

The `Peer` class should be instantiated with a running `Protocol` instance.  Running the peer would *stream* the incoming messages from the `Protocol` instance and handle them however it deems appropriate.

This design **should** simplify our concept of what a `Peer` is, removing the *need* for us to actually go through the handshake/connection by separating/decoupling the networking component.

**Comment by veox** [comment]
After fiddling some with PR #205, it seems that `Protocol`, too, could avoid object instantiation, if the reference to `peer` that created it could be removed...

This functionality that perhaps doesn't belong in `Peer` - it seems to me that it doesn't belong in `Protocol`, also.

Should it be isolated then into a new `MessageStream`/`ProtocolMultiplexer` class?..

(Just thinking out loud.)

**Comment by pipermerriam** [comment]
Now that this is underway I've got a bit of a map of what things can/should/might come next.  None of this is set in stone of course or even necessarily the right idea but rather musings that lead towards something hopefully better.

### Further shrink the `Peer` concept.

Basically this: https://github.com/pipermerriam/trinity/pull/2

We'll call this a `Connection` for lack of a better term right now.  A connection binds a `Protocol` to a `Transport`, implementing the business logic needed to do the sub-protocol handshake.

Basically this code and the parts directly related to it become a new class:

https://github.com/ethereum/trinity/blob/926e95cf96159e557a30a7c78f43dbe10c919be6/trinity/protocol/eth/peer.py#L69-L95

I do not believe the `Connection` class needs to be a service.

One important point will be to aim for `Connection` to be generic for all protocols.  I.E., not to have an `ETHConnection` and an `LESConnection`, but only one `Connection` class that is used for all protocols.  I believe this is important if we want to eventually do away with `EthPeer/LESPeer/etc` and just have a single concept of `Peer`.  Goal being to have the `Protocol` be where all of the specialized components live.

### Rename `sub_protocol` and `base_protocol`

Simple terminology switching.

- `base_protocol` which represents the `P2PProtocol` instance responsible for the base communication of the core protocol commands becomes `core_protocol`
- `sub_protocol` just becomes `protocol`

I've found these terms easier to deal with and it simplifies the name we use for the *thing* we interact with most commonly.

### Migrate request/response API to use `Connection`

After we have a `Connection` concept, the request/response API needs to be refactored such that it only knows about `Connection` and is naive of `BasePeer`.

### Single `P2PProtocol`, many other `Protocols`

IIUC we are supposed to be able to speak across multiple sub-protcols using the same p2p connection.  As it stands our infrastructure only knows how to handle a single sub-protocol.  Once we have a `Connection` concept extending to multiple concurrent protocols should be straight forward.  This leads nicely into the next component.

### Figure out the future of `Peer`

Assuming we have a `Connection` object, the peer class's responsibilities will have shrunken significantly, however, I believe the `Peer` will still be the part of this that *runs*, i.e. that is a `BaseService`.  Peers now wrap up multiple protocol connections including the core p2p protocol connection and expose the high level apis for things like disconnecting, stats tracking and aggregation, etc.  It's not clear to me whether we will be able to get rid of `ETHPeer/LESPeer/etc` and have a single `Peer` class but I *think* it's doable.


### Generic `PeerPool`

We should also be able to ditch the `ETHPeerPool/LESPeerPool` concepts and just have a single `PeerPool` that houses all of our peers (which are also homogenous in type).  This requires APIs for asking only for peers that support the required protocol but that shouldn't be too difficult.

**Comment by gsalgado** [comment]
I think most of this has been done already, @pipermerriam?

**Comment by pipermerriam** [comment]
Yeah, closing.  We can open a new one whenever someone gets capacity/inspiration to continue this effort.
