### ISSUE TITLE
Receive Server in Beacon node

### ISSUE THREAD

**Issue by NIC619** [ethereum/trinity#912]
### What is wrong?
Receive Server in Beacon node is currently WIP: https://github.com/ethereum/trinity/pull/904
But it's blocked until [`RecentBeaconBlocks`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/p2p-interface.md#recentbeaconblocks) request/response is implemented. 

### How can it be fixed?
Implement `RecentBeaconBlocks` request/response.
Implement requesting parent block for orphan block in Receive Server.

**Comment by ralexstokes** [comment]
have we landed this in #904?

**Comment by NIC619** [comment]
Yes!
