### ISSUE TITLE
Check if kademlia nodes can be made pickable

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/trinity#94]
### What is wrong?

Kademlia nodes seem to be pickable when testing it with the default pickler in an interactive shell but fail with "can not picke module" when trying to send them between processes.

To workaround this, we currently manually serialize/deserialize nodes into uris to send the across processes.

https://github.com/ethereum/py-evm/blob/9c8fb3eead378ec4d1eb4454be574dd66c2f5580/p2p/kademlia.py#L143-L150

### How can it be fixed

More debugging :hocho:

**Comment by carver** [comment]
So while this might be tricky to figure out, it shouldn't require *too* much repo-specific knowledge to hunt down. If you can get trinity running without converting to uri's first, then you've pretty much solved it, there shouldn't be any surprising side-effects. (famous last words)

So... I added a good first issue in case someone wants to take a look at it.

**Comment by pipermerriam** [comment]
Also, it may actually be picklable now or the issue may actually be a circular import hiding in the codebase that is only triggered if imports are done in a specific order.

**Comment by cburgdorf** [comment]
This has been fixed recently
