### ISSUE TITLE
Flaky tests/p2p/test_token_bucket.py::assert_fuzzy_equal

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/trinity#967]
### What is wrong?

`tests/p2p/test_token_bucket.py::assert_fuzzy_equal` failing too often on CI

- Example: https://circleci.com/gh/ethereum/trinity/90067

### How can it be fixed

uninvestigated yet

**Comment by pipermerriam** [comment]
I'm leaning towards a monkeypatch based solution to manually control the flow of time and remove all fuzzy-ness.  This will result in a little bit of *testing the implementation* but I think we can get reliable tests that do an adequate job of testing the functionality with this approach.

**Comment by gsalgado** [comment]
I could reproduce this locally with `pytest -n 8 --count=100 tests/p2p/test_token_bucket.py::test_token_bucket_refills_itself` (needs the `pytest-repeat` package installed), but haven't had a chance to dig into it yet. Hopefully somebody will beat me to it ;-)
