### ISSUE TITLE
Sync health check

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/trinity#99]
### What is wrong?

With the new plugin architecture we end up with *loose* coupling.  I had a long running sync where the discovery service stopped responding (no diagnosis).  This meant my client stopped establishing new connections.

### How can it be fixed

We should implement some kind of health check in the main `eth1` syncing trinity process (and really any of the main apps we write) that validates that all of the necessary components are running/responding and crashes the application if they are unresponsive.

**Comment by pipermerriam** [comment]
This has become more important imho based on my work on #536 .  The services that plugin runs are critical to the health of the node and if they crash the trinity node should really probably crash with it.

**Comment by carver** [comment]
Maybe `DaemonPlugin` to follow along our naming from `BaseService`?

Or maybe this should just apply to all plugins: if any one of them dies, it takes down Trinity with it.

**Comment by lithp** [comment]
I think this makes a lot of sense!

 A simple implementation might be for the main process to run a watchdog: `main_endpoint.subscribe(FeedTheWatchdog, self.feed_watchdog)`. All processes that we consider important run a coro which sends something like `endpoint.broadcast(FeedTheWatchdog("discovery"))` every x seconds. If the watchdog ever notices that it's stopped receiving messages from any one service it brings trinity down. This would detect things like the discovery process failing to start and the discovery process crashing or stalling it's event loop, but it wouldn't detect some other critical coro failing and leaving behind just the coro which feeds the watchdog.

**Comment by pipermerriam** [comment]
Watchdog is probably a good starting point.  I'm thinking for this to be robust, we should eventually be able to declare something like:

The discovery service is healthy if:

- The response to event `X` satisfies this `health_check_fn(response)`
- ...

Basically, registering some set of periodic checks that run which can have arbitrary logic.  These could start out as hard coded/.
